// Code generated by boxer/public/semistructured/leeway/marshall/go/marshallgen — DO NOT EDIT.

package trail

import (
	"iter"

	"github.com/stergiotis/boxer/public/observability/eh/eb"
	dmlruntime "github.com/stergiotis/boxer/public/semistructured/leeway/dml/runtime"
	raruntime "github.com/stergiotis/boxer/public/semistructured/leeway/readaccess/runtime"
)

// --- Caller-assigned membership ids (registry-stable target). ---

const (
	kindRuntimeKindAgentGrant  uint64 = 9223372049739677902
	kindAgentGrantEvent        uint64 = 9223372049739677903
	kindAgentGrantRequest      uint64 = 9223372049739677985
	kindAgentGrantPlan         uint64 = 9223372049739677904
	kindAgentGrantPlanDigest   uint64 = 9223372049739677905
	kindAgentGrantEntries      uint64 = 9223372049739677906
	kindAgentGrantLaunches     uint64 = 9223372049739677907
	kindAgentGrantDestinations uint64 = 9223372049739677908
	kindAgentGrantCallsBudget  uint64 = 9223372049739677909
	kindAgentGrantDeadlineMs   uint64 = 9223372049739677910
	kindAgentGrantDecidedBy    uint64 = 9223372049739677911
	kindAgentGrantReason       uint64 = 9223372049739677912
)

// agentGrantSymbolAttrI is the InAttr-side view of the symbol section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type agentGrantSymbolAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// agentGrantSymbolSecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type agentGrantSymbolSecI[Attr any, Ent any] interface {
	BeginAttribute(value string) Attr
	EndSection() Ent
}

// agentGrantStringArrayAttrI is the InAttr-side view of the stringArray section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type agentGrantStringArrayAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	AddToContainerP(value string)
	EndAttributeP()
}

// agentGrantStringArraySecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type agentGrantStringArraySecI[Attr any, Ent any] interface {
	BeginAttribute() Attr
	BeginAttributeSingle(value string) Attr
	EndSection() Ent
}

// agentGrantU32ArrayAttrI is the InAttr-side view of the u32Array section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type agentGrantU32ArrayAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// agentGrantU32ArraySecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type agentGrantU32ArraySecI[Attr any, Ent any] interface {
	BeginAttributeSingle(value uint32) Attr
	EndSection() Ent
}

// agentGrantI64ArrayAttrI is the InAttr-side view of the i64Array section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type agentGrantI64ArrayAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// agentGrantI64ArraySecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type agentGrantI64ArraySecI[Attr any, Ent any] interface {
	BeginAttributeSingle(value int64) Attr
	EndSection() Ent
}

// agentGrantEntityI is the entity-builder surface agentGrantAddSections drives.
// It always lists the per-section getters; the entity-frame methods
// (BeginEntity / plain setters / CommitEntity) are added only for the
// full codec's BuildEntities. AddSections stacks sections onto a frame
// the caller already owns, so it needs none of them — which lets a
// store drive it with a builder whose frame control is unexported
// (ADR-0100 SD6). Ent is the builder pointer.
type agentGrantEntityI[
	SymbolAttr agentGrantSymbolAttrI,
	SymbolSec agentGrantSymbolSecI[SymbolAttr, Ent],
	StringArrayAttr agentGrantStringArrayAttrI,
	StringArraySec agentGrantStringArraySecI[StringArrayAttr, Ent],
	U32ArrayAttr agentGrantU32ArrayAttrI,
	U32ArraySec agentGrantU32ArraySecI[U32ArrayAttr, Ent],
	I64ArrayAttr agentGrantI64ArrayAttrI,
	I64ArraySec agentGrantI64ArraySecI[I64ArrayAttr, Ent],
	Ent any,
] interface {
	GetSectionSymbol() SymbolSec
	GetSectionStringArray() StringArraySec
	GetSectionU32Array() U32ArraySec
	GetSectionI64Array() I64ArraySec
}

// agentGrantEmitSectionSymbol writes this kind's symbol attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func agentGrantEmitSectionSymbol[
	SymbolAttr agentGrantSymbolAttrI,
	SymbolSec agentGrantSymbolSecI[SymbolAttr, Ent],
	Ent any,
](symbolSec SymbolSec, row AgentGrant) (err error) {
	symbolSecAttr_Kind := symbolSec.BeginAttribute(row.Kind)
	symbolSecAttr_Kind.AddMembershipLowCardRefP(kindRuntimeKindAgentGrant)
	symbolSecAttr_Kind.EndAttributeP()
	symbolSecAttr_Event := symbolSec.BeginAttribute(row.Event)
	symbolSecAttr_Event.AddMembershipLowCardRefP(kindAgentGrantEvent)
	symbolSecAttr_Event.EndAttributeP()
	symbolSecAttr_DecidedBy := symbolSec.BeginAttribute(row.DecidedBy)
	symbolSecAttr_DecidedBy.AddMembershipLowCardRefP(kindAgentGrantDecidedBy)
	symbolSecAttr_DecidedBy.EndAttributeP()
	return
}

// agentGrantEmitSectionStringArray writes this kind's stringArray attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func agentGrantEmitSectionStringArray[
	StringArrayAttr agentGrantStringArrayAttrI,
	StringArraySec agentGrantStringArraySecI[StringArrayAttr, Ent],
	Ent any,
](stringArraySec StringArraySec, row AgentGrant) (err error) {
	if row.Request.Has {
		stringArraySecAttr_Request := stringArraySec.BeginAttributeSingle(row.Request.Val)
		stringArraySecAttr_Request.AddMembershipLowCardRefP(kindAgentGrantRequest)
		stringArraySecAttr_Request.EndAttributeP()
	}
	stringArraySecAttr_Plan := stringArraySec.BeginAttributeSingle(row.Plan)
	stringArraySecAttr_Plan.AddMembershipLowCardRefP(kindAgentGrantPlan)
	stringArraySecAttr_Plan.EndAttributeP()
	stringArraySecAttr_PlanDigest := stringArraySec.BeginAttributeSingle(row.PlanDigest)
	stringArraySecAttr_PlanDigest.AddMembershipLowCardRefP(kindAgentGrantPlanDigest)
	stringArraySecAttr_PlanDigest.EndAttributeP()
	if len(row.Entries) > 0 {
		stringArraySecAttr_Entries := stringArraySec.BeginAttribute()
		for _, v := range row.Entries {
			stringArraySecAttr_Entries.AddToContainerP(v)
		}
		stringArraySecAttr_Entries.AddMembershipLowCardRefP(kindAgentGrantEntries)
		stringArraySecAttr_Entries.EndAttributeP()
	}
	if len(row.Launches) > 0 {
		stringArraySecAttr_Launches := stringArraySec.BeginAttribute()
		for _, v := range row.Launches {
			stringArraySecAttr_Launches.AddToContainerP(v)
		}
		stringArraySecAttr_Launches.AddMembershipLowCardRefP(kindAgentGrantLaunches)
		stringArraySecAttr_Launches.EndAttributeP()
	}
	if len(row.Destinations) > 0 {
		stringArraySecAttr_Destinations := stringArraySec.BeginAttribute()
		for _, v := range row.Destinations {
			stringArraySecAttr_Destinations.AddToContainerP(v)
		}
		stringArraySecAttr_Destinations.AddMembershipLowCardRefP(kindAgentGrantDestinations)
		stringArraySecAttr_Destinations.EndAttributeP()
	}
	if len(row.Reason) > 0 {
		stringArraySecAttr_Reason := stringArraySec.BeginAttribute()
		for _, v := range row.Reason {
			stringArraySecAttr_Reason.AddToContainerP(v)
		}
		stringArraySecAttr_Reason.AddMembershipLowCardRefP(kindAgentGrantReason)
		stringArraySecAttr_Reason.EndAttributeP()
	}
	return
}

// agentGrantEmitSectionU32Array writes this kind's u32Array attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func agentGrantEmitSectionU32Array[
	U32ArrayAttr agentGrantU32ArrayAttrI,
	U32ArraySec agentGrantU32ArraySecI[U32ArrayAttr, Ent],
	Ent any,
](u32ArraySec U32ArraySec, row AgentGrant) (err error) {
	u32ArraySecAttr_CallsBudget := u32ArraySec.BeginAttributeSingle(row.CallsBudget)
	u32ArraySecAttr_CallsBudget.AddMembershipLowCardRefP(kindAgentGrantCallsBudget)
	u32ArraySecAttr_CallsBudget.EndAttributeP()
	return
}

// agentGrantEmitSectionI64Array writes this kind's i64Array attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func agentGrantEmitSectionI64Array[
	I64ArrayAttr agentGrantI64ArrayAttrI,
	I64ArraySec agentGrantI64ArraySecI[I64ArrayAttr, Ent],
	Ent any,
](i64ArraySec I64ArraySec, row AgentGrant) (err error) {
	i64ArraySecAttr_DeadlineMs := i64ArraySec.BeginAttributeSingle(row.DeadlineMs)
	i64ArraySecAttr_DeadlineMs.AddMembershipLowCardRefP(kindAgentGrantDeadlineMs)
	i64ArraySecAttr_DeadlineMs.EndAttributeP()
	return
}

// agentGrantAddSections contributes this kind's tagged sections to the OPEN
// entity on dml — the BuildEntities body without the entity frame.
// The caller owns BeginEntity / plain setters / CommitEntity.
func agentGrantAddSections[
	SymbolAttr agentGrantSymbolAttrI,
	SymbolSec agentGrantSymbolSecI[SymbolAttr, Ent],
	StringArrayAttr agentGrantStringArrayAttrI,
	StringArraySec agentGrantStringArraySecI[StringArrayAttr, Ent],
	U32ArrayAttr agentGrantU32ArrayAttrI,
	U32ArraySec agentGrantU32ArraySecI[U32ArrayAttr, Ent],
	I64ArrayAttr agentGrantI64ArrayAttrI,
	I64ArraySec agentGrantI64ArraySecI[I64ArrayAttr, Ent],
	Ent any,
	DML agentGrantEntityI[
		SymbolAttr, SymbolSec,
		StringArrayAttr, StringArraySec,
		U32ArrayAttr, U32ArraySec,
		I64ArrayAttr, I64ArraySec,
		Ent,
	],
](dml DML, row AgentGrant) (err error) {
	// --- symbol. ---
	symbolSec := dml.GetSectionSymbol()
	err = agentGrantEmitSectionSymbol(symbolSec, row)
	if err != nil {
		return
	}
	symbolSec.EndSection()
	// --- stringArray. ---
	stringArraySec := dml.GetSectionStringArray()
	err = agentGrantEmitSectionStringArray(stringArraySec, row)
	if err != nil {
		return
	}
	stringArraySec.EndSection()
	// --- u32Array. ---
	u32ArraySec := dml.GetSectionU32Array()
	err = agentGrantEmitSectionU32Array(u32ArraySec, row)
	if err != nil {
		return
	}
	u32ArraySec.EndSection()
	// --- i64Array. ---
	i64ArraySec := dml.GetSectionI64Array()
	err = agentGrantEmitSectionI64Array(i64ArraySec, row)
	if err != nil {
		return
	}
	i64ArraySec.EndSection()
	return
}

// agentGrantSymbolAttrsReadI is the Attributes-side view of the symbol section.
type agentGrantSymbolAttrsReadI interface {
	GetAttrValueValue(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) string
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// agentGrantSymbolMembsReadI is the Memberships-side view of the symbol section.
type agentGrantSymbolMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// agentGrantStringArrayAttrsReadI is the Attributes-side view of the stringArray section.
type agentGrantStringArrayAttrsReadI interface {
	GetAttrValueValue(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[string]
	GetAttrValueSingle(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) (string, error)
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// agentGrantStringArrayMembsReadI is the Memberships-side view of the stringArray section.
type agentGrantStringArrayMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// agentGrantU32ArrayAttrsReadI is the Attributes-side view of the u32Array section.
type agentGrantU32ArrayAttrsReadI interface {
	GetAttrValueSingle(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) (uint32, error)
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// agentGrantU32ArrayMembsReadI is the Memberships-side view of the u32Array section.
type agentGrantU32ArrayMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// agentGrantI64ArrayAttrsReadI is the Attributes-side view of the i64Array section.
type agentGrantI64ArrayAttrsReadI interface {
	GetAttrValueSingle(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) (int64, error)
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// agentGrantI64ArrayMembsReadI is the Memberships-side view of the i64Array section.
type agentGrantI64ArrayMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// agentGrantReadRow reads row i as one optional AgentGrant component: presence-
// gated (a row carrying none of the kind's memberships yields
// present=false), membership-matched. A slot carrying more
// attributes than this kind's shape admits is an error, for every
// shape including containers. Plain-
// bound fields stay zero — the caller owns the envelope. The
// Attrs/Membs readers bind by type inference at the call site, as
// with FillFromArrow.
func agentGrantReadRow[
	SymbolAttrs agentGrantSymbolAttrsReadI,
	SymbolMembs agentGrantSymbolMembsReadI,
	StringArrayAttrs agentGrantStringArrayAttrsReadI,
	StringArrayMembs agentGrantStringArrayMembsReadI,
	U32ArrayAttrs agentGrantU32ArrayAttrsReadI,
	U32ArrayMembs agentGrantU32ArrayMembsReadI,
	I64ArrayAttrs agentGrantI64ArrayAttrsReadI,
	I64ArrayMembs agentGrantI64ArrayMembsReadI,
](
	i int,
	symbolAttrs SymbolAttrs,
	symbolMembs SymbolMembs,
	stringArrayAttrs StringArrayAttrs,
	stringArrayMembs StringArrayMembs,
	u32ArrayAttrs U32ArrayAttrs,
	u32ArrayMembs U32ArrayMembs,
	i64ArrayAttrs I64ArrayAttrs,
	i64ArrayMembs I64ArrayMembs,
) (row AgentGrant, present bool, err error) {
	// --- symbol. ---
	var symbolKindVal string
	var symbolKindCount int
	var symbolKindLastAttr int64
	var symbolEventVal string
	var symbolEventCount int
	var symbolEventLastAttr int64
	var symbolDecidedByVal string
	var symbolDecidedByCount int
	var symbolDecidedByLastAttr int64
	nsymbol := symbolAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nsymbol; attrJ++ {
		for membID := range symbolMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindRuntimeKindAgentGrant:
				if symbolKindLastAttr != attrJ+1 {
					symbolKindLastAttr = attrJ + 1
					symbolKindCount++
				}
				val := symbolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				symbolKindVal = val
			case kindAgentGrantEvent:
				if symbolEventLastAttr != attrJ+1 {
					symbolEventLastAttr = attrJ + 1
					symbolEventCount++
				}
				val := symbolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				symbolEventVal = val
			case kindAgentGrantDecidedBy:
				if symbolDecidedByLastAttr != attrJ+1 {
					symbolDecidedByLastAttr = attrJ + 1
					symbolDecidedByCount++
				}
				val := symbolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				symbolDecidedByVal = val
			}
		}
	}
	if symbolKindCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbol").Str("membership", "runtimeKindAgentGrant").Int("got", symbolKindCount).Errorf("slot symbol@runtimeKindAgentGrant (field Kind) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolKindCount)
		return
	}
	if symbolKindCount == 1 {
		row.Kind = symbolKindVal
		present = true
	}
	if symbolEventCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbol").Str("membership", "agentGrantEvent").Int("got", symbolEventCount).Errorf("slot symbol@agentGrantEvent (field Event) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolEventCount)
		return
	}
	if symbolEventCount == 1 {
		row.Event = symbolEventVal
		present = true
	}
	if symbolDecidedByCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbol").Str("membership", "agentGrantDecidedBy").Int("got", symbolDecidedByCount).Errorf("slot symbol@agentGrantDecidedBy (field DecidedBy) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolDecidedByCount)
		return
	}
	if symbolDecidedByCount == 1 {
		row.DecidedBy = symbolDecidedByVal
		present = true
	}
	// --- stringArray. ---
	var stringArrayRequestVal string
	var stringArrayRequestCount int
	var stringArrayRequestLastAttr int64
	var stringArrayPlanVal string
	var stringArrayPlanCount int
	var stringArrayPlanLastAttr int64
	var stringArrayPlanDigestVal string
	var stringArrayPlanDigestCount int
	var stringArrayPlanDigestLastAttr int64
	var stringArrayEntriesSlice []string
	var stringArrayEntriesCount int
	var stringArrayEntriesLastAttr int64
	var stringArrayLaunchesSlice []string
	var stringArrayLaunchesCount int
	var stringArrayLaunchesLastAttr int64
	var stringArrayDestinationsSlice []string
	var stringArrayDestinationsCount int
	var stringArrayDestinationsLastAttr int64
	var stringArrayReasonSlice []string
	var stringArrayReasonCount int
	var stringArrayReasonLastAttr int64
	nstringArray := stringArrayAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nstringArray; attrJ++ {
		for membID := range stringArrayMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindAgentGrantRequest:
				if stringArrayRequestLastAttr != attrJ+1 {
					stringArrayRequestLastAttr = attrJ + 1
					stringArrayRequestCount++
				}
				val, valErr := stringArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "agentGrantRequest").Str("field", "Request").Errorf("slot stringArray@agentGrantRequest (field Request) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				stringArrayRequestVal = val
			case kindAgentGrantPlan:
				if stringArrayPlanLastAttr != attrJ+1 {
					stringArrayPlanLastAttr = attrJ + 1
					stringArrayPlanCount++
				}
				val, valErr := stringArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "agentGrantPlan").Str("field", "Plan").Errorf("slot stringArray@agentGrantPlan (field Plan) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				stringArrayPlanVal = val
			case kindAgentGrantPlanDigest:
				if stringArrayPlanDigestLastAttr != attrJ+1 {
					stringArrayPlanDigestLastAttr = attrJ + 1
					stringArrayPlanDigestCount++
				}
				val, valErr := stringArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "agentGrantPlanDigest").Str("field", "PlanDigest").Errorf("slot stringArray@agentGrantPlanDigest (field PlanDigest) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				stringArrayPlanDigestVal = val
			case kindAgentGrantEntries:
				if stringArrayEntriesLastAttr != attrJ+1 {
					stringArrayEntriesLastAttr = attrJ + 1
					stringArrayEntriesCount++
				}
				for v := range stringArrayAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
					stringArrayEntriesSlice = append(stringArrayEntriesSlice, v)
				}
			case kindAgentGrantLaunches:
				if stringArrayLaunchesLastAttr != attrJ+1 {
					stringArrayLaunchesLastAttr = attrJ + 1
					stringArrayLaunchesCount++
				}
				for v := range stringArrayAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
					stringArrayLaunchesSlice = append(stringArrayLaunchesSlice, v)
				}
			case kindAgentGrantDestinations:
				if stringArrayDestinationsLastAttr != attrJ+1 {
					stringArrayDestinationsLastAttr = attrJ + 1
					stringArrayDestinationsCount++
				}
				for v := range stringArrayAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
					stringArrayDestinationsSlice = append(stringArrayDestinationsSlice, v)
				}
			case kindAgentGrantReason:
				if stringArrayReasonLastAttr != attrJ+1 {
					stringArrayReasonLastAttr = attrJ + 1
					stringArrayReasonCount++
				}
				for v := range stringArrayAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
					stringArrayReasonSlice = append(stringArrayReasonSlice, v)
				}
			}
		}
	}
	if stringArrayRequestCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "agentGrantRequest").Int("got", stringArrayRequestCount).Errorf("slot stringArray@agentGrantRequest (field Request) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", stringArrayRequestCount)
		return
	}
	if stringArrayRequestCount == 1 {
		row.Request.Val = stringArrayRequestVal
		row.Request.Has = true
		present = true
	}
	if stringArrayPlanCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "agentGrantPlan").Int("got", stringArrayPlanCount).Errorf("slot stringArray@agentGrantPlan (field Plan) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", stringArrayPlanCount)
		return
	}
	if stringArrayPlanCount == 1 {
		row.Plan = stringArrayPlanVal
		present = true
	}
	if stringArrayPlanDigestCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "agentGrantPlanDigest").Int("got", stringArrayPlanDigestCount).Errorf("slot stringArray@agentGrantPlanDigest (field PlanDigest) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", stringArrayPlanDigestCount)
		return
	}
	if stringArrayPlanDigestCount == 1 {
		row.PlanDigest = stringArrayPlanDigestVal
		present = true
	}
	if stringArrayEntriesCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "agentGrantEntries").Int("got", stringArrayEntriesCount).Errorf("slot stringArray@agentGrantEntries (field Entries) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", stringArrayEntriesCount)
		return
	}
	if stringArrayEntriesSlice != nil {
		row.Entries = stringArrayEntriesSlice
		present = true
	}
	if stringArrayLaunchesCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "agentGrantLaunches").Int("got", stringArrayLaunchesCount).Errorf("slot stringArray@agentGrantLaunches (field Launches) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", stringArrayLaunchesCount)
		return
	}
	if stringArrayLaunchesSlice != nil {
		row.Launches = stringArrayLaunchesSlice
		present = true
	}
	if stringArrayDestinationsCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "agentGrantDestinations").Int("got", stringArrayDestinationsCount).Errorf("slot stringArray@agentGrantDestinations (field Destinations) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", stringArrayDestinationsCount)
		return
	}
	if stringArrayDestinationsSlice != nil {
		row.Destinations = stringArrayDestinationsSlice
		present = true
	}
	if stringArrayReasonCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "agentGrantReason").Int("got", stringArrayReasonCount).Errorf("slot stringArray@agentGrantReason (field Reason) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", stringArrayReasonCount)
		return
	}
	if stringArrayReasonSlice != nil {
		row.Reason = stringArrayReasonSlice
		present = true
	}
	// --- u32Array. ---
	var u32ArrayCallsBudgetVal uint32
	var u32ArrayCallsBudgetCount int
	var u32ArrayCallsBudgetLastAttr int64
	nu32Array := u32ArrayAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nu32Array; attrJ++ {
		for membID := range u32ArrayMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindAgentGrantCallsBudget:
				if u32ArrayCallsBudgetLastAttr != attrJ+1 {
					u32ArrayCallsBudgetLastAttr = attrJ + 1
					u32ArrayCallsBudgetCount++
				}
				val, valErr := u32ArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "u32Array").Str("membership", "agentGrantCallsBudget").Str("field", "CallsBudget").Errorf("slot u32Array@agentGrantCallsBudget (field CallsBudget) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				u32ArrayCallsBudgetVal = val
			}
		}
	}
	if u32ArrayCallsBudgetCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "u32Array").Str("membership", "agentGrantCallsBudget").Int("got", u32ArrayCallsBudgetCount).Errorf("slot u32Array@agentGrantCallsBudget (field CallsBudget) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", u32ArrayCallsBudgetCount)
		return
	}
	if u32ArrayCallsBudgetCount == 1 {
		row.CallsBudget = u32ArrayCallsBudgetVal
		present = true
	}
	// --- i64Array. ---
	var i64ArrayDeadlineMsVal int64
	var i64ArrayDeadlineMsCount int
	var i64ArrayDeadlineMsLastAttr int64
	ni64Array := i64ArrayAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < ni64Array; attrJ++ {
		for membID := range i64ArrayMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindAgentGrantDeadlineMs:
				if i64ArrayDeadlineMsLastAttr != attrJ+1 {
					i64ArrayDeadlineMsLastAttr = attrJ + 1
					i64ArrayDeadlineMsCount++
				}
				val, valErr := i64ArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "i64Array").Str("membership", "agentGrantDeadlineMs").Str("field", "DeadlineMs").Errorf("slot i64Array@agentGrantDeadlineMs (field DeadlineMs) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				i64ArrayDeadlineMsVal = val
			}
		}
	}
	if i64ArrayDeadlineMsCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "i64Array").Str("membership", "agentGrantDeadlineMs").Int("got", i64ArrayDeadlineMsCount).Errorf("slot i64Array@agentGrantDeadlineMs (field DeadlineMs) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", i64ArrayDeadlineMsCount)
		return
	}
	if i64ArrayDeadlineMsCount == 1 {
		row.DeadlineMs = i64ArrayDeadlineMsVal
		present = true
	}
	return
}
