// Code generated by boxer/public/semistructured/leeway/marshall/go/marshallgen — DO NOT EDIT.

package trail

import (
	"iter"

	"github.com/stergiotis/boxer/public/observability/eh/eb"
	dmlruntime "github.com/stergiotis/boxer/public/semistructured/leeway/dml/runtime"
	raruntime "github.com/stergiotis/boxer/public/semistructured/leeway/readaccess/runtime"
)

// --- Caller-assigned membership ids (registry-stable target). ---

const (
	kindRuntimeKindLlmMessage uint64 = 9223372049739677850
	kindLlmMessageCallId      uint64 = 9223372049739677851
	kindLlmMessageOrdinal     uint64 = 9223372049739677855
	kindLlmMessageRole        uint64 = 9223372049739677856
	kindLlmMessageSensitivity uint64 = 9223372049739677854
	kindLlmMessageBytes       uint64 = 9223372049739677897
	kindLlmMessageDigest      uint64 = 9223372049739677898
	kindLlmMessageToolCallId  uint64 = 9223372049739677859
	kindLlmMessageToolCallIds uint64 = 9223372049739677899
	kindLlmMessageToolNames   uint64 = 9223372049739677900
	kindLlmMessageImages      uint64 = 9223372049739677861
)

// llmMessageSymbolAttrI is the InAttr-side view of the symbol section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type llmMessageSymbolAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// llmMessageSymbolSecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type llmMessageSymbolSecI[Attr any, Ent any] interface {
	BeginAttribute(value string) Attr
	EndSection() Ent
}

// llmMessageStringArrayAttrI is the InAttr-side view of the stringArray section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type llmMessageStringArrayAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	AddToContainerP(value string)
	EndAttributeP()
}

// llmMessageStringArraySecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type llmMessageStringArraySecI[Attr any, Ent any] interface {
	BeginAttribute() Attr
	BeginAttributeSingle(value string) Attr
	EndSection() Ent
}

// llmMessageU32ArrayAttrI is the InAttr-side view of the u32Array section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type llmMessageU32ArrayAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// llmMessageU32ArraySecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type llmMessageU32ArraySecI[Attr any, Ent any] interface {
	BeginAttributeSingle(value uint32) Attr
	EndSection() Ent
}

// llmMessageU64ArrayAttrI is the InAttr-side view of the u64Array section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type llmMessageU64ArrayAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// llmMessageU64ArraySecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type llmMessageU64ArraySecI[Attr any, Ent any] interface {
	BeginAttributeSingle(value uint64) Attr
	EndSection() Ent
}

// llmMessageSymbolArrayAttrI is the InAttr-side view of the symbolArray section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type llmMessageSymbolArrayAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	AddToContainerP(value string)
	EndAttributeP()
}

// llmMessageSymbolArraySecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type llmMessageSymbolArraySecI[Attr any, Ent any] interface {
	BeginAttribute() Attr
	EndSection() Ent
}

// llmMessageEntityI is the entity-builder surface llmMessageAddSections drives.
// It always lists the per-section getters; the entity-frame methods
// (BeginEntity / plain setters / CommitEntity) are added only for the
// full codec's BuildEntities. AddSections stacks sections onto a frame
// the caller already owns, so it needs none of them — which lets a
// store drive it with a builder whose frame control is unexported
// (ADR-0100 SD6). Ent is the builder pointer.
type llmMessageEntityI[
	SymbolAttr llmMessageSymbolAttrI,
	SymbolSec llmMessageSymbolSecI[SymbolAttr, Ent],
	StringArrayAttr llmMessageStringArrayAttrI,
	StringArraySec llmMessageStringArraySecI[StringArrayAttr, Ent],
	U32ArrayAttr llmMessageU32ArrayAttrI,
	U32ArraySec llmMessageU32ArraySecI[U32ArrayAttr, Ent],
	U64ArrayAttr llmMessageU64ArrayAttrI,
	U64ArraySec llmMessageU64ArraySecI[U64ArrayAttr, Ent],
	SymbolArrayAttr llmMessageSymbolArrayAttrI,
	SymbolArraySec llmMessageSymbolArraySecI[SymbolArrayAttr, Ent],
	Ent any,
] interface {
	GetSectionSymbol() SymbolSec
	GetSectionStringArray() StringArraySec
	GetSectionU32Array() U32ArraySec
	GetSectionU64Array() U64ArraySec
	GetSectionSymbolArray() SymbolArraySec
}

// llmMessageEmitSectionSymbol writes this kind's symbol attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func llmMessageEmitSectionSymbol[
	SymbolAttr llmMessageSymbolAttrI,
	SymbolSec llmMessageSymbolSecI[SymbolAttr, Ent],
	Ent any,
](symbolSec SymbolSec, row LlmMessage) (err error) {
	symbolSecAttr_Kind := symbolSec.BeginAttribute(row.Kind)
	symbolSecAttr_Kind.AddMembershipLowCardRefP(kindRuntimeKindLlmMessage)
	symbolSecAttr_Kind.EndAttributeP()
	symbolSecAttr_Role := symbolSec.BeginAttribute(row.Role)
	symbolSecAttr_Role.AddMembershipLowCardRefP(kindLlmMessageRole)
	symbolSecAttr_Role.EndAttributeP()
	symbolSecAttr_Sensitivity := symbolSec.BeginAttribute(row.Sensitivity)
	symbolSecAttr_Sensitivity.AddMembershipLowCardRefP(kindLlmMessageSensitivity)
	symbolSecAttr_Sensitivity.EndAttributeP()
	return
}

// llmMessageEmitSectionStringArray writes this kind's stringArray attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func llmMessageEmitSectionStringArray[
	StringArrayAttr llmMessageStringArrayAttrI,
	StringArraySec llmMessageStringArraySecI[StringArrayAttr, Ent],
	Ent any,
](stringArraySec StringArraySec, row LlmMessage) (err error) {
	stringArraySecAttr_CallId := stringArraySec.BeginAttributeSingle(row.CallId)
	stringArraySecAttr_CallId.AddMembershipLowCardRefP(kindLlmMessageCallId)
	stringArraySecAttr_CallId.EndAttributeP()
	stringArraySecAttr_Digest := stringArraySec.BeginAttributeSingle(row.Digest)
	stringArraySecAttr_Digest.AddMembershipLowCardRefP(kindLlmMessageDigest)
	stringArraySecAttr_Digest.EndAttributeP()
	if row.ToolCallId.Has {
		stringArraySecAttr_ToolCallId := stringArraySec.BeginAttributeSingle(row.ToolCallId.Val)
		stringArraySecAttr_ToolCallId.AddMembershipLowCardRefP(kindLlmMessageToolCallId)
		stringArraySecAttr_ToolCallId.EndAttributeP()
	}
	if len(row.ToolCallIds) > 0 {
		stringArraySecAttr_ToolCallIds := stringArraySec.BeginAttribute()
		for _, v := range row.ToolCallIds {
			stringArraySecAttr_ToolCallIds.AddToContainerP(v)
		}
		stringArraySecAttr_ToolCallIds.AddMembershipLowCardRefP(kindLlmMessageToolCallIds)
		stringArraySecAttr_ToolCallIds.EndAttributeP()
	}
	if len(row.Images) > 0 {
		stringArraySecAttr_Images := stringArraySec.BeginAttribute()
		for _, v := range row.Images {
			stringArraySecAttr_Images.AddToContainerP(v)
		}
		stringArraySecAttr_Images.AddMembershipLowCardRefP(kindLlmMessageImages)
		stringArraySecAttr_Images.EndAttributeP()
	}
	return
}

// llmMessageEmitSectionU32Array writes this kind's u32Array attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func llmMessageEmitSectionU32Array[
	U32ArrayAttr llmMessageU32ArrayAttrI,
	U32ArraySec llmMessageU32ArraySecI[U32ArrayAttr, Ent],
	Ent any,
](u32ArraySec U32ArraySec, row LlmMessage) (err error) {
	u32ArraySecAttr_Ordinal := u32ArraySec.BeginAttributeSingle(row.Ordinal)
	u32ArraySecAttr_Ordinal.AddMembershipLowCardRefP(kindLlmMessageOrdinal)
	u32ArraySecAttr_Ordinal.EndAttributeP()
	return
}

// llmMessageEmitSectionU64Array writes this kind's u64Array attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func llmMessageEmitSectionU64Array[
	U64ArrayAttr llmMessageU64ArrayAttrI,
	U64ArraySec llmMessageU64ArraySecI[U64ArrayAttr, Ent],
	Ent any,
](u64ArraySec U64ArraySec, row LlmMessage) (err error) {
	u64ArraySecAttr_Bytes := u64ArraySec.BeginAttributeSingle(row.Bytes)
	u64ArraySecAttr_Bytes.AddMembershipLowCardRefP(kindLlmMessageBytes)
	u64ArraySecAttr_Bytes.EndAttributeP()
	return
}

// llmMessageEmitSectionSymbolArray writes this kind's symbolArray attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func llmMessageEmitSectionSymbolArray[
	SymbolArrayAttr llmMessageSymbolArrayAttrI,
	SymbolArraySec llmMessageSymbolArraySecI[SymbolArrayAttr, Ent],
	Ent any,
](symbolArraySec SymbolArraySec, row LlmMessage) (err error) {
	if len(row.ToolNames) > 0 {
		symbolArraySecAttr_ToolNames := symbolArraySec.BeginAttribute()
		for _, v := range row.ToolNames {
			symbolArraySecAttr_ToolNames.AddToContainerP(v)
		}
		symbolArraySecAttr_ToolNames.AddMembershipLowCardRefP(kindLlmMessageToolNames)
		symbolArraySecAttr_ToolNames.EndAttributeP()
	}
	return
}

// llmMessageAddSections contributes this kind's tagged sections to the OPEN
// entity on dml — the BuildEntities body without the entity frame.
// The caller owns BeginEntity / plain setters / CommitEntity.
func llmMessageAddSections[
	SymbolAttr llmMessageSymbolAttrI,
	SymbolSec llmMessageSymbolSecI[SymbolAttr, Ent],
	StringArrayAttr llmMessageStringArrayAttrI,
	StringArraySec llmMessageStringArraySecI[StringArrayAttr, Ent],
	U32ArrayAttr llmMessageU32ArrayAttrI,
	U32ArraySec llmMessageU32ArraySecI[U32ArrayAttr, Ent],
	U64ArrayAttr llmMessageU64ArrayAttrI,
	U64ArraySec llmMessageU64ArraySecI[U64ArrayAttr, Ent],
	SymbolArrayAttr llmMessageSymbolArrayAttrI,
	SymbolArraySec llmMessageSymbolArraySecI[SymbolArrayAttr, Ent],
	Ent any,
	DML llmMessageEntityI[
		SymbolAttr, SymbolSec,
		StringArrayAttr, StringArraySec,
		U32ArrayAttr, U32ArraySec,
		U64ArrayAttr, U64ArraySec,
		SymbolArrayAttr, SymbolArraySec,
		Ent,
	],
](dml DML, row LlmMessage) (err error) {
	// --- symbol. ---
	symbolSec := dml.GetSectionSymbol()
	err = llmMessageEmitSectionSymbol(symbolSec, row)
	if err != nil {
		return
	}
	symbolSec.EndSection()
	// --- stringArray. ---
	stringArraySec := dml.GetSectionStringArray()
	err = llmMessageEmitSectionStringArray(stringArraySec, row)
	if err != nil {
		return
	}
	stringArraySec.EndSection()
	// --- u32Array. ---
	u32ArraySec := dml.GetSectionU32Array()
	err = llmMessageEmitSectionU32Array(u32ArraySec, row)
	if err != nil {
		return
	}
	u32ArraySec.EndSection()
	// --- u64Array. ---
	u64ArraySec := dml.GetSectionU64Array()
	err = llmMessageEmitSectionU64Array(u64ArraySec, row)
	if err != nil {
		return
	}
	u64ArraySec.EndSection()
	// --- symbolArray. ---
	symbolArraySec := dml.GetSectionSymbolArray()
	err = llmMessageEmitSectionSymbolArray(symbolArraySec, row)
	if err != nil {
		return
	}
	symbolArraySec.EndSection()
	return
}

// llmMessageSymbolAttrsReadI is the Attributes-side view of the symbol section.
type llmMessageSymbolAttrsReadI interface {
	GetAttrValueValue(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) string
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// llmMessageSymbolMembsReadI is the Memberships-side view of the symbol section.
type llmMessageSymbolMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// llmMessageStringArrayAttrsReadI is the Attributes-side view of the stringArray section.
type llmMessageStringArrayAttrsReadI interface {
	GetAttrValueValue(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[string]
	GetAttrValueSingle(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) (string, error)
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// llmMessageStringArrayMembsReadI is the Memberships-side view of the stringArray section.
type llmMessageStringArrayMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// llmMessageU32ArrayAttrsReadI is the Attributes-side view of the u32Array section.
type llmMessageU32ArrayAttrsReadI interface {
	GetAttrValueSingle(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) (uint32, error)
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// llmMessageU32ArrayMembsReadI is the Memberships-side view of the u32Array section.
type llmMessageU32ArrayMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// llmMessageU64ArrayAttrsReadI is the Attributes-side view of the u64Array section.
type llmMessageU64ArrayAttrsReadI interface {
	GetAttrValueSingle(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) (uint64, error)
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// llmMessageU64ArrayMembsReadI is the Memberships-side view of the u64Array section.
type llmMessageU64ArrayMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// llmMessageSymbolArrayAttrsReadI is the Attributes-side view of the symbolArray section.
type llmMessageSymbolArrayAttrsReadI interface {
	GetAttrValueValue(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[string]
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// llmMessageSymbolArrayMembsReadI is the Memberships-side view of the symbolArray section.
type llmMessageSymbolArrayMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// llmMessageReadRow reads row i as one optional LlmMessage component: presence-
// gated (a row carrying none of the kind's memberships yields
// present=false), membership-matched. A slot carrying more
// attributes than this kind's shape admits is an error, for every
// shape including containers. Plain-
// bound fields stay zero — the caller owns the envelope. The
// Attrs/Membs readers bind by type inference at the call site, as
// with FillFromArrow.
func llmMessageReadRow[
	SymbolAttrs llmMessageSymbolAttrsReadI,
	SymbolMembs llmMessageSymbolMembsReadI,
	StringArrayAttrs llmMessageStringArrayAttrsReadI,
	StringArrayMembs llmMessageStringArrayMembsReadI,
	U32ArrayAttrs llmMessageU32ArrayAttrsReadI,
	U32ArrayMembs llmMessageU32ArrayMembsReadI,
	U64ArrayAttrs llmMessageU64ArrayAttrsReadI,
	U64ArrayMembs llmMessageU64ArrayMembsReadI,
	SymbolArrayAttrs llmMessageSymbolArrayAttrsReadI,
	SymbolArrayMembs llmMessageSymbolArrayMembsReadI,
](
	i int,
	symbolAttrs SymbolAttrs,
	symbolMembs SymbolMembs,
	stringArrayAttrs StringArrayAttrs,
	stringArrayMembs StringArrayMembs,
	u32ArrayAttrs U32ArrayAttrs,
	u32ArrayMembs U32ArrayMembs,
	u64ArrayAttrs U64ArrayAttrs,
	u64ArrayMembs U64ArrayMembs,
	symbolArrayAttrs SymbolArrayAttrs,
	symbolArrayMembs SymbolArrayMembs,
) (row LlmMessage, present bool, err error) {
	// --- symbol. ---
	var symbolKindVal string
	var symbolKindCount int
	var symbolKindLastAttr int64
	var symbolRoleVal string
	var symbolRoleCount int
	var symbolRoleLastAttr int64
	var symbolSensitivityVal string
	var symbolSensitivityCount int
	var symbolSensitivityLastAttr int64
	nsymbol := symbolAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nsymbol; attrJ++ {
		for membID := range symbolMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindRuntimeKindLlmMessage:
				if symbolKindLastAttr != attrJ+1 {
					symbolKindLastAttr = attrJ + 1
					symbolKindCount++
				}
				val := symbolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				symbolKindVal = val
			case kindLlmMessageRole:
				if symbolRoleLastAttr != attrJ+1 {
					symbolRoleLastAttr = attrJ + 1
					symbolRoleCount++
				}
				val := symbolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				symbolRoleVal = val
			case kindLlmMessageSensitivity:
				if symbolSensitivityLastAttr != attrJ+1 {
					symbolSensitivityLastAttr = attrJ + 1
					symbolSensitivityCount++
				}
				val := symbolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				symbolSensitivityVal = val
			}
		}
	}
	if symbolKindCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbol").Str("membership", "runtimeKindLlmMessage").Int("got", symbolKindCount).Errorf("slot symbol@runtimeKindLlmMessage (field Kind) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolKindCount)
		return
	}
	if symbolKindCount == 1 {
		row.Kind = symbolKindVal
		present = true
	}
	if symbolRoleCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbol").Str("membership", "llmMessageRole").Int("got", symbolRoleCount).Errorf("slot symbol@llmMessageRole (field Role) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolRoleCount)
		return
	}
	if symbolRoleCount == 1 {
		row.Role = symbolRoleVal
		present = true
	}
	if symbolSensitivityCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbol").Str("membership", "llmMessageSensitivity").Int("got", symbolSensitivityCount).Errorf("slot symbol@llmMessageSensitivity (field Sensitivity) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolSensitivityCount)
		return
	}
	if symbolSensitivityCount == 1 {
		row.Sensitivity = symbolSensitivityVal
		present = true
	}
	// --- stringArray. ---
	var stringArrayCallIdVal string
	var stringArrayCallIdCount int
	var stringArrayCallIdLastAttr int64
	var stringArrayDigestVal string
	var stringArrayDigestCount int
	var stringArrayDigestLastAttr int64
	var stringArrayToolCallIdVal string
	var stringArrayToolCallIdCount int
	var stringArrayToolCallIdLastAttr int64
	var stringArrayToolCallIdsSlice []string
	var stringArrayToolCallIdsCount int
	var stringArrayToolCallIdsLastAttr int64
	var stringArrayImagesSlice []string
	var stringArrayImagesCount int
	var stringArrayImagesLastAttr int64
	nstringArray := stringArrayAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nstringArray; attrJ++ {
		for membID := range stringArrayMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindLlmMessageCallId:
				if stringArrayCallIdLastAttr != attrJ+1 {
					stringArrayCallIdLastAttr = attrJ + 1
					stringArrayCallIdCount++
				}
				val, valErr := stringArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "llmMessageCallId").Str("field", "CallId").Errorf("slot stringArray@llmMessageCallId (field CallId) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				stringArrayCallIdVal = val
			case kindLlmMessageDigest:
				if stringArrayDigestLastAttr != attrJ+1 {
					stringArrayDigestLastAttr = attrJ + 1
					stringArrayDigestCount++
				}
				val, valErr := stringArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "llmMessageDigest").Str("field", "Digest").Errorf("slot stringArray@llmMessageDigest (field Digest) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				stringArrayDigestVal = val
			case kindLlmMessageToolCallId:
				if stringArrayToolCallIdLastAttr != attrJ+1 {
					stringArrayToolCallIdLastAttr = attrJ + 1
					stringArrayToolCallIdCount++
				}
				val, valErr := stringArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "llmMessageToolCallId").Str("field", "ToolCallId").Errorf("slot stringArray@llmMessageToolCallId (field ToolCallId) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				stringArrayToolCallIdVal = val
			case kindLlmMessageToolCallIds:
				if stringArrayToolCallIdsLastAttr != attrJ+1 {
					stringArrayToolCallIdsLastAttr = attrJ + 1
					stringArrayToolCallIdsCount++
				}
				for v := range stringArrayAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
					stringArrayToolCallIdsSlice = append(stringArrayToolCallIdsSlice, v)
				}
			case kindLlmMessageImages:
				if stringArrayImagesLastAttr != attrJ+1 {
					stringArrayImagesLastAttr = attrJ + 1
					stringArrayImagesCount++
				}
				for v := range stringArrayAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
					stringArrayImagesSlice = append(stringArrayImagesSlice, v)
				}
			}
		}
	}
	if stringArrayCallIdCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "llmMessageCallId").Int("got", stringArrayCallIdCount).Errorf("slot stringArray@llmMessageCallId (field CallId) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", stringArrayCallIdCount)
		return
	}
	if stringArrayCallIdCount == 1 {
		row.CallId = stringArrayCallIdVal
		present = true
	}
	if stringArrayDigestCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "llmMessageDigest").Int("got", stringArrayDigestCount).Errorf("slot stringArray@llmMessageDigest (field Digest) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", stringArrayDigestCount)
		return
	}
	if stringArrayDigestCount == 1 {
		row.Digest = stringArrayDigestVal
		present = true
	}
	if stringArrayToolCallIdCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "llmMessageToolCallId").Int("got", stringArrayToolCallIdCount).Errorf("slot stringArray@llmMessageToolCallId (field ToolCallId) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", stringArrayToolCallIdCount)
		return
	}
	if stringArrayToolCallIdCount == 1 {
		row.ToolCallId.Val = stringArrayToolCallIdVal
		row.ToolCallId.Has = true
		present = true
	}
	if stringArrayToolCallIdsCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "llmMessageToolCallIds").Int("got", stringArrayToolCallIdsCount).Errorf("slot stringArray@llmMessageToolCallIds (field ToolCallIds) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", stringArrayToolCallIdsCount)
		return
	}
	if stringArrayToolCallIdsSlice != nil {
		row.ToolCallIds = stringArrayToolCallIdsSlice
		present = true
	}
	if stringArrayImagesCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "llmMessageImages").Int("got", stringArrayImagesCount).Errorf("slot stringArray@llmMessageImages (field Images) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", stringArrayImagesCount)
		return
	}
	if stringArrayImagesSlice != nil {
		row.Images = stringArrayImagesSlice
		present = true
	}
	// --- u32Array. ---
	var u32ArrayOrdinalVal uint32
	var u32ArrayOrdinalCount int
	var u32ArrayOrdinalLastAttr int64
	nu32Array := u32ArrayAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nu32Array; attrJ++ {
		for membID := range u32ArrayMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindLlmMessageOrdinal:
				if u32ArrayOrdinalLastAttr != attrJ+1 {
					u32ArrayOrdinalLastAttr = attrJ + 1
					u32ArrayOrdinalCount++
				}
				val, valErr := u32ArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "u32Array").Str("membership", "llmMessageOrdinal").Str("field", "Ordinal").Errorf("slot u32Array@llmMessageOrdinal (field Ordinal) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				u32ArrayOrdinalVal = val
			}
		}
	}
	if u32ArrayOrdinalCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "u32Array").Str("membership", "llmMessageOrdinal").Int("got", u32ArrayOrdinalCount).Errorf("slot u32Array@llmMessageOrdinal (field Ordinal) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", u32ArrayOrdinalCount)
		return
	}
	if u32ArrayOrdinalCount == 1 {
		row.Ordinal = u32ArrayOrdinalVal
		present = true
	}
	// --- u64Array. ---
	var u64ArrayBytesVal uint64
	var u64ArrayBytesCount int
	var u64ArrayBytesLastAttr int64
	nu64Array := u64ArrayAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nu64Array; attrJ++ {
		for membID := range u64ArrayMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindLlmMessageBytes:
				if u64ArrayBytesLastAttr != attrJ+1 {
					u64ArrayBytesLastAttr = attrJ + 1
					u64ArrayBytesCount++
				}
				val, valErr := u64ArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "u64Array").Str("membership", "llmMessageBytes").Str("field", "Bytes").Errorf("slot u64Array@llmMessageBytes (field Bytes) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				u64ArrayBytesVal = val
			}
		}
	}
	if u64ArrayBytesCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "u64Array").Str("membership", "llmMessageBytes").Int("got", u64ArrayBytesCount).Errorf("slot u64Array@llmMessageBytes (field Bytes) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", u64ArrayBytesCount)
		return
	}
	if u64ArrayBytesCount == 1 {
		row.Bytes = u64ArrayBytesVal
		present = true
	}
	// --- symbolArray. ---
	var symbolArrayToolNamesSlice []string
	var symbolArrayToolNamesCount int
	var symbolArrayToolNamesLastAttr int64
	nsymbolArray := symbolArrayAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nsymbolArray; attrJ++ {
		for membID := range symbolArrayMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindLlmMessageToolNames:
				if symbolArrayToolNamesLastAttr != attrJ+1 {
					symbolArrayToolNamesLastAttr = attrJ + 1
					symbolArrayToolNamesCount++
				}
				for v := range symbolArrayAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
					symbolArrayToolNamesSlice = append(symbolArrayToolNamesSlice, v)
				}
			}
		}
	}
	if symbolArrayToolNamesCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbolArray").Str("membership", "llmMessageToolNames").Int("got", symbolArrayToolNamesCount).Errorf("slot symbolArray@llmMessageToolNames (field ToolNames) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolArrayToolNamesCount)
		return
	}
	if symbolArrayToolNamesSlice != nil {
		row.ToolNames = symbolArrayToolNamesSlice
		present = true
	}
	return
}
