// Code generated by boxer/public/semistructured/leeway/marshall/go/marshallgen — DO NOT EDIT.

package persiststore

import (
	"iter"

	"github.com/stergiotis/boxer/public/observability/eh/eb"
	dmlruntime "github.com/stergiotis/boxer/public/semistructured/leeway/dml/runtime"
	raruntime "github.com/stergiotis/boxer/public/semistructured/leeway/readaccess/runtime"
)

// --- Caller-assigned membership ids (registry-stable target). ---

const (
	kindRuntimeApp          uint64 = 9223372049739677701
	kindRuntimePersistKey   uint64 = 9223372049739677712
	kindRuntimePersistValue uint64 = 9223372049739677769
)

// stateStateAppIdAttrI is the InAttr-side view of the stateAppId section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type stateStateAppIdAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// stateStateAppIdSecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type stateStateAppIdSecI[Attr any, Ent any] interface {
	BeginAttribute(value string) Attr
	EndSection() Ent
}

// stateStateKeyAttrI is the InAttr-side view of the stateKey section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type stateStateKeyAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// stateStateKeySecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type stateStateKeySecI[Attr any, Ent any] interface {
	BeginAttribute(value string) Attr
	EndSection() Ent
}

// stateStateBlobAttrI is the InAttr-side view of the stateBlob section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type stateStateBlobAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// stateStateBlobSecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type stateStateBlobSecI[Attr any, Ent any] interface {
	BeginAttribute(value []byte) Attr
	EndSection() Ent
}

// stateEntityI is the entity-builder surface stateAddSections drives.
// It always lists the per-section getters; the entity-frame methods
// (BeginEntity / plain setters / CommitEntity) are added only for the
// full codec's BuildEntities. AddSections stacks sections onto a frame
// the caller already owns, so it needs none of them — which lets a
// store drive it with a builder whose frame control is unexported
// (ADR-0100 SD6). Ent is the builder pointer.
type stateEntityI[
	StateAppIdAttr stateStateAppIdAttrI,
	StateAppIdSec stateStateAppIdSecI[StateAppIdAttr, Ent],
	StateKeyAttr stateStateKeyAttrI,
	StateKeySec stateStateKeySecI[StateKeyAttr, Ent],
	StateBlobAttr stateStateBlobAttrI,
	StateBlobSec stateStateBlobSecI[StateBlobAttr, Ent],
	Ent any,
] interface {
	GetSectionStateAppId() StateAppIdSec
	GetSectionStateKey() StateKeySec
	GetSectionStateBlob() StateBlobSec
}

// stateAddSections contributes this kind's tagged sections to the OPEN
// entity on dml — the BuildEntities body without the entity frame.
// The caller owns BeginEntity / plain setters / CommitEntity.
func stateAddSections[
	StateAppIdAttr stateStateAppIdAttrI,
	StateAppIdSec stateStateAppIdSecI[StateAppIdAttr, Ent],
	StateKeyAttr stateStateKeyAttrI,
	StateKeySec stateStateKeySecI[StateKeyAttr, Ent],
	StateBlobAttr stateStateBlobAttrI,
	StateBlobSec stateStateBlobSecI[StateBlobAttr, Ent],
	Ent any,
	DML stateEntityI[
		StateAppIdAttr, StateAppIdSec,
		StateKeyAttr, StateKeySec,
		StateBlobAttr, StateBlobSec,
		Ent,
	],
](dml DML, row State) (err error) {
	// --- stateAppId. ---
	stateAppIdSec := dml.GetSectionStateAppId()
	stateAppIdSecAttr_AppId := stateAppIdSec.BeginAttribute(row.AppId)
	stateAppIdSecAttr_AppId.AddMembershipLowCardRefP(kindRuntimeApp)
	stateAppIdSecAttr_AppId.EndAttributeP()
	stateAppIdSec.EndSection()
	// --- stateKey. ---
	stateKeySec := dml.GetSectionStateKey()
	stateKeySecAttr_Key := stateKeySec.BeginAttribute(row.Key)
	stateKeySecAttr_Key.AddMembershipLowCardRefP(kindRuntimePersistKey)
	stateKeySecAttr_Key.EndAttributeP()
	stateKeySec.EndSection()
	// --- stateBlob. ---
	stateBlobSec := dml.GetSectionStateBlob()
	stateBlobSecAttr_Value := stateBlobSec.BeginAttribute(row.Value)
	stateBlobSecAttr_Value.AddMembershipLowCardRefP(kindRuntimePersistValue)
	stateBlobSecAttr_Value.EndAttributeP()
	stateBlobSec.EndSection()
	return
}

// stateStateAppIdAttrsReadI is the Attributes-side view of the stateAppId section.
type stateStateAppIdAttrsReadI interface {
	GetAttrValueValue(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) string
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// stateStateAppIdMembsReadI is the Memberships-side view of the stateAppId section.
type stateStateAppIdMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// stateStateKeyAttrsReadI is the Attributes-side view of the stateKey section.
type stateStateKeyAttrsReadI interface {
	GetAttrValueValue(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) string
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// stateStateKeyMembsReadI is the Memberships-side view of the stateKey section.
type stateStateKeyMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// stateStateBlobAttrsReadI is the Attributes-side view of the stateBlob section.
type stateStateBlobAttrsReadI interface {
	GetAttrValueValue(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) []byte
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// stateStateBlobMembsReadI is the Memberships-side view of the stateBlob section.
type stateStateBlobMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// stateReadRow reads row i as one optional State component: presence-
// gated (a row carrying none of the kind's memberships yields
// present=false), membership-matched. A slot carrying more
// attributes than this kind's shape admits is an error, for every
// shape including containers. Plain-
// bound fields stay zero — the caller owns the envelope. The
// Attrs/Membs readers bind by type inference at the call site, as
// with FillFromArrow.
func stateReadRow[
	StateAppIdAttrs stateStateAppIdAttrsReadI,
	StateAppIdMembs stateStateAppIdMembsReadI,
	StateKeyAttrs stateStateKeyAttrsReadI,
	StateKeyMembs stateStateKeyMembsReadI,
	StateBlobAttrs stateStateBlobAttrsReadI,
	StateBlobMembs stateStateBlobMembsReadI,
](
	i int,
	stateAppIdAttrs StateAppIdAttrs,
	stateAppIdMembs StateAppIdMembs,
	stateKeyAttrs StateKeyAttrs,
	stateKeyMembs StateKeyMembs,
	stateBlobAttrs StateBlobAttrs,
	stateBlobMembs StateBlobMembs,
) (row State, present bool, err error) {
	// --- stateAppId. ---
	var stateAppIdAppIdVal string
	var stateAppIdAppIdCount int
	var stateAppIdAppIdLastAttr int64
	nstateAppId := stateAppIdAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nstateAppId; attrJ++ {
		for membID := range stateAppIdMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindRuntimeApp:
				if stateAppIdAppIdLastAttr != attrJ+1 {
					stateAppIdAppIdLastAttr = attrJ + 1
					stateAppIdAppIdCount++
				}
				val := stateAppIdAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				stateAppIdAppIdVal = val
			}
		}
	}
	if stateAppIdAppIdCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "stateAppId").Str("membership", "runtimeApp").Int("got", stateAppIdAppIdCount).Errorf("slot stateAppId@runtimeApp (field AppId) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", stateAppIdAppIdCount)
		return
	}
	if stateAppIdAppIdCount == 1 {
		row.AppId = stateAppIdAppIdVal
		present = true
	}
	// --- stateKey. ---
	var stateKeyKeyVal string
	var stateKeyKeyCount int
	var stateKeyKeyLastAttr int64
	nstateKey := stateKeyAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nstateKey; attrJ++ {
		for membID := range stateKeyMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindRuntimePersistKey:
				if stateKeyKeyLastAttr != attrJ+1 {
					stateKeyKeyLastAttr = attrJ + 1
					stateKeyKeyCount++
				}
				val := stateKeyAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				stateKeyKeyVal = val
			}
		}
	}
	if stateKeyKeyCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "stateKey").Str("membership", "runtimePersistKey").Int("got", stateKeyKeyCount).Errorf("slot stateKey@runtimePersistKey (field Key) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", stateKeyKeyCount)
		return
	}
	if stateKeyKeyCount == 1 {
		row.Key = stateKeyKeyVal
		present = true
	}
	// --- stateBlob. ---
	var stateBlobValueVal []byte
	var stateBlobValueCount int
	var stateBlobValueLastAttr int64
	nstateBlob := stateBlobAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nstateBlob; attrJ++ {
		for membID := range stateBlobMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindRuntimePersistValue:
				if stateBlobValueLastAttr != attrJ+1 {
					stateBlobValueLastAttr = attrJ + 1
					stateBlobValueCount++
				}
				val := stateBlobAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				cp := make([]byte, len(val))
				copy(cp, val)
				stateBlobValueVal = cp
			}
		}
	}
	if stateBlobValueCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "stateBlob").Str("membership", "runtimePersistValue").Int("got", stateBlobValueCount).Errorf("slot stateBlob@runtimePersistValue (field Value) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", stateBlobValueCount)
		return
	}
	if stateBlobValueCount == 1 {
		row.Value = stateBlobValueVal
		present = true
	}
	return
}
