// Code generated by Leeway DML (github.com/stergiotis/boxer/public/semistructured/leeway/anchor/ecsdemo/stage2.test); DO NOT EDIT.

package stage2

import (
	"errors"
	"github.com/apache/arrow-go/v18/arrow"
	array "github.com/apache/arrow-go/v18/arrow/array"
	_ "github.com/apache/arrow-go/v18/arrow/ipc"
	_ "github.com/apache/arrow-go/v18/arrow/math"
	"github.com/apache/arrow-go/v18/arrow/memory"
	"github.com/stergiotis/boxer/public/observability/eh"
	"github.com/stergiotis/boxer/public/observability/eh/eb"
	"github.com/stergiotis/boxer/public/semistructured/leeway/dml/runtime"
	"slices"
	"time"
)

///////////////////////////////////////////////////////////////////
// code generator
// gocodegen.GenerateArrowSchemaFactory
// ./public/semistructured/leeway/gocodegen/gocodegen_common.go:26

func CreateSchemaDroneTable() (schema *arrow.Schema) {
	schema = arrow.NewSchema([]arrow.Field{
		/* 000 */ arrow.Field{Name: "id:id:u64:2k:0:0:", Nullable: false, Type: arrow.PrimitiveTypes.Uint64},
		/* 001 */ arrow.Field{Name: "tv:symbol:value:val:s:m:0:24:0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.StringType{})},
		/* 002 */ arrow.Field{Name: "tv:symbol:hr:hr:u64:2k:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 003 */ arrow.Field{Name: "tv:symbol:lr:lr:u64:2q:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 004 */ arrow.Field{Name: "tv:symbol:lv:lv:y:m:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.BinaryType{})},
		/* 005 */ arrow.Field{Name: "tv:symbol:lmr:lmr:u64:2q:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 006 */ arrow.Field{Name: "tv:symbol:mrhp:mrhp:y:g:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.BinaryType{})},
		/* 007 */ arrow.Field{Name: "tv:symbol:hrcard:hrcard:u64:4gw:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 008 */ arrow.Field{Name: "tv:symbol:lrcard:lrcard:u64:4gw:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 009 */ arrow.Field{Name: "tv:symbol:lvcard:lvcard:u64:4gw:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 010 */ arrow.Field{Name: "tv:symbol:lmrcard:lmrcard:u64:4gw:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 011 */ arrow.Field{Name: "tv:u64Array:value:val:u64h:g:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 012 */ arrow.Field{Name: "tv:u64Array:hr:hr:u64:2k:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 013 */ arrow.Field{Name: "tv:u64Array:lr:lr:u64:2q:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 014 */ arrow.Field{Name: "tv:u64Array:lv:lv:y:m:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.BinaryType{})},
		/* 015 */ arrow.Field{Name: "tv:u64Array:lmr:lmr:u64:2q:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 016 */ arrow.Field{Name: "tv:u64Array:mrhp:mrhp:y:g:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.BinaryType{})},
		/* 017 */ arrow.Field{Name: "tv:u64Array:len:len:u64:28o:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 018 */ arrow.Field{Name: "tv:u64Array:hrcard:hrcard:u64:4gw:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 019 */ arrow.Field{Name: "tv:u64Array:lrcard:lrcard:u64:4gw:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 020 */ arrow.Field{Name: "tv:u64Array:lvcard:lvcard:u64:4gw:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 021 */ arrow.Field{Name: "tv:u64Array:lmrcard:lmrcard:u64:4gw:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 022 */ arrow.Field{Name: "tv:symbolArray:value:val:sh:g:0:24:0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.StringType{})},
		/* 023 */ arrow.Field{Name: "tv:symbolArray:hr:hr:u64:2k:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 024 */ arrow.Field{Name: "tv:symbolArray:lr:lr:u64:2q:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 025 */ arrow.Field{Name: "tv:symbolArray:lv:lv:y:m:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.BinaryType{})},
		/* 026 */ arrow.Field{Name: "tv:symbolArray:lmr:lmr:u64:2q:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 027 */ arrow.Field{Name: "tv:symbolArray:mrhp:mrhp:y:g:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.BinaryType{})},
		/* 028 */ arrow.Field{Name: "tv:symbolArray:len:len:u64:28o:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 029 */ arrow.Field{Name: "tv:symbolArray:hrcard:hrcard:u64:4gw:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 030 */ arrow.Field{Name: "tv:symbolArray:lrcard:lrcard:u64:4gw:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 031 */ arrow.Field{Name: "tv:symbolArray:lvcard:lvcard:u64:4gw:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 032 */ arrow.Field{Name: "tv:symbolArray:lmrcard:lmrcard:u64:4gw:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 033 */ arrow.Field{Name: "tv:geoPoint:pointLat:val:f32:g:0:0:0::geo", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Float32)},
		/* 034 */ arrow.Field{Name: "tv:geoPoint:pointLng:val:f32:g:0:0:0::geo", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Float32)},
		/* 035 */ arrow.Field{Name: "tv:geoPoint:h3:val:u64:g:0:0:0::geo", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 036 */ arrow.Field{Name: "tv:geoPoint:hr:hr:u64:2k:0:0:0::geo", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 037 */ arrow.Field{Name: "tv:geoPoint:lr:lr:u64:2q:0:0:0::geo", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 038 */ arrow.Field{Name: "tv:geoPoint:lv:lv:y:m:0:0:0::geo", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.BinaryType{})},
		/* 039 */ arrow.Field{Name: "tv:geoPoint:lmr:lmr:u64:2q:0:0:0::geo", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 040 */ arrow.Field{Name: "tv:geoPoint:mrhp:mrhp:y:g:0:0:0::geo", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.BinaryType{})},
		/* 041 */ arrow.Field{Name: "tv:geoPoint:hrcard:hrcard:u64:4gw:0:0:0::geo", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 042 */ arrow.Field{Name: "tv:geoPoint:lrcard:lrcard:u64:4gw:0:0:0::geo", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 043 */ arrow.Field{Name: "tv:geoPoint:lvcard:lvcard:u64:4gw:0:0:0::geo", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 044 */ arrow.Field{Name: "tv:geoPoint:lmrcard:lmrcard:u64:4gw:0:0:0::geo", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 045 */ arrow.Field{Name: "tv:timeRange:beginIncl:val:z64:2k:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.TimestampType{Unit: arrow.Nanosecond})},
		/* 046 */ arrow.Field{Name: "tv:timeRange:endExcl:val:z64:2k:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.TimestampType{Unit: arrow.Nanosecond})},
		/* 047 */ arrow.Field{Name: "tv:timeRange:hr:hr:u64:2k:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 048 */ arrow.Field{Name: "tv:timeRange:lr:lr:u64:2q:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 049 */ arrow.Field{Name: "tv:timeRange:lv:lv:y:m:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.BinaryType{})},
		/* 050 */ arrow.Field{Name: "tv:timeRange:lmr:lmr:u64:2q:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 051 */ arrow.Field{Name: "tv:timeRange:mrhp:mrhp:y:g:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.BinaryType{})},
		/* 052 */ arrow.Field{Name: "tv:timeRange:hrcard:hrcard:u64:4gw:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 053 */ arrow.Field{Name: "tv:timeRange:lrcard:lrcard:u64:4gw:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 054 */ arrow.Field{Name: "tv:timeRange:lvcard:lvcard:u64:4gw:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 055 */ arrow.Field{Name: "tv:timeRange:lmrcard:lmrcard:u64:4gw:0:0:0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
	}, nil)
	return
}

///////////////////////////////////////////////////////////////////
// code generator
// dml.(*GoClassBuilder).ComposeEntityClassAndFactoryCode
// ./public/semistructured/leeway/dml/lw_dml_generator.go:1266

type InEntityDroneTable struct {
	errs                  []error
	state                 runtime.EntityStateE
	allocator             memory.Allocator
	builder               *array.RecordBuilder
	records               []arrow.RecordBatch
	section00Inst         *InEntityDroneTableSectionGeoPoint
	section00State        runtime.EntityStateE
	section01Inst         *InEntityDroneTableSectionSymbol
	section01State        runtime.EntityStateE
	section02Inst         *InEntityDroneTableSectionSymbolArray
	section02State        runtime.EntityStateE
	section03Inst         *InEntityDroneTableSectionTimeRange
	section03State        runtime.EntityStateE
	section04Inst         *InEntityDroneTableSectionU64Array
	section04State        runtime.EntityStateE
	activeSections        *[5]bool
	plainId0              uint64
	scalarFieldBuilder000 *array.Uint64Builder
}

func NewInEntityDroneTable(allocator memory.Allocator, estimatedNumberOfRecords int) (inst *InEntityDroneTable) {
	inst = &InEntityDroneTable{}
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.allocator = allocator
	inst.records = make([]arrow.RecordBatch, 0, estimatedNumberOfRecords)
	schema := CreateSchemaDroneTable()
	builder := array.NewRecordBuilder(allocator, schema)
	inst.builder = builder
	inst.initSections(builder)
	inst.scalarFieldBuilder000 = builder.Field(0).(*array.Uint64Builder)

	return inst
}

// SetActiveSections marks which section indices BeginEntity should
// initialise (skipping beginSection for the rest). Pass nil to clear.
// The hint is a performance optimisation; sending BeginAttribute to
// an unmarked section produces empty-list bytes at TransferRecords.
func (inst *InEntityDroneTable) SetActiveSections(idxs []int) {
	if idxs == nil {
		inst.activeSections = nil
		return
	}
	var mask [5]bool
	for _, i := range idxs {
		if i >= 0 && i < len(mask) {
			mask[i] = true
		}
	}
	inst.activeSections = &mask
}

// Builder exposes the underlying RecordBuilder so callers can apply
// shim-level hints (e.g. SetActiveFields on the arrowrowbinary /
// arrowsparserb / arrowrowcbor backends).
func (inst *InEntityDroneTable) Builder() *array.RecordBuilder { return inst.builder }

// InEntityDroneTableSectionIndices maps each section name to its section%02dInst slot in
// the generated entity. Useful for callers that need to compute
// SetActiveSections inputs from section names — for example, the
// marshallgen-driven keelson codec wrappers.
var InEntityDroneTableSectionIndices = map[string]int{
	"geoPoint":    0,
	"symbol":      1,
	"symbolArray": 2,
	"timeRange":   3,
	"u64Array":    4,
}

///////////////////////////////////////////////////////////////////
// code generator
// dml.(*GoClassBuilder).ComposeEntityCode
// ./public/semistructured/leeway/dml/lw_dml_generator.go:1443

func (inst *InEntityDroneTable) SetId(id0 uint64) *InEntityDroneTable {
	if inst.state != runtime.EntityStateInEntity {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.plainId0 = id0

	return inst
}
func (inst *InEntityDroneTable) appendPlainValues() {
	inst.scalarFieldBuilder000.Append(inst.plainId0)
}
func (inst *InEntityDroneTable) resetPlainValues() {
	inst.plainId0 = uint64(0)
}
func (inst *InEntityDroneTable) initSections(builder *array.RecordBuilder) {
	inst.section00Inst = NewInEntityDroneTableSectionGeoPoint(builder, inst)
	inst.section01Inst = NewInEntityDroneTableSectionSymbol(builder, inst)
	inst.section02Inst = NewInEntityDroneTableSectionSymbolArray(builder, inst)
	inst.section03Inst = NewInEntityDroneTableSectionTimeRange(builder, inst)
	inst.section04Inst = NewInEntityDroneTableSectionU64Array(builder, inst)
}
func (inst *InEntityDroneTable) beginSections() {
	if mask := inst.activeSections; mask != nil {
		if mask[0] {
			inst.section00Inst.beginSection()
		}
		if mask[1] {
			inst.section01Inst.beginSection()
		}
		if mask[2] {
			inst.section02Inst.beginSection()
		}
		if mask[3] {
			inst.section03Inst.beginSection()
		}
		if mask[4] {
			inst.section04Inst.beginSection()
		}
		return
	}
	inst.section00Inst.beginSection()
	inst.section01Inst.beginSection()
	inst.section02Inst.beginSection()
	inst.section03Inst.beginSection()
	inst.section04Inst.beginSection()
}
func (inst *InEntityDroneTable) resetSections() {
	inst.section00Inst.resetSection()
	inst.section01Inst.resetSection()
	inst.section02Inst.resetSection()
	inst.section03Inst.resetSection()
	inst.section04Inst.resetSection()
}
func (inst *InEntityDroneTable) CheckErrors() (err error) {
	err = eh.CheckErrors(inst.errs)
	err = errors.Join(err, inst.section00Inst.CheckErrors())
	err = errors.Join(err, inst.section01Inst.CheckErrors())
	err = errors.Join(err, inst.section02Inst.CheckErrors())
	err = errors.Join(err, inst.section03Inst.CheckErrors())
	err = errors.Join(err, inst.section04Inst.CheckErrors())

	return
}
func (inst *InEntityDroneTable) GetSectionGeoPoint() *InEntityDroneTableSectionGeoPoint {
	return inst.section00Inst
}
func (inst *InEntityDroneTable) GetSectionSymbol() *InEntityDroneTableSectionSymbol {
	return inst.section01Inst
}
func (inst *InEntityDroneTable) GetSectionSymbolArray() *InEntityDroneTableSectionSymbolArray {
	return inst.section02Inst
}
func (inst *InEntityDroneTable) GetSectionTimeRange() *InEntityDroneTableSectionTimeRange {
	return inst.section03Inst
}
func (inst *InEntityDroneTable) GetSectionU64Array() *InEntityDroneTableSectionU64Array {
	return inst.section04Inst
}
func (inst *InEntityDroneTable) BeginEntity() *InEntityDroneTable {
	switch inst.state {
	case runtime.EntityStateInitial:
		inst.state = runtime.EntityStateInEntity
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}

	inst.beginSections()
	return inst
}
func (inst *InEntityDroneTable) validateEntity() {
	{
		state := inst.section00Inst.state
		switch state {
		case runtime.EntityStateInAttribute:
			inst.AppendError(eb.Build().Str("section", "geoPoint").Stringer("state", state).Errorf("wrong state: Check that .BeginAttribute() is followed by .EndAttribute()"))
			break
		}
	}
	{
		state := inst.section01Inst.state
		switch state {
		case runtime.EntityStateInAttribute:
			inst.AppendError(eb.Build().Str("section", "symbol").Stringer("state", state).Errorf("wrong state: Check that .BeginAttribute() is followed by .EndAttribute()"))
			break
		}
	}
	{
		state := inst.section02Inst.state
		switch state {
		case runtime.EntityStateInAttribute:
			inst.AppendError(eb.Build().Str("section", "symbolArray").Stringer("state", state).Errorf("wrong state: Check that .BeginAttribute() is followed by .EndAttribute()"))
			break
		}
	}
	{
		state := inst.section03Inst.state
		switch state {
		case runtime.EntityStateInAttribute:
			inst.AppendError(eb.Build().Str("section", "timeRange").Stringer("state", state).Errorf("wrong state: Check that .BeginAttribute() is followed by .EndAttribute()"))
			break
		}
	}
	{
		state := inst.section04Inst.state
		switch state {
		case runtime.EntityStateInAttribute:
			inst.AppendError(eb.Build().Str("section", "u64Array").Stringer("state", state).Errorf("wrong state: Check that .BeginAttribute() is followed by .EndAttribute()"))
			break
		}
	}

	return
}
func (inst *InEntityDroneTable) CommitEntity() (err error) {
	inst.validateEntity()
	err = inst.CheckErrors()
	if err != nil {
		err = eh.Errorf("unable to commit entity, found errors: %w", err)
		return
	}
	switch inst.state {
	case runtime.EntityStateInEntity:
		inst.state = runtime.EntityStateInitial
		break
	default:
		err = runtime.ErrInvalidStateTransition
		return
	}

	inst.appendPlainValues()
	inst.resetPlainValues()
	inst.resetSections()
	return
}
func (inst *InEntityDroneTable) RollbackEntity() (err error) {
	switch inst.state {
	case runtime.EntityStateInEntity:
		inst.state = runtime.EntityStateInitial
		break
	default:
		err = runtime.ErrInvalidStateTransition
		return
	}

	inst.clearErrors()       // rollback is the recovery mechanism: discard the entity's errors
	inst.appendPlainValues() // arrow fields must all have one row
	inst.resetPlainValues()
	inst.resetSections()
	rec := inst.builder.NewRecord()
	if rec.NumRows() > 1 {
		inst.records = append(inst.records, rec.NewSlice(0, rec.NumRows()-1))
	} else {
		// FIXME find better way to truncate builder
		inst.builder.NewRecord().Release()
	}
	rec.Release()
	return
}

// TransferRecords The returned Records must be Release()'d after use.
func (inst *InEntityDroneTable) TransferRecords(recordsIn []arrow.RecordBatch) (recordsOut []arrow.RecordBatch, err error) {
	if inst.state != runtime.EntityStateInitial {
		err = runtime.ErrInvalidStateTransition
		return
	}

	recordsOut = append(recordsIn, inst.records...)
	clear(inst.records)
	inst.records = inst.records[:0]
	rec := inst.builder.NewRecord()
	if rec.NumRows() > 0 {
		recordsOut = append(recordsOut, rec)
	}
	return
}

func (inst *InEntityDroneTable) GetSchema() (schema *arrow.Schema) {
	return inst.builder.Schema()
}

func (inst *InEntityDroneTable) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityDroneTable) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}

type InEntityDroneTableSectionGeoPoint struct {
	errs                  []error
	inAttr                *InEntityDroneTableSectionGeoPointInAttr
	state                 runtime.EntityStateE
	attributeCount        int
	parent                *InEntityDroneTable
	scalarFieldBuilder033 *array.Float32Builder
	scalarListBuilder033  *array.ListBuilder
	scalarFieldBuilder034 *array.Float32Builder
	scalarListBuilder034  *array.ListBuilder
	scalarFieldBuilder035 *array.Uint64Builder
	scalarListBuilder035  *array.ListBuilder
}

func NewInEntityDroneTableSectionGeoPoint(builder *array.RecordBuilder, parent *InEntityDroneTable) (inst *InEntityDroneTableSectionGeoPoint) {
	inst = &InEntityDroneTableSectionGeoPoint{}
	inAttr := NewInEntityDroneTableSectionGeoPointInAttr(builder, inst)
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.inAttr = inAttr
	inst.parent = parent
	inst.scalarFieldBuilder033 = builder.Field(33).(*array.ListBuilder).ValueBuilder().(*array.Float32Builder)
	inst.scalarListBuilder033 = builder.Field(33).(*array.ListBuilder)
	inst.scalarFieldBuilder034 = builder.Field(34).(*array.ListBuilder).ValueBuilder().(*array.Float32Builder)
	inst.scalarListBuilder034 = builder.Field(34).(*array.ListBuilder)
	inst.scalarFieldBuilder035 = builder.Field(35).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.scalarListBuilder035 = builder.Field(35).(*array.ListBuilder)

	return inst
}
func (inst *InEntityDroneTableSectionGeoPoint) endAttribute() {
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInSection
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
}
func (inst *InEntityDroneTableSectionGeoPoint) BeginAttribute(pointLat33 float32, pointLng34 float32, h335 uint64) *InEntityDroneTableSectionGeoPointInAttr {
	switch inst.state {
	case runtime.EntityStateInSection:
		inst.state = runtime.EntityStateInAttribute
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.inAttr
	}
	inst.scalarFieldBuilder033.Append(pointLat33)
	inst.scalarFieldBuilder034.Append(pointLng34)
	inst.scalarFieldBuilder035.Append(h335)
	inst.attributeCount++

	inst.inAttr.state = inst.state
	return inst.inAttr
}
func (inst *InEntityDroneTableSectionGeoPoint) CheckErrors() (err error) {
	err = eh.CheckErrors(slices.Concat(inst.errs, inst.inAttr.errs))
	return
}
func (inst *InEntityDroneTableSectionGeoPoint) EndSection() *InEntityDroneTable {
	switch inst.state {
	case runtime.EntityStateInSection:
		inst.state = runtime.EntityStateInitial
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent
	}

	return inst.parent
}

func (inst *InEntityDroneTableSectionGeoPoint) beginSection() {
	inst.state = runtime.EntityStateInSection
	inst.attributeCount = 0
	inst.inAttr.beginAttribute()
}

func (inst *InEntityDroneTableSectionGeoPoint) resetSection() {
	inst.clearErrors()
	inst.inAttr.clearErrors()
	inst.attributeCount = 0
	inst.state = runtime.EntityStateInitial
}

func (inst *InEntityDroneTableSectionGeoPoint) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityDroneTableSectionGeoPoint) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}

type InEntityDroneTableSectionGeoPointInAttr struct {
	errs                             []error
	state                            runtime.EntityStateE
	parent                           *InEntityDroneTableSectionGeoPoint
	scalarFieldBuilder033            *array.Float32Builder
	scalarListBuilder033             *array.ListBuilder
	scalarFieldBuilder034            *array.Float32Builder
	scalarListBuilder034             *array.ListBuilder
	scalarFieldBuilder035            *array.Uint64Builder
	scalarListBuilder035             *array.ListBuilder
	membershipFieldBuilder036        *array.Uint64Builder
	membershipListBuilder036         *array.ListBuilder
	membershipFieldBuilder037        *array.Uint64Builder
	membershipListBuilder037         *array.ListBuilder
	membershipFieldBuilder038        *array.BinaryBuilder
	membershipListBuilder038         *array.ListBuilder
	membershipFieldBuilder039        *array.Uint64Builder
	membershipListBuilder039         *array.ListBuilder
	membershipFieldBuilder040        *array.BinaryBuilder
	membershipListBuilder040         *array.ListBuilder
	membershipSupportFieldBuilder041 *array.Uint64Builder
	membershipSupportListBuilder041  *array.ListBuilder
	membershipSupportFieldBuilder042 *array.Uint64Builder
	membershipSupportListBuilder042  *array.ListBuilder
	membershipSupportFieldBuilder043 *array.Uint64Builder
	membershipSupportListBuilder043  *array.ListBuilder
	membershipSupportFieldBuilder044 *array.Uint64Builder
	membershipSupportListBuilder044  *array.ListBuilder

	membershipContainerLength036 int

	membershipContainerLength037 int

	membershipContainerLength038 int

	membershipContainerLength039 int

	membershipContainerLength040 int
}

func NewInEntityDroneTableSectionGeoPointInAttr(builder *array.RecordBuilder, parent *InEntityDroneTableSectionGeoPoint) (inst *InEntityDroneTableSectionGeoPointInAttr) {
	inst = &InEntityDroneTableSectionGeoPointInAttr{}
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.parent = parent
	inst.scalarFieldBuilder033 = builder.Field(33).(*array.ListBuilder).ValueBuilder().(*array.Float32Builder)
	inst.scalarListBuilder033 = builder.Field(33).(*array.ListBuilder)
	inst.scalarFieldBuilder034 = builder.Field(34).(*array.ListBuilder).ValueBuilder().(*array.Float32Builder)
	inst.scalarListBuilder034 = builder.Field(34).(*array.ListBuilder)
	inst.scalarFieldBuilder035 = builder.Field(35).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.scalarListBuilder035 = builder.Field(35).(*array.ListBuilder)
	inst.membershipFieldBuilder036 = builder.Field(36).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder036 = builder.Field(36).(*array.ListBuilder)
	inst.membershipFieldBuilder037 = builder.Field(37).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder037 = builder.Field(37).(*array.ListBuilder)
	inst.membershipFieldBuilder038 = builder.Field(38).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.membershipListBuilder038 = builder.Field(38).(*array.ListBuilder)
	inst.membershipFieldBuilder039 = builder.Field(39).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder039 = builder.Field(39).(*array.ListBuilder)
	inst.membershipFieldBuilder040 = builder.Field(40).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.membershipListBuilder040 = builder.Field(40).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder041 = builder.Field(41).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder041 = builder.Field(41).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder042 = builder.Field(42).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder042 = builder.Field(42).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder043 = builder.Field(43).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder043 = builder.Field(43).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder044 = builder.Field(44).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder044 = builder.Field(44).(*array.ListBuilder)

	return inst
}
func (inst *InEntityDroneTableSectionGeoPointInAttr) beginAttribute() {
	inst.membershipListBuilder036.Append(true)
	inst.membershipListBuilder037.Append(true)
	inst.membershipListBuilder038.Append(true)
	inst.membershipListBuilder039.Append(true)
	inst.membershipListBuilder040.Append(true)
	inst.membershipContainerLength036 = 0
	inst.membershipContainerLength037 = 0
	inst.membershipContainerLength038 = 0
	inst.membershipContainerLength039 = 0
	inst.membershipContainerLength040 = 0
	inst.scalarListBuilder033.Append(true)
	inst.scalarListBuilder034.Append(true)
	inst.scalarListBuilder035.Append(true)
	inst.membershipSupportListBuilder041.Append(true)
	inst.membershipSupportListBuilder042.Append(true)
	inst.membershipSupportListBuilder043.Append(true)
	inst.membershipSupportListBuilder044.Append(true)
	inst.state = runtime.EntityStateInSection
	inst.clearErrors()
}
func (inst *InEntityDroneTableSectionGeoPointInAttr) AddMembershipHighCardRef(hr36 uint64) *InEntityDroneTableSectionGeoPointInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder036.Append(hr36)
	inst.membershipContainerLength036++
	return inst
}
func (inst *InEntityDroneTableSectionGeoPointInAttr) AddMembershipHighCardRefP(hr36 uint64) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder036.Append(hr36)
	inst.membershipContainerLength036++
	return
}
func (inst *InEntityDroneTableSectionGeoPointInAttr) AddMembershipLowCardRef(lr37 uint64) *InEntityDroneTableSectionGeoPointInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder037.Append(lr37)
	inst.membershipContainerLength037++
	return inst
}
func (inst *InEntityDroneTableSectionGeoPointInAttr) AddMembershipLowCardRefP(lr37 uint64) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder037.Append(lr37)
	inst.membershipContainerLength037++
	return
}
func (inst *InEntityDroneTableSectionGeoPointInAttr) AddMembershipLowCardVerbatim(lv38 []byte) *InEntityDroneTableSectionGeoPointInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder038.Append(lv38)
	inst.membershipContainerLength038++
	return inst
}
func (inst *InEntityDroneTableSectionGeoPointInAttr) AddMembershipLowCardVerbatimP(lv38 []byte) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder038.Append(lv38)
	inst.membershipContainerLength038++
	return
}
func (inst *InEntityDroneTableSectionGeoPointInAttr) AddMembershipMixedLowCardRef(lmr39 uint64, mrhp40 []byte) *InEntityDroneTableSectionGeoPointInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder039.Append(lmr39)
	inst.membershipFieldBuilder040.Append(mrhp40)
	inst.membershipContainerLength039++
	inst.membershipContainerLength040++
	return inst
}
func (inst *InEntityDroneTableSectionGeoPointInAttr) AddMembershipMixedLowCardRefP(lmr39 uint64, mrhp40 []byte) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder039.Append(lmr39)
	inst.membershipFieldBuilder040.Append(mrhp40)
	inst.membershipContainerLength039++
	inst.membershipContainerLength040++
	return
}
func (inst *InEntityDroneTableSectionGeoPointInAttr) handleMembershipSupportColumns() {
	var l int
	var _ = l
	l = inst.membershipContainerLength036
	inst.membershipContainerLength036 = 0
	inst.membershipSupportFieldBuilder041.Append(uint64(l))
	l = inst.membershipContainerLength037
	inst.membershipContainerLength037 = 0
	inst.membershipSupportFieldBuilder042.Append(uint64(l))
	l = inst.membershipContainerLength038
	inst.membershipContainerLength038 = 0
	inst.membershipSupportFieldBuilder043.Append(uint64(l))
	l = inst.membershipContainerLength039
	inst.membershipContainerLength039 = 0
	inst.membershipSupportFieldBuilder044.Append(uint64(l))
}
func (inst *InEntityDroneTableSectionGeoPointInAttr) handleNonScalarSupportColumns() {
	var l int
	var _ = l
}
func (inst *InEntityDroneTableSectionGeoPointInAttr) completeAttribute() {
	inst.handleMembershipSupportColumns()
	inst.handleNonScalarSupportColumns()
}
func (inst *InEntityDroneTableSectionGeoPointInAttr) EndSection() *InEntityDroneTable {
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInitial
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent.parent
	}

	inst.completeAttribute()
	inst.parent.EndSection()
	return inst.parent.parent
}
func (inst *InEntityDroneTableSectionGeoPointInAttr) EndAttribute() *InEntityDroneTableSectionGeoPoint {
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInSection
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent
	}

	inst.completeAttribute()
	inst.parent.endAttribute()
	return inst.parent
}
func (inst *InEntityDroneTableSectionGeoPointInAttr) EndAttributeP() {
	inst.EndAttribute()
}

func (inst *InEntityDroneTableSectionGeoPointInAttr) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityDroneTableSectionGeoPointInAttr) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}

type InEntityDroneTableSectionSymbol struct {
	errs                  []error
	inAttr                *InEntityDroneTableSectionSymbolInAttr
	state                 runtime.EntityStateE
	attributeCount        int
	parent                *InEntityDroneTable
	scalarFieldBuilder001 *array.StringBuilder
	scalarListBuilder001  *array.ListBuilder
}

func NewInEntityDroneTableSectionSymbol(builder *array.RecordBuilder, parent *InEntityDroneTable) (inst *InEntityDroneTableSectionSymbol) {
	inst = &InEntityDroneTableSectionSymbol{}
	inAttr := NewInEntityDroneTableSectionSymbolInAttr(builder, inst)
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.inAttr = inAttr
	inst.parent = parent
	inst.scalarFieldBuilder001 = builder.Field(1).(*array.ListBuilder).ValueBuilder().(*array.StringBuilder)
	inst.scalarListBuilder001 = builder.Field(1).(*array.ListBuilder)

	return inst
}
func (inst *InEntityDroneTableSectionSymbol) endAttribute() {
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInSection
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
}
func (inst *InEntityDroneTableSectionSymbol) BeginAttribute(value1 string) *InEntityDroneTableSectionSymbolInAttr {
	switch inst.state {
	case runtime.EntityStateInSection:
		inst.state = runtime.EntityStateInAttribute
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.inAttr
	}
	inst.scalarFieldBuilder001.Append(value1)
	inst.attributeCount++

	inst.inAttr.state = inst.state
	return inst.inAttr
}
func (inst *InEntityDroneTableSectionSymbol) CheckErrors() (err error) {
	err = eh.CheckErrors(slices.Concat(inst.errs, inst.inAttr.errs))
	return
}
func (inst *InEntityDroneTableSectionSymbol) EndSection() *InEntityDroneTable {
	switch inst.state {
	case runtime.EntityStateInSection:
		inst.state = runtime.EntityStateInitial
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent
	}

	return inst.parent
}

func (inst *InEntityDroneTableSectionSymbol) beginSection() {
	inst.state = runtime.EntityStateInSection
	inst.attributeCount = 0
	inst.inAttr.beginAttribute()
}

func (inst *InEntityDroneTableSectionSymbol) resetSection() {
	inst.clearErrors()
	inst.inAttr.clearErrors()
	inst.attributeCount = 0
	inst.state = runtime.EntityStateInitial
}

func (inst *InEntityDroneTableSectionSymbol) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityDroneTableSectionSymbol) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}

type InEntityDroneTableSectionSymbolInAttr struct {
	errs                             []error
	state                            runtime.EntityStateE
	parent                           *InEntityDroneTableSectionSymbol
	scalarFieldBuilder001            *array.StringBuilder
	scalarListBuilder001             *array.ListBuilder
	membershipFieldBuilder002        *array.Uint64Builder
	membershipListBuilder002         *array.ListBuilder
	membershipFieldBuilder003        *array.Uint64Builder
	membershipListBuilder003         *array.ListBuilder
	membershipFieldBuilder004        *array.BinaryBuilder
	membershipListBuilder004         *array.ListBuilder
	membershipFieldBuilder005        *array.Uint64Builder
	membershipListBuilder005         *array.ListBuilder
	membershipFieldBuilder006        *array.BinaryBuilder
	membershipListBuilder006         *array.ListBuilder
	membershipSupportFieldBuilder007 *array.Uint64Builder
	membershipSupportListBuilder007  *array.ListBuilder
	membershipSupportFieldBuilder008 *array.Uint64Builder
	membershipSupportListBuilder008  *array.ListBuilder
	membershipSupportFieldBuilder009 *array.Uint64Builder
	membershipSupportListBuilder009  *array.ListBuilder
	membershipSupportFieldBuilder010 *array.Uint64Builder
	membershipSupportListBuilder010  *array.ListBuilder

	membershipContainerLength002 int

	membershipContainerLength003 int

	membershipContainerLength004 int

	membershipContainerLength005 int

	membershipContainerLength006 int
}

func NewInEntityDroneTableSectionSymbolInAttr(builder *array.RecordBuilder, parent *InEntityDroneTableSectionSymbol) (inst *InEntityDroneTableSectionSymbolInAttr) {
	inst = &InEntityDroneTableSectionSymbolInAttr{}
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.parent = parent
	inst.scalarFieldBuilder001 = builder.Field(1).(*array.ListBuilder).ValueBuilder().(*array.StringBuilder)
	inst.scalarListBuilder001 = builder.Field(1).(*array.ListBuilder)
	inst.membershipFieldBuilder002 = builder.Field(2).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder002 = builder.Field(2).(*array.ListBuilder)
	inst.membershipFieldBuilder003 = builder.Field(3).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder003 = builder.Field(3).(*array.ListBuilder)
	inst.membershipFieldBuilder004 = builder.Field(4).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.membershipListBuilder004 = builder.Field(4).(*array.ListBuilder)
	inst.membershipFieldBuilder005 = builder.Field(5).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder005 = builder.Field(5).(*array.ListBuilder)
	inst.membershipFieldBuilder006 = builder.Field(6).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.membershipListBuilder006 = builder.Field(6).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder007 = builder.Field(7).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder007 = builder.Field(7).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder008 = builder.Field(8).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder008 = builder.Field(8).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder009 = builder.Field(9).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder009 = builder.Field(9).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder010 = builder.Field(10).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder010 = builder.Field(10).(*array.ListBuilder)

	return inst
}
func (inst *InEntityDroneTableSectionSymbolInAttr) beginAttribute() {
	inst.membershipListBuilder002.Append(true)
	inst.membershipListBuilder003.Append(true)
	inst.membershipListBuilder004.Append(true)
	inst.membershipListBuilder005.Append(true)
	inst.membershipListBuilder006.Append(true)
	inst.membershipContainerLength002 = 0
	inst.membershipContainerLength003 = 0
	inst.membershipContainerLength004 = 0
	inst.membershipContainerLength005 = 0
	inst.membershipContainerLength006 = 0
	inst.scalarListBuilder001.Append(true)
	inst.membershipSupportListBuilder007.Append(true)
	inst.membershipSupportListBuilder008.Append(true)
	inst.membershipSupportListBuilder009.Append(true)
	inst.membershipSupportListBuilder010.Append(true)
	inst.state = runtime.EntityStateInSection
	inst.clearErrors()
}
func (inst *InEntityDroneTableSectionSymbolInAttr) AddMembershipHighCardRef(hr2 uint64) *InEntityDroneTableSectionSymbolInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder002.Append(hr2)
	inst.membershipContainerLength002++
	return inst
}
func (inst *InEntityDroneTableSectionSymbolInAttr) AddMembershipHighCardRefP(hr2 uint64) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder002.Append(hr2)
	inst.membershipContainerLength002++
	return
}
func (inst *InEntityDroneTableSectionSymbolInAttr) AddMembershipLowCardRef(lr3 uint64) *InEntityDroneTableSectionSymbolInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder003.Append(lr3)
	inst.membershipContainerLength003++
	return inst
}
func (inst *InEntityDroneTableSectionSymbolInAttr) AddMembershipLowCardRefP(lr3 uint64) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder003.Append(lr3)
	inst.membershipContainerLength003++
	return
}
func (inst *InEntityDroneTableSectionSymbolInAttr) AddMembershipLowCardVerbatim(lv4 []byte) *InEntityDroneTableSectionSymbolInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder004.Append(lv4)
	inst.membershipContainerLength004++
	return inst
}
func (inst *InEntityDroneTableSectionSymbolInAttr) AddMembershipLowCardVerbatimP(lv4 []byte) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder004.Append(lv4)
	inst.membershipContainerLength004++
	return
}
func (inst *InEntityDroneTableSectionSymbolInAttr) AddMembershipMixedLowCardRef(lmr5 uint64, mrhp6 []byte) *InEntityDroneTableSectionSymbolInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder005.Append(lmr5)
	inst.membershipFieldBuilder006.Append(mrhp6)
	inst.membershipContainerLength005++
	inst.membershipContainerLength006++
	return inst
}
func (inst *InEntityDroneTableSectionSymbolInAttr) AddMembershipMixedLowCardRefP(lmr5 uint64, mrhp6 []byte) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder005.Append(lmr5)
	inst.membershipFieldBuilder006.Append(mrhp6)
	inst.membershipContainerLength005++
	inst.membershipContainerLength006++
	return
}
func (inst *InEntityDroneTableSectionSymbolInAttr) handleMembershipSupportColumns() {
	var l int
	var _ = l
	l = inst.membershipContainerLength002
	inst.membershipContainerLength002 = 0
	inst.membershipSupportFieldBuilder007.Append(uint64(l))
	l = inst.membershipContainerLength003
	inst.membershipContainerLength003 = 0
	inst.membershipSupportFieldBuilder008.Append(uint64(l))
	l = inst.membershipContainerLength004
	inst.membershipContainerLength004 = 0
	inst.membershipSupportFieldBuilder009.Append(uint64(l))
	l = inst.membershipContainerLength005
	inst.membershipContainerLength005 = 0
	inst.membershipSupportFieldBuilder010.Append(uint64(l))
}
func (inst *InEntityDroneTableSectionSymbolInAttr) handleNonScalarSupportColumns() {
	var l int
	var _ = l
}
func (inst *InEntityDroneTableSectionSymbolInAttr) completeAttribute() {
	inst.handleMembershipSupportColumns()
	inst.handleNonScalarSupportColumns()
}
func (inst *InEntityDroneTableSectionSymbolInAttr) EndSection() *InEntityDroneTable {
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInitial
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent.parent
	}

	inst.completeAttribute()
	inst.parent.EndSection()
	return inst.parent.parent
}
func (inst *InEntityDroneTableSectionSymbolInAttr) EndAttribute() *InEntityDroneTableSectionSymbol {
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInSection
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent
	}

	inst.completeAttribute()
	inst.parent.endAttribute()
	return inst.parent
}
func (inst *InEntityDroneTableSectionSymbolInAttr) EndAttributeP() {
	inst.EndAttribute()
}

func (inst *InEntityDroneTableSectionSymbolInAttr) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityDroneTableSectionSymbolInAttr) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}

type InEntityDroneTableSectionSymbolArray struct {
	errs                           []error
	inAttr                         *InEntityDroneTableSectionSymbolArrayInAttr
	state                          runtime.EntityStateE
	attributeCount                 int
	parent                         *InEntityDroneTable
	homogenousArrayFieldBuilder022 *array.StringBuilder
	homogenousArrayListBuilder022  *array.ListBuilder
}

func NewInEntityDroneTableSectionSymbolArray(builder *array.RecordBuilder, parent *InEntityDroneTable) (inst *InEntityDroneTableSectionSymbolArray) {
	inst = &InEntityDroneTableSectionSymbolArray{}
	inAttr := NewInEntityDroneTableSectionSymbolArrayInAttr(builder, inst)
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.inAttr = inAttr
	inst.parent = parent
	inst.homogenousArrayFieldBuilder022 = builder.Field(22).(*array.ListBuilder).ValueBuilder().(*array.StringBuilder)
	inst.homogenousArrayListBuilder022 = builder.Field(22).(*array.ListBuilder)

	return inst
}
func (inst *InEntityDroneTableSectionSymbolArray) endAttribute() {
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInSection
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
}
func (inst *InEntityDroneTableSectionSymbolArray) BeginAttribute() *InEntityDroneTableSectionSymbolArrayInAttr {
	switch inst.state {
	case runtime.EntityStateInSection:
		inst.state = runtime.EntityStateInAttribute
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.inAttr
	}
	inst.attributeCount++

	inst.inAttr.state = inst.state
	return inst.inAttr
}
func (inst *InEntityDroneTableSectionSymbolArray) BeginAttributeSingle(value22 string) *InEntityDroneTableSectionSymbolArrayInAttr {
	return inst.BeginAttribute().AddToContainer(value22)
}
func (inst *InEntityDroneTableSectionSymbolArray) CheckErrors() (err error) {
	err = eh.CheckErrors(slices.Concat(inst.errs, inst.inAttr.errs))
	return
}
func (inst *InEntityDroneTableSectionSymbolArray) EndSection() *InEntityDroneTable {
	switch inst.state {
	case runtime.EntityStateInSection:
		inst.state = runtime.EntityStateInitial
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent
	}

	return inst.parent
}

func (inst *InEntityDroneTableSectionSymbolArray) beginSection() {
	inst.state = runtime.EntityStateInSection
	inst.attributeCount = 0
	inst.inAttr.beginAttribute()
}

func (inst *InEntityDroneTableSectionSymbolArray) resetSection() {
	inst.clearErrors()
	inst.inAttr.clearErrors()
	inst.attributeCount = 0
	inst.state = runtime.EntityStateInitial
}

func (inst *InEntityDroneTableSectionSymbolArray) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityDroneTableSectionSymbolArray) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}

type InEntityDroneTableSectionSymbolArrayInAttr struct {
	errs                                  []error
	state                                 runtime.EntityStateE
	parent                                *InEntityDroneTableSectionSymbolArray
	homogenousArrayFieldBuilder022        *array.StringBuilder
	homogenousArrayListBuilder022         *array.ListBuilder
	membershipFieldBuilder023             *array.Uint64Builder
	membershipListBuilder023              *array.ListBuilder
	membershipFieldBuilder024             *array.Uint64Builder
	membershipListBuilder024              *array.ListBuilder
	membershipFieldBuilder025             *array.BinaryBuilder
	membershipListBuilder025              *array.ListBuilder
	membershipFieldBuilder026             *array.Uint64Builder
	membershipListBuilder026              *array.ListBuilder
	membershipFieldBuilder027             *array.BinaryBuilder
	membershipListBuilder027              *array.ListBuilder
	homogenousArraySupportFieldBuilder028 *array.Uint64Builder
	homogenousArraySupportListBuilder028  *array.ListBuilder
	membershipSupportFieldBuilder029      *array.Uint64Builder
	membershipSupportListBuilder029       *array.ListBuilder
	membershipSupportFieldBuilder030      *array.Uint64Builder
	membershipSupportListBuilder030       *array.ListBuilder
	membershipSupportFieldBuilder031      *array.Uint64Builder
	membershipSupportListBuilder031       *array.ListBuilder
	membershipSupportFieldBuilder032      *array.Uint64Builder
	membershipSupportListBuilder032       *array.ListBuilder

	membershipContainerLength023 int

	membershipContainerLength024 int

	membershipContainerLength025 int

	membershipContainerLength026 int

	membershipContainerLength027 int

	homogenousArrayContainerLength022 int
}

func NewInEntityDroneTableSectionSymbolArrayInAttr(builder *array.RecordBuilder, parent *InEntityDroneTableSectionSymbolArray) (inst *InEntityDroneTableSectionSymbolArrayInAttr) {
	inst = &InEntityDroneTableSectionSymbolArrayInAttr{}
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.parent = parent
	inst.homogenousArrayFieldBuilder022 = builder.Field(22).(*array.ListBuilder).ValueBuilder().(*array.StringBuilder)
	inst.homogenousArrayListBuilder022 = builder.Field(22).(*array.ListBuilder)
	inst.membershipFieldBuilder023 = builder.Field(23).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder023 = builder.Field(23).(*array.ListBuilder)
	inst.membershipFieldBuilder024 = builder.Field(24).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder024 = builder.Field(24).(*array.ListBuilder)
	inst.membershipFieldBuilder025 = builder.Field(25).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.membershipListBuilder025 = builder.Field(25).(*array.ListBuilder)
	inst.membershipFieldBuilder026 = builder.Field(26).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder026 = builder.Field(26).(*array.ListBuilder)
	inst.membershipFieldBuilder027 = builder.Field(27).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.membershipListBuilder027 = builder.Field(27).(*array.ListBuilder)
	inst.homogenousArraySupportFieldBuilder028 = builder.Field(28).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.homogenousArraySupportListBuilder028 = builder.Field(28).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder029 = builder.Field(29).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder029 = builder.Field(29).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder030 = builder.Field(30).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder030 = builder.Field(30).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder031 = builder.Field(31).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder031 = builder.Field(31).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder032 = builder.Field(32).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder032 = builder.Field(32).(*array.ListBuilder)

	return inst
}
func (inst *InEntityDroneTableSectionSymbolArrayInAttr) beginAttribute() {
	inst.homogenousArrayListBuilder022.Append(true)
	inst.membershipListBuilder023.Append(true)
	inst.membershipListBuilder024.Append(true)
	inst.membershipListBuilder025.Append(true)
	inst.membershipListBuilder026.Append(true)
	inst.membershipListBuilder027.Append(true)
	inst.homogenousArrayContainerLength022 = 0
	inst.membershipContainerLength023 = 0
	inst.membershipContainerLength024 = 0
	inst.membershipContainerLength025 = 0
	inst.membershipContainerLength026 = 0
	inst.membershipContainerLength027 = 0
	inst.homogenousArraySupportListBuilder028.Append(true)
	inst.membershipSupportListBuilder029.Append(true)
	inst.membershipSupportListBuilder030.Append(true)
	inst.membershipSupportListBuilder031.Append(true)
	inst.membershipSupportListBuilder032.Append(true)
	inst.state = runtime.EntityStateInSection
	inst.clearErrors()
}
func (inst *InEntityDroneTableSectionSymbolArrayInAttr) AddToContainer(value22 string) *InEntityDroneTableSectionSymbolArrayInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.homogenousArrayFieldBuilder022.Append(value22)
	inst.homogenousArrayContainerLength022++
	return inst
}
func (inst *InEntityDroneTableSectionSymbolArrayInAttr) AddToContainerP(value22 string) {
	inst.AddToContainer(value22)
}
func (inst *InEntityDroneTableSectionSymbolArrayInAttr) AddMembershipHighCardRef(hr23 uint64) *InEntityDroneTableSectionSymbolArrayInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder023.Append(hr23)
	inst.membershipContainerLength023++
	return inst
}
func (inst *InEntityDroneTableSectionSymbolArrayInAttr) AddMembershipHighCardRefP(hr23 uint64) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder023.Append(hr23)
	inst.membershipContainerLength023++
	return
}
func (inst *InEntityDroneTableSectionSymbolArrayInAttr) AddMembershipLowCardRef(lr24 uint64) *InEntityDroneTableSectionSymbolArrayInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder024.Append(lr24)
	inst.membershipContainerLength024++
	return inst
}
func (inst *InEntityDroneTableSectionSymbolArrayInAttr) AddMembershipLowCardRefP(lr24 uint64) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder024.Append(lr24)
	inst.membershipContainerLength024++
	return
}
func (inst *InEntityDroneTableSectionSymbolArrayInAttr) AddMembershipLowCardVerbatim(lv25 []byte) *InEntityDroneTableSectionSymbolArrayInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder025.Append(lv25)
	inst.membershipContainerLength025++
	return inst
}
func (inst *InEntityDroneTableSectionSymbolArrayInAttr) AddMembershipLowCardVerbatimP(lv25 []byte) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder025.Append(lv25)
	inst.membershipContainerLength025++
	return
}
func (inst *InEntityDroneTableSectionSymbolArrayInAttr) AddMembershipMixedLowCardRef(lmr26 uint64, mrhp27 []byte) *InEntityDroneTableSectionSymbolArrayInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder026.Append(lmr26)
	inst.membershipFieldBuilder027.Append(mrhp27)
	inst.membershipContainerLength026++
	inst.membershipContainerLength027++
	return inst
}
func (inst *InEntityDroneTableSectionSymbolArrayInAttr) AddMembershipMixedLowCardRefP(lmr26 uint64, mrhp27 []byte) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder026.Append(lmr26)
	inst.membershipFieldBuilder027.Append(mrhp27)
	inst.membershipContainerLength026++
	inst.membershipContainerLength027++
	return
}
func (inst *InEntityDroneTableSectionSymbolArrayInAttr) handleMembershipSupportColumns() {
	var l int
	var _ = l
	l = inst.membershipContainerLength023
	inst.membershipContainerLength023 = 0
	inst.membershipSupportFieldBuilder029.Append(uint64(l))
	l = inst.membershipContainerLength024
	inst.membershipContainerLength024 = 0
	inst.membershipSupportFieldBuilder030.Append(uint64(l))
	l = inst.membershipContainerLength025
	inst.membershipContainerLength025 = 0
	inst.membershipSupportFieldBuilder031.Append(uint64(l))
	l = inst.membershipContainerLength026
	inst.membershipContainerLength026 = 0
	inst.membershipSupportFieldBuilder032.Append(uint64(l))
}
func (inst *InEntityDroneTableSectionSymbolArrayInAttr) handleNonScalarSupportColumns() {
	var l int
	var _ = l
	l = inst.homogenousArrayContainerLength022
	inst.homogenousArrayContainerLength022 = 0
	inst.homogenousArraySupportFieldBuilder028.Append(uint64(l))
}
func (inst *InEntityDroneTableSectionSymbolArrayInAttr) completeAttribute() {
	inst.handleMembershipSupportColumns()
	inst.handleNonScalarSupportColumns()
}
func (inst *InEntityDroneTableSectionSymbolArrayInAttr) EndSection() *InEntityDroneTable {
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInitial
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent.parent
	}

	inst.completeAttribute()
	inst.parent.EndSection()
	return inst.parent.parent
}
func (inst *InEntityDroneTableSectionSymbolArrayInAttr) EndAttribute() *InEntityDroneTableSectionSymbolArray {
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInSection
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent
	}

	inst.completeAttribute()
	inst.parent.endAttribute()
	return inst.parent
}
func (inst *InEntityDroneTableSectionSymbolArrayInAttr) EndAttributeP() {
	inst.EndAttribute()
}

func (inst *InEntityDroneTableSectionSymbolArrayInAttr) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityDroneTableSectionSymbolArrayInAttr) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}

type InEntityDroneTableSectionTimeRange struct {
	errs                  []error
	inAttr                *InEntityDroneTableSectionTimeRangeInAttr
	state                 runtime.EntityStateE
	attributeCount        int
	parent                *InEntityDroneTable
	scalarFieldBuilder045 *array.TimestampBuilder
	scalarListBuilder045  *array.ListBuilder
	scalarFieldBuilder046 *array.TimestampBuilder
	scalarListBuilder046  *array.ListBuilder
}

func NewInEntityDroneTableSectionTimeRange(builder *array.RecordBuilder, parent *InEntityDroneTable) (inst *InEntityDroneTableSectionTimeRange) {
	inst = &InEntityDroneTableSectionTimeRange{}
	inAttr := NewInEntityDroneTableSectionTimeRangeInAttr(builder, inst)
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.inAttr = inAttr
	inst.parent = parent
	inst.scalarFieldBuilder045 = builder.Field(45).(*array.ListBuilder).ValueBuilder().(*array.TimestampBuilder)
	inst.scalarListBuilder045 = builder.Field(45).(*array.ListBuilder)
	inst.scalarFieldBuilder046 = builder.Field(46).(*array.ListBuilder).ValueBuilder().(*array.TimestampBuilder)
	inst.scalarListBuilder046 = builder.Field(46).(*array.ListBuilder)

	return inst
}
func (inst *InEntityDroneTableSectionTimeRange) endAttribute() {
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInSection
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
}
func (inst *InEntityDroneTableSectionTimeRange) BeginAttribute(beginIncl45 time.Time, endExcl46 time.Time) *InEntityDroneTableSectionTimeRangeInAttr {
	switch inst.state {
	case runtime.EntityStateInSection:
		inst.state = runtime.EntityStateInAttribute
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.inAttr
	}
	inst.scalarFieldBuilder045.Append(arrow.Timestamp(beginIncl45.UnixNano()))
	inst.scalarFieldBuilder046.Append(arrow.Timestamp(endExcl46.UnixNano()))
	inst.attributeCount++

	inst.inAttr.state = inst.state
	return inst.inAttr
}
func (inst *InEntityDroneTableSectionTimeRange) CheckErrors() (err error) {
	err = eh.CheckErrors(slices.Concat(inst.errs, inst.inAttr.errs))
	return
}
func (inst *InEntityDroneTableSectionTimeRange) EndSection() *InEntityDroneTable {
	switch inst.state {
	case runtime.EntityStateInSection:
		inst.state = runtime.EntityStateInitial
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent
	}

	return inst.parent
}

func (inst *InEntityDroneTableSectionTimeRange) beginSection() {
	inst.state = runtime.EntityStateInSection
	inst.attributeCount = 0
	inst.inAttr.beginAttribute()
}

func (inst *InEntityDroneTableSectionTimeRange) resetSection() {
	inst.clearErrors()
	inst.inAttr.clearErrors()
	inst.attributeCount = 0
	inst.state = runtime.EntityStateInitial
}

func (inst *InEntityDroneTableSectionTimeRange) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityDroneTableSectionTimeRange) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}

type InEntityDroneTableSectionTimeRangeInAttr struct {
	errs                             []error
	state                            runtime.EntityStateE
	parent                           *InEntityDroneTableSectionTimeRange
	scalarFieldBuilder045            *array.TimestampBuilder
	scalarListBuilder045             *array.ListBuilder
	scalarFieldBuilder046            *array.TimestampBuilder
	scalarListBuilder046             *array.ListBuilder
	membershipFieldBuilder047        *array.Uint64Builder
	membershipListBuilder047         *array.ListBuilder
	membershipFieldBuilder048        *array.Uint64Builder
	membershipListBuilder048         *array.ListBuilder
	membershipFieldBuilder049        *array.BinaryBuilder
	membershipListBuilder049         *array.ListBuilder
	membershipFieldBuilder050        *array.Uint64Builder
	membershipListBuilder050         *array.ListBuilder
	membershipFieldBuilder051        *array.BinaryBuilder
	membershipListBuilder051         *array.ListBuilder
	membershipSupportFieldBuilder052 *array.Uint64Builder
	membershipSupportListBuilder052  *array.ListBuilder
	membershipSupportFieldBuilder053 *array.Uint64Builder
	membershipSupportListBuilder053  *array.ListBuilder
	membershipSupportFieldBuilder054 *array.Uint64Builder
	membershipSupportListBuilder054  *array.ListBuilder
	membershipSupportFieldBuilder055 *array.Uint64Builder
	membershipSupportListBuilder055  *array.ListBuilder

	membershipContainerLength047 int

	membershipContainerLength048 int

	membershipContainerLength049 int

	membershipContainerLength050 int

	membershipContainerLength051 int
}

func NewInEntityDroneTableSectionTimeRangeInAttr(builder *array.RecordBuilder, parent *InEntityDroneTableSectionTimeRange) (inst *InEntityDroneTableSectionTimeRangeInAttr) {
	inst = &InEntityDroneTableSectionTimeRangeInAttr{}
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.parent = parent
	inst.scalarFieldBuilder045 = builder.Field(45).(*array.ListBuilder).ValueBuilder().(*array.TimestampBuilder)
	inst.scalarListBuilder045 = builder.Field(45).(*array.ListBuilder)
	inst.scalarFieldBuilder046 = builder.Field(46).(*array.ListBuilder).ValueBuilder().(*array.TimestampBuilder)
	inst.scalarListBuilder046 = builder.Field(46).(*array.ListBuilder)
	inst.membershipFieldBuilder047 = builder.Field(47).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder047 = builder.Field(47).(*array.ListBuilder)
	inst.membershipFieldBuilder048 = builder.Field(48).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder048 = builder.Field(48).(*array.ListBuilder)
	inst.membershipFieldBuilder049 = builder.Field(49).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.membershipListBuilder049 = builder.Field(49).(*array.ListBuilder)
	inst.membershipFieldBuilder050 = builder.Field(50).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder050 = builder.Field(50).(*array.ListBuilder)
	inst.membershipFieldBuilder051 = builder.Field(51).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.membershipListBuilder051 = builder.Field(51).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder052 = builder.Field(52).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder052 = builder.Field(52).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder053 = builder.Field(53).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder053 = builder.Field(53).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder054 = builder.Field(54).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder054 = builder.Field(54).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder055 = builder.Field(55).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder055 = builder.Field(55).(*array.ListBuilder)

	return inst
}
func (inst *InEntityDroneTableSectionTimeRangeInAttr) beginAttribute() {
	inst.membershipListBuilder047.Append(true)
	inst.membershipListBuilder048.Append(true)
	inst.membershipListBuilder049.Append(true)
	inst.membershipListBuilder050.Append(true)
	inst.membershipListBuilder051.Append(true)
	inst.membershipContainerLength047 = 0
	inst.membershipContainerLength048 = 0
	inst.membershipContainerLength049 = 0
	inst.membershipContainerLength050 = 0
	inst.membershipContainerLength051 = 0
	inst.scalarListBuilder045.Append(true)
	inst.scalarListBuilder046.Append(true)
	inst.membershipSupportListBuilder052.Append(true)
	inst.membershipSupportListBuilder053.Append(true)
	inst.membershipSupportListBuilder054.Append(true)
	inst.membershipSupportListBuilder055.Append(true)
	inst.state = runtime.EntityStateInSection
	inst.clearErrors()
}
func (inst *InEntityDroneTableSectionTimeRangeInAttr) AddMembershipHighCardRef(hr47 uint64) *InEntityDroneTableSectionTimeRangeInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder047.Append(hr47)
	inst.membershipContainerLength047++
	return inst
}
func (inst *InEntityDroneTableSectionTimeRangeInAttr) AddMembershipHighCardRefP(hr47 uint64) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder047.Append(hr47)
	inst.membershipContainerLength047++
	return
}
func (inst *InEntityDroneTableSectionTimeRangeInAttr) AddMembershipLowCardRef(lr48 uint64) *InEntityDroneTableSectionTimeRangeInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder048.Append(lr48)
	inst.membershipContainerLength048++
	return inst
}
func (inst *InEntityDroneTableSectionTimeRangeInAttr) AddMembershipLowCardRefP(lr48 uint64) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder048.Append(lr48)
	inst.membershipContainerLength048++
	return
}
func (inst *InEntityDroneTableSectionTimeRangeInAttr) AddMembershipLowCardVerbatim(lv49 []byte) *InEntityDroneTableSectionTimeRangeInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder049.Append(lv49)
	inst.membershipContainerLength049++
	return inst
}
func (inst *InEntityDroneTableSectionTimeRangeInAttr) AddMembershipLowCardVerbatimP(lv49 []byte) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder049.Append(lv49)
	inst.membershipContainerLength049++
	return
}
func (inst *InEntityDroneTableSectionTimeRangeInAttr) AddMembershipMixedLowCardRef(lmr50 uint64, mrhp51 []byte) *InEntityDroneTableSectionTimeRangeInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder050.Append(lmr50)
	inst.membershipFieldBuilder051.Append(mrhp51)
	inst.membershipContainerLength050++
	inst.membershipContainerLength051++
	return inst
}
func (inst *InEntityDroneTableSectionTimeRangeInAttr) AddMembershipMixedLowCardRefP(lmr50 uint64, mrhp51 []byte) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder050.Append(lmr50)
	inst.membershipFieldBuilder051.Append(mrhp51)
	inst.membershipContainerLength050++
	inst.membershipContainerLength051++
	return
}
func (inst *InEntityDroneTableSectionTimeRangeInAttr) handleMembershipSupportColumns() {
	var l int
	var _ = l
	l = inst.membershipContainerLength047
	inst.membershipContainerLength047 = 0
	inst.membershipSupportFieldBuilder052.Append(uint64(l))
	l = inst.membershipContainerLength048
	inst.membershipContainerLength048 = 0
	inst.membershipSupportFieldBuilder053.Append(uint64(l))
	l = inst.membershipContainerLength049
	inst.membershipContainerLength049 = 0
	inst.membershipSupportFieldBuilder054.Append(uint64(l))
	l = inst.membershipContainerLength050
	inst.membershipContainerLength050 = 0
	inst.membershipSupportFieldBuilder055.Append(uint64(l))
}
func (inst *InEntityDroneTableSectionTimeRangeInAttr) handleNonScalarSupportColumns() {
	var l int
	var _ = l
}
func (inst *InEntityDroneTableSectionTimeRangeInAttr) completeAttribute() {
	inst.handleMembershipSupportColumns()
	inst.handleNonScalarSupportColumns()
}
func (inst *InEntityDroneTableSectionTimeRangeInAttr) EndSection() *InEntityDroneTable {
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInitial
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent.parent
	}

	inst.completeAttribute()
	inst.parent.EndSection()
	return inst.parent.parent
}
func (inst *InEntityDroneTableSectionTimeRangeInAttr) EndAttribute() *InEntityDroneTableSectionTimeRange {
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInSection
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent
	}

	inst.completeAttribute()
	inst.parent.endAttribute()
	return inst.parent
}
func (inst *InEntityDroneTableSectionTimeRangeInAttr) EndAttributeP() {
	inst.EndAttribute()
}

func (inst *InEntityDroneTableSectionTimeRangeInAttr) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityDroneTableSectionTimeRangeInAttr) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}

type InEntityDroneTableSectionU64Array struct {
	errs                           []error
	inAttr                         *InEntityDroneTableSectionU64ArrayInAttr
	state                          runtime.EntityStateE
	attributeCount                 int
	parent                         *InEntityDroneTable
	homogenousArrayFieldBuilder011 *array.Uint64Builder
	homogenousArrayListBuilder011  *array.ListBuilder
}

func NewInEntityDroneTableSectionU64Array(builder *array.RecordBuilder, parent *InEntityDroneTable) (inst *InEntityDroneTableSectionU64Array) {
	inst = &InEntityDroneTableSectionU64Array{}
	inAttr := NewInEntityDroneTableSectionU64ArrayInAttr(builder, inst)
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.inAttr = inAttr
	inst.parent = parent
	inst.homogenousArrayFieldBuilder011 = builder.Field(11).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.homogenousArrayListBuilder011 = builder.Field(11).(*array.ListBuilder)

	return inst
}
func (inst *InEntityDroneTableSectionU64Array) endAttribute() {
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInSection
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
}
func (inst *InEntityDroneTableSectionU64Array) BeginAttribute() *InEntityDroneTableSectionU64ArrayInAttr {
	switch inst.state {
	case runtime.EntityStateInSection:
		inst.state = runtime.EntityStateInAttribute
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.inAttr
	}
	inst.attributeCount++

	inst.inAttr.state = inst.state
	return inst.inAttr
}
func (inst *InEntityDroneTableSectionU64Array) BeginAttributeSingle(value11 uint64) *InEntityDroneTableSectionU64ArrayInAttr {
	return inst.BeginAttribute().AddToContainer(value11)
}
func (inst *InEntityDroneTableSectionU64Array) CheckErrors() (err error) {
	err = eh.CheckErrors(slices.Concat(inst.errs, inst.inAttr.errs))
	return
}
func (inst *InEntityDroneTableSectionU64Array) EndSection() *InEntityDroneTable {
	switch inst.state {
	case runtime.EntityStateInSection:
		inst.state = runtime.EntityStateInitial
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent
	}

	return inst.parent
}

func (inst *InEntityDroneTableSectionU64Array) beginSection() {
	inst.state = runtime.EntityStateInSection
	inst.attributeCount = 0
	inst.inAttr.beginAttribute()
}

func (inst *InEntityDroneTableSectionU64Array) resetSection() {
	inst.clearErrors()
	inst.inAttr.clearErrors()
	inst.attributeCount = 0
	inst.state = runtime.EntityStateInitial
}

func (inst *InEntityDroneTableSectionU64Array) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityDroneTableSectionU64Array) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}

type InEntityDroneTableSectionU64ArrayInAttr struct {
	errs                                  []error
	state                                 runtime.EntityStateE
	parent                                *InEntityDroneTableSectionU64Array
	homogenousArrayFieldBuilder011        *array.Uint64Builder
	homogenousArrayListBuilder011         *array.ListBuilder
	membershipFieldBuilder012             *array.Uint64Builder
	membershipListBuilder012              *array.ListBuilder
	membershipFieldBuilder013             *array.Uint64Builder
	membershipListBuilder013              *array.ListBuilder
	membershipFieldBuilder014             *array.BinaryBuilder
	membershipListBuilder014              *array.ListBuilder
	membershipFieldBuilder015             *array.Uint64Builder
	membershipListBuilder015              *array.ListBuilder
	membershipFieldBuilder016             *array.BinaryBuilder
	membershipListBuilder016              *array.ListBuilder
	homogenousArraySupportFieldBuilder017 *array.Uint64Builder
	homogenousArraySupportListBuilder017  *array.ListBuilder
	membershipSupportFieldBuilder018      *array.Uint64Builder
	membershipSupportListBuilder018       *array.ListBuilder
	membershipSupportFieldBuilder019      *array.Uint64Builder
	membershipSupportListBuilder019       *array.ListBuilder
	membershipSupportFieldBuilder020      *array.Uint64Builder
	membershipSupportListBuilder020       *array.ListBuilder
	membershipSupportFieldBuilder021      *array.Uint64Builder
	membershipSupportListBuilder021       *array.ListBuilder

	membershipContainerLength012 int

	membershipContainerLength013 int

	membershipContainerLength014 int

	membershipContainerLength015 int

	membershipContainerLength016 int

	homogenousArrayContainerLength011 int
}

func NewInEntityDroneTableSectionU64ArrayInAttr(builder *array.RecordBuilder, parent *InEntityDroneTableSectionU64Array) (inst *InEntityDroneTableSectionU64ArrayInAttr) {
	inst = &InEntityDroneTableSectionU64ArrayInAttr{}
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.parent = parent
	inst.homogenousArrayFieldBuilder011 = builder.Field(11).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.homogenousArrayListBuilder011 = builder.Field(11).(*array.ListBuilder)
	inst.membershipFieldBuilder012 = builder.Field(12).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder012 = builder.Field(12).(*array.ListBuilder)
	inst.membershipFieldBuilder013 = builder.Field(13).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder013 = builder.Field(13).(*array.ListBuilder)
	inst.membershipFieldBuilder014 = builder.Field(14).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.membershipListBuilder014 = builder.Field(14).(*array.ListBuilder)
	inst.membershipFieldBuilder015 = builder.Field(15).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder015 = builder.Field(15).(*array.ListBuilder)
	inst.membershipFieldBuilder016 = builder.Field(16).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.membershipListBuilder016 = builder.Field(16).(*array.ListBuilder)
	inst.homogenousArraySupportFieldBuilder017 = builder.Field(17).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.homogenousArraySupportListBuilder017 = builder.Field(17).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder018 = builder.Field(18).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder018 = builder.Field(18).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder019 = builder.Field(19).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder019 = builder.Field(19).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder020 = builder.Field(20).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder020 = builder.Field(20).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder021 = builder.Field(21).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder021 = builder.Field(21).(*array.ListBuilder)

	return inst
}
func (inst *InEntityDroneTableSectionU64ArrayInAttr) beginAttribute() {
	inst.homogenousArrayListBuilder011.Append(true)
	inst.membershipListBuilder012.Append(true)
	inst.membershipListBuilder013.Append(true)
	inst.membershipListBuilder014.Append(true)
	inst.membershipListBuilder015.Append(true)
	inst.membershipListBuilder016.Append(true)
	inst.homogenousArrayContainerLength011 = 0
	inst.membershipContainerLength012 = 0
	inst.membershipContainerLength013 = 0
	inst.membershipContainerLength014 = 0
	inst.membershipContainerLength015 = 0
	inst.membershipContainerLength016 = 0
	inst.homogenousArraySupportListBuilder017.Append(true)
	inst.membershipSupportListBuilder018.Append(true)
	inst.membershipSupportListBuilder019.Append(true)
	inst.membershipSupportListBuilder020.Append(true)
	inst.membershipSupportListBuilder021.Append(true)
	inst.state = runtime.EntityStateInSection
	inst.clearErrors()
}
func (inst *InEntityDroneTableSectionU64ArrayInAttr) AddToContainer(value11 uint64) *InEntityDroneTableSectionU64ArrayInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.homogenousArrayFieldBuilder011.Append(value11)
	inst.homogenousArrayContainerLength011++
	return inst
}
func (inst *InEntityDroneTableSectionU64ArrayInAttr) AddToContainerP(value11 uint64) {
	inst.AddToContainer(value11)
}
func (inst *InEntityDroneTableSectionU64ArrayInAttr) AddMembershipHighCardRef(hr12 uint64) *InEntityDroneTableSectionU64ArrayInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder012.Append(hr12)
	inst.membershipContainerLength012++
	return inst
}
func (inst *InEntityDroneTableSectionU64ArrayInAttr) AddMembershipHighCardRefP(hr12 uint64) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder012.Append(hr12)
	inst.membershipContainerLength012++
	return
}
func (inst *InEntityDroneTableSectionU64ArrayInAttr) AddMembershipLowCardRef(lr13 uint64) *InEntityDroneTableSectionU64ArrayInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder013.Append(lr13)
	inst.membershipContainerLength013++
	return inst
}
func (inst *InEntityDroneTableSectionU64ArrayInAttr) AddMembershipLowCardRefP(lr13 uint64) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder013.Append(lr13)
	inst.membershipContainerLength013++
	return
}
func (inst *InEntityDroneTableSectionU64ArrayInAttr) AddMembershipLowCardVerbatim(lv14 []byte) *InEntityDroneTableSectionU64ArrayInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder014.Append(lv14)
	inst.membershipContainerLength014++
	return inst
}
func (inst *InEntityDroneTableSectionU64ArrayInAttr) AddMembershipLowCardVerbatimP(lv14 []byte) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder014.Append(lv14)
	inst.membershipContainerLength014++
	return
}
func (inst *InEntityDroneTableSectionU64ArrayInAttr) AddMembershipMixedLowCardRef(lmr15 uint64, mrhp16 []byte) *InEntityDroneTableSectionU64ArrayInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder015.Append(lmr15)
	inst.membershipFieldBuilder016.Append(mrhp16)
	inst.membershipContainerLength015++
	inst.membershipContainerLength016++
	return inst
}
func (inst *InEntityDroneTableSectionU64ArrayInAttr) AddMembershipMixedLowCardRefP(lmr15 uint64, mrhp16 []byte) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder015.Append(lmr15)
	inst.membershipFieldBuilder016.Append(mrhp16)
	inst.membershipContainerLength015++
	inst.membershipContainerLength016++
	return
}
func (inst *InEntityDroneTableSectionU64ArrayInAttr) handleMembershipSupportColumns() {
	var l int
	var _ = l
	l = inst.membershipContainerLength012
	inst.membershipContainerLength012 = 0
	inst.membershipSupportFieldBuilder018.Append(uint64(l))
	l = inst.membershipContainerLength013
	inst.membershipContainerLength013 = 0
	inst.membershipSupportFieldBuilder019.Append(uint64(l))
	l = inst.membershipContainerLength014
	inst.membershipContainerLength014 = 0
	inst.membershipSupportFieldBuilder020.Append(uint64(l))
	l = inst.membershipContainerLength015
	inst.membershipContainerLength015 = 0
	inst.membershipSupportFieldBuilder021.Append(uint64(l))
}
func (inst *InEntityDroneTableSectionU64ArrayInAttr) handleNonScalarSupportColumns() {
	var l int
	var _ = l
	l = inst.homogenousArrayContainerLength011
	inst.homogenousArrayContainerLength011 = 0
	inst.homogenousArraySupportFieldBuilder017.Append(uint64(l))
}
func (inst *InEntityDroneTableSectionU64ArrayInAttr) completeAttribute() {
	inst.handleMembershipSupportColumns()
	inst.handleNonScalarSupportColumns()
}
func (inst *InEntityDroneTableSectionU64ArrayInAttr) EndSection() *InEntityDroneTable {
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInitial
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent.parent
	}

	inst.completeAttribute()
	inst.parent.EndSection()
	return inst.parent.parent
}
func (inst *InEntityDroneTableSectionU64ArrayInAttr) EndAttribute() *InEntityDroneTableSectionU64Array {
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInSection
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent
	}

	inst.completeAttribute()
	inst.parent.endAttribute()
	return inst.parent
}
func (inst *InEntityDroneTableSectionU64ArrayInAttr) EndAttributeP() {
	inst.EndAttribute()
}

func (inst *InEntityDroneTableSectionU64ArrayInAttr) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityDroneTableSectionU64ArrayInAttr) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}
