CREATE DATABASE IF NOT EXISTS boxer;

CREATE TABLE IF NOT EXISTS boxer.watchbillevent (
	"id:id:s:4::0:" String CODEC(ZSTD(3)),
	"ts:ts:z64:47::0:" DateTime64(9,'UTC') CODEC(Delta,ZSTD(3)),
	"tv:eventState:value:val:s:24:::0::data" Array(LowCardinality(String)) CODEC(ZSTD(3)),
	"tv:eventState:hr:hr:u64:47:::0::data" Array(UInt64) CODEC(Delta,ZSTD(3)),
	"tv:eventState:lr:lr:u64:1247:::0::data" Array(LowCardinality(UInt64)) CODEC(Delta,ZSTD(3)),
	"tv:eventState:lv:lv:y:124:::0::data" Array(LowCardinality(String)) CODEC(ZSTD(3)),
	"tv:eventState:lmr:lmr:u64:1247:::0::data" Array(LowCardinality(UInt64)) CODEC(Delta,ZSTD(3)),
	"tv:eventState:mrhp:mrhp:y:4:::0::data" Array(String) CODEC(ZSTD(3)),
	"tv:eventState:hrcard:hrcard:u64:4E:::0::data" Array(UInt64) CODEC(T64,ZSTD(3)),
	"tv:eventState:lrcard:lrcard:u64:4E:::0::data" Array(UInt64) CODEC(T64,ZSTD(3)),
	"tv:eventState:lvcard:lvcard:u64:4E:::0::data" Array(UInt64) CODEC(T64,ZSTD(3)),
	"tv:eventState:lmrcard:lmrcard:u64:4E:::0::data" Array(UInt64) CODEC(T64,ZSTD(3)),
	"tv:eventAttempt:value:val:u32:4:::0::data" Array(UInt32) CODEC(ZSTD(3)),
	"tv:eventAttempt:hr:hr:u64:47:::0::data" Array(UInt64) CODEC(Delta,ZSTD(3)),
	"tv:eventAttempt:lr:lr:u64:1247:::0::data" Array(LowCardinality(UInt64)) CODEC(Delta,ZSTD(3)),
	"tv:eventAttempt:lv:lv:y:124:::0::data" Array(LowCardinality(String)) CODEC(ZSTD(3)),
	"tv:eventAttempt:lmr:lmr:u64:1247:::0::data" Array(LowCardinality(UInt64)) CODEC(Delta,ZSTD(3)),
	"tv:eventAttempt:mrhp:mrhp:y:4:::0::data" Array(String) CODEC(ZSTD(3)),
	"tv:eventAttempt:hrcard:hrcard:u64:4E:::0::data" Array(UInt64) CODEC(T64,ZSTD(3)),
	"tv:eventAttempt:lrcard:lrcard:u64:4E:::0::data" Array(UInt64) CODEC(T64,ZSTD(3)),
	"tv:eventAttempt:lvcard:lvcard:u64:4E:::0::data" Array(UInt64) CODEC(T64,ZSTD(3)),
	"tv:eventAttempt:lmrcard:lmrcard:u64:4E:::0::data" Array(UInt64) CODEC(T64,ZSTD(3)),
	"tv:eventWorkerRun:value:val:s:24:::0::data" Array(LowCardinality(String)) CODEC(ZSTD(3)),
	"tv:eventWorkerRun:hr:hr:u64:47:::0::data" Array(UInt64) CODEC(Delta,ZSTD(3)),
	"tv:eventWorkerRun:lr:lr:u64:1247:::0::data" Array(LowCardinality(UInt64)) CODEC(Delta,ZSTD(3)),
	"tv:eventWorkerRun:lv:lv:y:124:::0::data" Array(LowCardinality(String)) CODEC(ZSTD(3)),
	"tv:eventWorkerRun:lmr:lmr:u64:1247:::0::data" Array(LowCardinality(UInt64)) CODEC(Delta,ZSTD(3)),
	"tv:eventWorkerRun:mrhp:mrhp:y:4:::0::data" Array(String) CODEC(ZSTD(3)),
	"tv:eventWorkerRun:hrcard:hrcard:u64:4E:::0::data" Array(UInt64) CODEC(T64,ZSTD(3)),
	"tv:eventWorkerRun:lrcard:lrcard:u64:4E:::0::data" Array(UInt64) CODEC(T64,ZSTD(3)),
	"tv:eventWorkerRun:lvcard:lvcard:u64:4E:::0::data" Array(UInt64) CODEC(T64,ZSTD(3)),
	"tv:eventWorkerRun:lmrcard:lmrcard:u64:4E:::0::data" Array(UInt64) CODEC(T64,ZSTD(3)),
	"tv:eventError:value:val:y:4:::0::data" Array(String) CODEC(ZSTD(3)),
	"tv:eventError:hr:hr:u64:47:::0::data" Array(UInt64) CODEC(Delta,ZSTD(3)),
	"tv:eventError:lr:lr:u64:1247:::0::data" Array(LowCardinality(UInt64)) CODEC(Delta,ZSTD(3)),
	"tv:eventError:lv:lv:y:124:::0::data" Array(LowCardinality(String)) CODEC(ZSTD(3)),
	"tv:eventError:lmr:lmr:u64:1247:::0::data" Array(LowCardinality(UInt64)) CODEC(Delta,ZSTD(3)),
	"tv:eventError:mrhp:mrhp:y:4:::0::data" Array(String) CODEC(ZSTD(3)),
	"tv:eventError:hrcard:hrcard:u64:4E:::0::data" Array(UInt64) CODEC(T64,ZSTD(3)),
	"tv:eventError:lrcard:lrcard:u64:4E:::0::data" Array(UInt64) CODEC(T64,ZSTD(3)),
	"tv:eventError:lvcard:lvcard:u64:4E:::0::data" Array(UInt64) CODEC(T64,ZSTD(3)),
	"tv:eventError:lmrcard:lmrcard:u64:4E:::0::data" Array(UInt64) CODEC(T64,ZSTD(3)),
	"tv:eventNote:value:val:s:4:::0::data" Array(String) CODEC(ZSTD(3)),
	"tv:eventNote:hr:hr:u64:47:::0::data" Array(UInt64) CODEC(Delta,ZSTD(3)),
	"tv:eventNote:lr:lr:u64:1247:::0::data" Array(LowCardinality(UInt64)) CODEC(Delta,ZSTD(3)),
	"tv:eventNote:lv:lv:y:124:::0::data" Array(LowCardinality(String)) CODEC(ZSTD(3)),
	"tv:eventNote:lmr:lmr:u64:1247:::0::data" Array(LowCardinality(UInt64)) CODEC(Delta,ZSTD(3)),
	"tv:eventNote:mrhp:mrhp:y:4:::0::data" Array(String) CODEC(ZSTD(3)),
	"tv:eventNote:hrcard:hrcard:u64:4E:::0::data" Array(UInt64) CODEC(T64,ZSTD(3)),
	"tv:eventNote:lrcard:lrcard:u64:4E:::0::data" Array(UInt64) CODEC(T64,ZSTD(3)),
	"tv:eventNote:lvcard:lvcard:u64:4E:::0::data" Array(UInt64) CODEC(T64,ZSTD(3)),
	"tv:eventNote:lmrcard:lmrcard:u64:4E:::0::data" Array(UInt64) CODEC(T64,ZSTD(3))
) ENGINE = MergeTree()
ORDER BY ("id:id:s:4::0:", "ts:ts:z64:47::0:")
SETTINGS allow_suspicious_low_cardinality_types=1