// Code generated by Leeway DML (github.com/stergiotis/boxer/public/keelson/runtime/persist/persiststore.test); DO NOT EDIT.

package lowlevel

import (
	"errors"
	"github.com/apache/arrow-go/v18/arrow"
	array "github.com/apache/arrow-go/v18/arrow/array"
	_ "github.com/apache/arrow-go/v18/arrow/ipc"
	_ "github.com/apache/arrow-go/v18/arrow/math"
	"github.com/apache/arrow-go/v18/arrow/memory"
	"github.com/stergiotis/boxer/public/observability/eh"
	"github.com/stergiotis/boxer/public/observability/eh/eb"
	"github.com/stergiotis/boxer/public/semistructured/leeway/dml/runtime"
	"slices"
	"time"
)

///////////////////////////////////////////////////////////////////
// code generator
// gocodegen.GenerateArrowSchemaFactory
// ./public/semistructured/leeway/gocodegen/gocodegen_common.go:26

func CreateSchemaPersiststateTable() (schema *arrow.Schema) {
	schema = arrow.NewSchema([]arrow.Field{
		/* 000 */ arrow.Field{Name: "id:id:s:4::0:", Nullable: false, Type: &arrow.StringType{}},
		/* 001 */ arrow.Field{Name: "ts:ts:z64:47::0:", Nullable: false, Type: &arrow.TimestampType{Unit: arrow.Nanosecond}},
		/* 002 */ arrow.Field{Name: "lc:lifecycle:u8:4::0:", Nullable: false, Type: arrow.PrimitiveTypes.Uint8},
		/* 003 */ arrow.Field{Name: "tv:symbol:value:val:s:24:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.StringType{})},
		/* 004 */ arrow.Field{Name: "tv:symbol:hr:hr:u64:47:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 005 */ arrow.Field{Name: "tv:symbol:lr:lr:u64:1247:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 006 */ arrow.Field{Name: "tv:symbol:lv:lv:y:124:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.BinaryType{})},
		/* 007 */ arrow.Field{Name: "tv:symbol:lmr:lmr:u64:1247:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 008 */ arrow.Field{Name: "tv:symbol:mrhp:mrhp:y:4:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.BinaryType{})},
		/* 009 */ arrow.Field{Name: "tv:symbol:hrcard:hrcard:u64:4E:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 010 */ arrow.Field{Name: "tv:symbol:lrcard:lrcard:u64:4E:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 011 */ arrow.Field{Name: "tv:symbol:lvcard:lvcard:u64:4E:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 012 */ arrow.Field{Name: "tv:symbol:lmrcard:lmrcard:u64:4E:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 013 */ arrow.Field{Name: "tv:string:value:val:s:4:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.StringType{})},
		/* 014 */ arrow.Field{Name: "tv:string:hr:hr:u64:47:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 015 */ arrow.Field{Name: "tv:string:lr:lr:u64:1247:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 016 */ arrow.Field{Name: "tv:string:lv:lv:y:124:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.BinaryType{})},
		/* 017 */ arrow.Field{Name: "tv:string:lmr:lmr:u64:1247:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 018 */ arrow.Field{Name: "tv:string:mrhp:mrhp:y:4:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.BinaryType{})},
		/* 019 */ arrow.Field{Name: "tv:string:hrcard:hrcard:u64:4E:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 020 */ arrow.Field{Name: "tv:string:lrcard:lrcard:u64:4E:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 021 */ arrow.Field{Name: "tv:string:lvcard:lvcard:u64:4E:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 022 */ arrow.Field{Name: "tv:string:lmrcard:lmrcard:u64:4E:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 023 */ arrow.Field{Name: "tv:blob:value:val:y:4:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.BinaryType{})},
		/* 024 */ arrow.Field{Name: "tv:blob:hr:hr:u64:47:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 025 */ arrow.Field{Name: "tv:blob:lr:lr:u64:1247:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 026 */ arrow.Field{Name: "tv:blob:lv:lv:y:124:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.BinaryType{})},
		/* 027 */ arrow.Field{Name: "tv:blob:lmr:lmr:u64:1247:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 028 */ arrow.Field{Name: "tv:blob:mrhp:mrhp:y:4:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.BinaryType{})},
		/* 029 */ arrow.Field{Name: "tv:blob:hrcard:hrcard:u64:4E:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 030 */ arrow.Field{Name: "tv:blob:lrcard:lrcard:u64:4E:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 031 */ arrow.Field{Name: "tv:blob:lvcard:lvcard:u64:4E:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 032 */ arrow.Field{Name: "tv:blob:lmrcard:lmrcard:u64:4E:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 033 */ arrow.Field{Name: "tv:u64:value:val:u64:4:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 034 */ arrow.Field{Name: "tv:u64:hr:hr:u64:47:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 035 */ arrow.Field{Name: "tv:u64:lr:lr:u64:1247:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 036 */ arrow.Field{Name: "tv:u64:lv:lv:y:124:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.BinaryType{})},
		/* 037 */ arrow.Field{Name: "tv:u64:lmr:lmr:u64:1247:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 038 */ arrow.Field{Name: "tv:u64:mrhp:mrhp:y:4:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.BinaryType{})},
		/* 039 */ arrow.Field{Name: "tv:u64:hrcard:hrcard:u64:4E:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 040 */ arrow.Field{Name: "tv:u64:lrcard:lrcard:u64:4E:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 041 */ arrow.Field{Name: "tv:u64:lvcard:lvcard:u64:4E:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 042 */ arrow.Field{Name: "tv:u64:lmrcard:lmrcard:u64:4E:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 043 */ arrow.Field{Name: "tv:f64:value:val:f64:4:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Float64)},
		/* 044 */ arrow.Field{Name: "tv:f64:hr:hr:u64:47:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 045 */ arrow.Field{Name: "tv:f64:lr:lr:u64:1247:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 046 */ arrow.Field{Name: "tv:f64:lv:lv:y:124:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.BinaryType{})},
		/* 047 */ arrow.Field{Name: "tv:f64:lmr:lmr:u64:1247:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 048 */ arrow.Field{Name: "tv:f64:mrhp:mrhp:y:4:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(&arrow.BinaryType{})},
		/* 049 */ arrow.Field{Name: "tv:f64:hrcard:hrcard:u64:4E:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 050 */ arrow.Field{Name: "tv:f64:lrcard:lrcard:u64:4E:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 051 */ arrow.Field{Name: "tv:f64:lvcard:lvcard:u64:4E:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
		/* 052 */ arrow.Field{Name: "tv:f64:lmrcard:lmrcard:u64:4E:::0::data", Nullable: false, Type: arrow.ListOfNonNullable(arrow.PrimitiveTypes.Uint64)},
	}, nil)
	return
}

///////////////////////////////////////////////////////////////////
// code generator
// dml.(*GoClassBuilder).ComposeEntityClassAndFactoryCode
// ./public/semistructured/leeway/dml/lw_dml_generator.go:1487

type InEntityPersiststateTable struct {
	errs               []error
	state              runtime.EntityStateE
	allocator          memory.Allocator
	builder            *array.RecordBuilder
	records            []arrow.RecordBatch
	section00Inst      *InEntityPersiststateTableSectionBlob
	section00State     runtime.EntityStateE
	section01Inst      *InEntityPersiststateTableSectionF64
	section01State     runtime.EntityStateE
	section02Inst      *InEntityPersiststateTableSectionString
	section02State     runtime.EntityStateE
	section03Inst      *InEntityPersiststateTableSectionSymbol
	section03State     runtime.EntityStateE
	section04Inst      *InEntityPersiststateTableSectionU64
	section04State     runtime.EntityStateE
	activeSections     *[5]bool
	ambientHighCardRef []uint64
	plainId0           string

	plainTs1 time.Time

	plainLifecycle2       uint8
	scalarFieldBuilder000 *array.StringBuilder

	scalarFieldBuilder001 *array.TimestampBuilder

	scalarFieldBuilder002 *array.Uint8Builder
}

func NewInEntityPersiststateTable(allocator memory.Allocator, estimatedNumberOfRecords int) (inst *InEntityPersiststateTable) {
	inst = &InEntityPersiststateTable{}
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.allocator = allocator
	inst.records = make([]arrow.RecordBatch, 0, estimatedNumberOfRecords)
	schema := CreateSchemaPersiststateTable()
	builder := array.NewRecordBuilder(allocator, schema)
	inst.builder = builder
	inst.initSections(builder)
	inst.scalarFieldBuilder000 = builder.Field(0).(*array.StringBuilder)
	inst.scalarFieldBuilder001 = builder.Field(1).(*array.TimestampBuilder)
	inst.scalarFieldBuilder002 = builder.Field(2).(*array.Uint8Builder)

	return inst
}

// SetActiveSections marks which section indices BeginEntity should
// initialise (skipping beginSection for the rest). Pass nil to clear.
// The hint is a performance optimisation; sending BeginAttribute to
// an unmarked section produces empty-list bytes at TransferRecords.
func (inst *InEntityPersiststateTable) setActiveSections(idxs []int) {
	if idxs == nil {
		inst.activeSections = nil
		return
	}
	var mask [5]bool
	for _, i := range idxs {
		if i >= 0 && i < len(mask) {
			mask[i] = true
		}
	}
	inst.activeSections = &mask
}

// InEntityPersiststateTableSectionIndices maps each section name to its section%02dInst slot in
// the generated entity. Useful for callers that need to compute
// SetActiveSections inputs from section names — for example, the
// marshallgen-driven keelson codec wrappers.
var InEntityPersiststateTableSectionIndices = map[string]int{
	"blob":   0,
	"f64":    1,
	"string": 2,
	"symbol": 3,
	"u64":    4,
}

///////////////////////////////////////////////////////////////////
// code generator
// dml.(*GoClassBuilder).ComposeEntityCode
// ./public/semistructured/leeway/dml/lw_dml_generator.go:1682

func (inst *InEntityPersiststateTable) setId(id0 string) *InEntityPersiststateTable {
	if inst.state != runtime.EntityStateInEntity {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.plainId0 = id0

	return inst
}

///////////////////////////////////////////////////////////////////
// code generator
// dml.(*GoClassBuilder).ComposeEntityCode
// ./public/semistructured/leeway/dml/lw_dml_generator.go:1682

func (inst *InEntityPersiststateTable) setTimestamp(ts1 time.Time) *InEntityPersiststateTable {
	if inst.state != runtime.EntityStateInEntity {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.plainTs1 = ts1

	return inst
}

///////////////////////////////////////////////////////////////////
// code generator
// dml.(*GoClassBuilder).ComposeEntityCode
// ./public/semistructured/leeway/dml/lw_dml_generator.go:1682

func (inst *InEntityPersiststateTable) setLifecycle(lifecycle2 uint8) *InEntityPersiststateTable {
	if inst.state != runtime.EntityStateInEntity {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.plainLifecycle2 = lifecycle2

	return inst
}

// PushMembershipHighCardRef adds id to the ambient HighCardRef memberships
// replayed onto every attribute as it closes, until it is popped (ADR-0112 M1).
// The stamp scope — one section vs the whole entity — is the caller's to set.
func (inst *InEntityPersiststateTable) PushMembershipHighCardRef(id uint64) {
	inst.ambientHighCardRef = append(inst.ambientHighCardRef, id)
}

// PopMembershipsHighCardRef removes the last n ambient HighCardRef memberships
// (bounds-clamped); balance it against PushMembershipHighCardRef.
func (inst *InEntityPersiststateTable) PopMembershipsHighCardRef(n int) {
	if n < 0 {
		n = 0
	}
	if n > len(inst.ambientHighCardRef) {
		n = len(inst.ambientHighCardRef)
	}
	inst.ambientHighCardRef = inst.ambientHighCardRef[:len(inst.ambientHighCardRef)-n]
}

// ClearMembershipsHighCardRef drops every ambient HighCardRef membership,
// pushed by anyone. It is the discard-everything counterpart to the balanced
// Push/Pop discipline — for a caller that owns the whole entity (a generated
// store's DiscardPending) and cannot know how many pushes abandoned frames
// left behind.
func (inst *InEntityPersiststateTable) ClearMembershipsHighCardRef() {
	inst.ambientHighCardRef = inst.ambientHighCardRef[:0]
}
func (inst *InEntityPersiststateTable) appendPlainValues() {
	inst.scalarFieldBuilder000.Append(inst.plainId0)

	inst.scalarFieldBuilder001.Append(arrow.Timestamp(inst.plainTs1.UnixNano()))

	inst.scalarFieldBuilder002.Append(inst.plainLifecycle2)
}
func (inst *InEntityPersiststateTable) resetPlainValues() {
	inst.plainId0 = ""

	inst.plainTs1 = time.Time{}

	inst.plainLifecycle2 = uint8(0)
}
func (inst *InEntityPersiststateTable) initSections(builder *array.RecordBuilder) {
	inst.section00Inst = NewInEntityPersiststateTableSectionBlob(builder, inst)
	inst.section01Inst = NewInEntityPersiststateTableSectionF64(builder, inst)
	inst.section02Inst = NewInEntityPersiststateTableSectionString(builder, inst)
	inst.section03Inst = NewInEntityPersiststateTableSectionSymbol(builder, inst)
	inst.section04Inst = NewInEntityPersiststateTableSectionU64(builder, inst)
}
func (inst *InEntityPersiststateTable) beginSections() {
	if mask := inst.activeSections; mask != nil {
		if mask[0] {
			inst.section00Inst.beginSection()
		}
		if mask[1] {
			inst.section01Inst.beginSection()
		}
		if mask[2] {
			inst.section02Inst.beginSection()
		}
		if mask[3] {
			inst.section03Inst.beginSection()
		}
		if mask[4] {
			inst.section04Inst.beginSection()
		}
		return
	}
	inst.section00Inst.beginSection()
	inst.section01Inst.beginSection()
	inst.section02Inst.beginSection()
	inst.section03Inst.beginSection()
	inst.section04Inst.beginSection()
}
func (inst *InEntityPersiststateTable) resetSections() {
	inst.section00Inst.resetSection()
	inst.section01Inst.resetSection()
	inst.section02Inst.resetSection()
	inst.section03Inst.resetSection()
	inst.section04Inst.resetSection()
}
func (inst *InEntityPersiststateTable) CheckErrors() (err error) {
	err = eh.CheckErrors(inst.errs)
	err = errors.Join(err, inst.section00Inst.CheckErrors())
	err = errors.Join(err, inst.section01Inst.CheckErrors())
	err = errors.Join(err, inst.section02Inst.CheckErrors())
	err = errors.Join(err, inst.section03Inst.CheckErrors())
	err = errors.Join(err, inst.section04Inst.CheckErrors())

	return
}
func (inst *InEntityPersiststateTable) GetSectionBlob() *InEntityPersiststateTableSectionBlob {
	return inst.section00Inst
}
func (inst *InEntityPersiststateTable) GetSectionF64() *InEntityPersiststateTableSectionF64 {
	return inst.section01Inst
}
func (inst *InEntityPersiststateTable) GetSectionString() *InEntityPersiststateTableSectionString {
	return inst.section02Inst
}
func (inst *InEntityPersiststateTable) GetSectionSymbol() *InEntityPersiststateTableSectionSymbol {
	return inst.section03Inst
}
func (inst *InEntityPersiststateTable) GetSectionU64() *InEntityPersiststateTableSectionU64 {
	return inst.section04Inst
}
func (inst *InEntityPersiststateTable) beginEntity() *InEntityPersiststateTable {
	switch inst.state {
	case runtime.EntityStateInitial:
		inst.state = runtime.EntityStateInEntity
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}

	inst.beginSections()
	return inst
}
func (inst *InEntityPersiststateTable) validateEntity() {
	{
		state := inst.section00Inst.state
		switch state {
		case runtime.EntityStateInAttribute:
			inst.AppendError(eb.Build().Str("section", "blob").Stringer("state", state).Errorf("wrong state: Check that .BeginAttribute() is followed by .EndAttribute()"))
			break
		}
	}
	{
		state := inst.section01Inst.state
		switch state {
		case runtime.EntityStateInAttribute:
			inst.AppendError(eb.Build().Str("section", "f64").Stringer("state", state).Errorf("wrong state: Check that .BeginAttribute() is followed by .EndAttribute()"))
			break
		}
	}
	{
		state := inst.section02Inst.state
		switch state {
		case runtime.EntityStateInAttribute:
			inst.AppendError(eb.Build().Str("section", "string").Stringer("state", state).Errorf("wrong state: Check that .BeginAttribute() is followed by .EndAttribute()"))
			break
		}
	}
	{
		state := inst.section03Inst.state
		switch state {
		case runtime.EntityStateInAttribute:
			inst.AppendError(eb.Build().Str("section", "symbol").Stringer("state", state).Errorf("wrong state: Check that .BeginAttribute() is followed by .EndAttribute()"))
			break
		}
	}
	{
		state := inst.section04Inst.state
		switch state {
		case runtime.EntityStateInAttribute:
			inst.AppendError(eb.Build().Str("section", "u64").Stringer("state", state).Errorf("wrong state: Check that .BeginAttribute() is followed by .EndAttribute()"))
			break
		}
	}

	return
}
func (inst *InEntityPersiststateTable) commitEntity() (err error) {
	inst.validateEntity()
	err = inst.CheckErrors()
	if err != nil {
		err = eh.Errorf("unable to commit entity, found errors: %w", err)
		return
	}
	switch inst.state {
	case runtime.EntityStateInEntity:
		inst.state = runtime.EntityStateInitial
		break
	default:
		err = runtime.ErrInvalidStateTransition
		return
	}

	inst.appendPlainValues()
	inst.resetPlainValues()
	inst.resetSections()
	return
}
func (inst *InEntityPersiststateTable) rollbackEntity() (err error) {
	switch inst.state {
	case runtime.EntityStateInEntity:
		inst.state = runtime.EntityStateInitial
		break
	default:
		err = runtime.ErrInvalidStateTransition
		return
	}

	inst.clearErrors()       // rollback is the recovery mechanism: discard the entity's errors
	inst.appendPlainValues() // arrow fields must all have one row
	inst.resetPlainValues()
	inst.resetSections()
	rec := inst.builder.NewRecord()
	if rec.NumRows() > 1 {
		inst.records = append(inst.records, rec.NewSlice(0, rec.NumRows()-1))
	} else {
		// FIXME find better way to truncate builder
		inst.builder.NewRecord().Release()
	}
	rec.Release()
	return
}

// TransferRecords The returned Records must be Release()'d after use.
func (inst *InEntityPersiststateTable) transferRecords(recordsIn []arrow.RecordBatch) (recordsOut []arrow.RecordBatch, err error) {
	if inst.state != runtime.EntityStateInitial {
		err = runtime.ErrInvalidStateTransition
		return
	}

	recordsOut = append(recordsIn, inst.records...)
	clear(inst.records)
	inst.records = inst.records[:0]
	rec := inst.builder.NewRecord()
	if rec.NumRows() > 0 {
		recordsOut = append(recordsOut, rec)
	} else {
		rec.Release() // an empty snapshot is nobody's to keep
	}
	return
}

func (inst *InEntityPersiststateTable) GetSchema() (schema *arrow.Schema) {
	return inst.builder.Schema()
}

// --- store control drivers (ADR-0100 SD6): exported access to InEntityPersiststateTable's
// unexported frame control, callable only from within this package. ---
func InEntityPersiststateTableBeginEntity(e *InEntityPersiststateTable) *InEntityPersiststateTable {
	return e.beginEntity()
}
func InEntityPersiststateTableCommitEntity(e *InEntityPersiststateTable) error {
	return e.commitEntity()
}
func InEntityPersiststateTableRollbackEntity(e *InEntityPersiststateTable) error {
	return e.rollbackEntity()
}
func InEntityPersiststateTableTransferRecords(e *InEntityPersiststateTable, recordsIn []arrow.RecordBatch) (recordsOut []arrow.RecordBatch, err error) {
	return e.transferRecords(recordsIn)
}
func InEntityPersiststateTableSetActiveSections(e *InEntityPersiststateTable, idxs []int) {
	e.setActiveSections(idxs)
}
func InEntityPersiststateTableReleaseBuilder(e *InEntityPersiststateTable) { e.builder.Release() }
func InEntityPersiststateTableSetId(e *InEntityPersiststateTable, id0 string) *InEntityPersiststateTable {
	return e.setId(id0)
}
func InEntityPersiststateTableSetTimestamp(e *InEntityPersiststateTable, ts1 time.Time) *InEntityPersiststateTable {
	return e.setTimestamp(ts1)
}
func InEntityPersiststateTableSetLifecycle(e *InEntityPersiststateTable, lifecycle2 uint8) *InEntityPersiststateTable {
	return e.setLifecycle(lifecycle2)
}

func (inst *InEntityPersiststateTable) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityPersiststateTable) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}

type InEntityPersiststateTableSectionBlob struct {
	errs                  []error
	inAttr                *InEntityPersiststateTableSectionBlobInAttr
	state                 runtime.EntityStateE
	attributeCount        int
	parent                *InEntityPersiststateTable
	scalarFieldBuilder023 *array.BinaryBuilder
	scalarListBuilder023  *array.ListBuilder
}

func NewInEntityPersiststateTableSectionBlob(builder *array.RecordBuilder, parent *InEntityPersiststateTable) (inst *InEntityPersiststateTableSectionBlob) {
	inst = &InEntityPersiststateTableSectionBlob{}
	inAttr := NewInEntityPersiststateTableSectionBlobInAttr(builder, inst)
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.inAttr = inAttr
	inst.parent = parent
	inst.scalarFieldBuilder023 = builder.Field(23).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.scalarListBuilder023 = builder.Field(23).(*array.ListBuilder)

	return inst
}
func (inst *InEntityPersiststateTableSectionBlob) endAttribute() {
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInSection
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
}
func (inst *InEntityPersiststateTableSectionBlob) BeginAttribute(value23 []byte) *InEntityPersiststateTableSectionBlobInAttr {
	switch inst.state {
	case runtime.EntityStateInSection:
		inst.state = runtime.EntityStateInAttribute
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.inAttr
	}
	inst.scalarFieldBuilder023.Append(value23)
	inst.attributeCount++

	inst.inAttr.state = inst.state
	return inst.inAttr
}

type InEntityPersiststateTableSectionBlobAttr struct {
	Value []byte
}

func (inst *InEntityPersiststateTableSectionBlob) Add(attr InEntityPersiststateTableSectionBlobAttr) *InEntityPersiststateTableSectionBlobInAttr {
	a := inst.BeginAttribute(attr.Value)
	return a
}
func (inst *InEntityPersiststateTableSectionBlob) CheckErrors() (err error) {
	err = eh.CheckErrors(slices.Concat(inst.errs, inst.inAttr.errs))
	return
}
func (inst *InEntityPersiststateTableSectionBlob) EndSection() *InEntityPersiststateTable {
	switch inst.state {
	case runtime.EntityStateInSection:
		inst.state = runtime.EntityStateInitial
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent
	}

	return inst.parent
}

func (inst *InEntityPersiststateTableSectionBlob) beginSection() {
	inst.state = runtime.EntityStateInSection
	inst.attributeCount = 0
	inst.inAttr.beginAttribute()
}

func (inst *InEntityPersiststateTableSectionBlob) resetSection() {
	inst.clearErrors()
	inst.inAttr.clearErrors()
	inst.attributeCount = 0
	inst.state = runtime.EntityStateInitial
}

func (inst *InEntityPersiststateTableSectionBlob) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityPersiststateTableSectionBlob) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}

type InEntityPersiststateTableSectionBlobInAttr struct {
	errs                             []error
	state                            runtime.EntityStateE
	parent                           *InEntityPersiststateTableSectionBlob
	scalarFieldBuilder023            *array.BinaryBuilder
	scalarListBuilder023             *array.ListBuilder
	membershipFieldBuilder024        *array.Uint64Builder
	membershipListBuilder024         *array.ListBuilder
	membershipFieldBuilder025        *array.Uint64Builder
	membershipListBuilder025         *array.ListBuilder
	membershipFieldBuilder026        *array.BinaryBuilder
	membershipListBuilder026         *array.ListBuilder
	membershipFieldBuilder027        *array.Uint64Builder
	membershipListBuilder027         *array.ListBuilder
	membershipFieldBuilder028        *array.BinaryBuilder
	membershipListBuilder028         *array.ListBuilder
	membershipSupportFieldBuilder029 *array.Uint64Builder
	membershipSupportListBuilder029  *array.ListBuilder
	membershipSupportFieldBuilder030 *array.Uint64Builder
	membershipSupportListBuilder030  *array.ListBuilder
	membershipSupportFieldBuilder031 *array.Uint64Builder
	membershipSupportListBuilder031  *array.ListBuilder
	membershipSupportFieldBuilder032 *array.Uint64Builder
	membershipSupportListBuilder032  *array.ListBuilder

	membershipContainerLength024 int

	membershipContainerLength025 int

	membershipContainerLength026 int

	membershipContainerLength027 int

	membershipContainerLength028 int
}

func NewInEntityPersiststateTableSectionBlobInAttr(builder *array.RecordBuilder, parent *InEntityPersiststateTableSectionBlob) (inst *InEntityPersiststateTableSectionBlobInAttr) {
	inst = &InEntityPersiststateTableSectionBlobInAttr{}
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.parent = parent
	inst.scalarFieldBuilder023 = builder.Field(23).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.scalarListBuilder023 = builder.Field(23).(*array.ListBuilder)
	inst.membershipFieldBuilder024 = builder.Field(24).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder024 = builder.Field(24).(*array.ListBuilder)
	inst.membershipFieldBuilder025 = builder.Field(25).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder025 = builder.Field(25).(*array.ListBuilder)
	inst.membershipFieldBuilder026 = builder.Field(26).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.membershipListBuilder026 = builder.Field(26).(*array.ListBuilder)
	inst.membershipFieldBuilder027 = builder.Field(27).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder027 = builder.Field(27).(*array.ListBuilder)
	inst.membershipFieldBuilder028 = builder.Field(28).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.membershipListBuilder028 = builder.Field(28).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder029 = builder.Field(29).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder029 = builder.Field(29).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder030 = builder.Field(30).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder030 = builder.Field(30).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder031 = builder.Field(31).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder031 = builder.Field(31).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder032 = builder.Field(32).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder032 = builder.Field(32).(*array.ListBuilder)

	return inst
}
func (inst *InEntityPersiststateTableSectionBlobInAttr) beginAttribute() {
	inst.membershipListBuilder024.Append(true)
	inst.membershipListBuilder025.Append(true)
	inst.membershipListBuilder026.Append(true)
	inst.membershipListBuilder027.Append(true)
	inst.membershipListBuilder028.Append(true)
	inst.membershipContainerLength024 = 0
	inst.membershipContainerLength025 = 0
	inst.membershipContainerLength026 = 0
	inst.membershipContainerLength027 = 0
	inst.membershipContainerLength028 = 0
	inst.scalarListBuilder023.Append(true)
	inst.membershipSupportListBuilder029.Append(true)
	inst.membershipSupportListBuilder030.Append(true)
	inst.membershipSupportListBuilder031.Append(true)
	inst.membershipSupportListBuilder032.Append(true)
	inst.state = runtime.EntityStateInSection
	inst.clearErrors()
}
func (inst *InEntityPersiststateTableSectionBlobInAttr) AddMembershipHighCardRef(hr24 uint64) *InEntityPersiststateTableSectionBlobInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder024.Append(hr24)
	inst.membershipContainerLength024++
	return inst
}
func (inst *InEntityPersiststateTableSectionBlobInAttr) AddMembershipHighCardRefP(hr24 uint64) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder024.Append(hr24)
	inst.membershipContainerLength024++
	return
}
func (inst *InEntityPersiststateTableSectionBlobInAttr) AddMembershipLowCardRef(lr25 uint64) *InEntityPersiststateTableSectionBlobInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder025.Append(lr25)
	inst.membershipContainerLength025++
	return inst
}
func (inst *InEntityPersiststateTableSectionBlobInAttr) AddMembershipLowCardRefP(lr25 uint64) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder025.Append(lr25)
	inst.membershipContainerLength025++
	return
}
func (inst *InEntityPersiststateTableSectionBlobInAttr) AddMembershipLowCardVerbatim(lv26 []byte) *InEntityPersiststateTableSectionBlobInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder026.Append(lv26)
	inst.membershipContainerLength026++
	return inst
}
func (inst *InEntityPersiststateTableSectionBlobInAttr) AddMembershipLowCardVerbatimP(lv26 []byte) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder026.Append(lv26)
	inst.membershipContainerLength026++
	return
}
func (inst *InEntityPersiststateTableSectionBlobInAttr) AddMembershipMixedLowCardRef(lmr27 uint64, mrhp28 []byte) *InEntityPersiststateTableSectionBlobInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder027.Append(lmr27)
	inst.membershipFieldBuilder028.Append(mrhp28)
	inst.membershipContainerLength027++
	inst.membershipContainerLength028++
	return inst
}
func (inst *InEntityPersiststateTableSectionBlobInAttr) AddMembershipMixedLowCardRefP(lmr27 uint64, mrhp28 []byte) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder027.Append(lmr27)
	inst.membershipFieldBuilder028.Append(mrhp28)
	inst.membershipContainerLength027++
	inst.membershipContainerLength028++
	return
}
func (inst *InEntityPersiststateTableSectionBlobInAttr) handleMembershipSupportColumns() {
	var l int
	var _ = l
	l = inst.membershipContainerLength024
	inst.membershipContainerLength024 = 0
	inst.membershipSupportFieldBuilder029.Append(uint64(l))
	l = inst.membershipContainerLength025
	inst.membershipContainerLength025 = 0
	inst.membershipSupportFieldBuilder030.Append(uint64(l))
	l = inst.membershipContainerLength026
	inst.membershipContainerLength026 = 0
	inst.membershipSupportFieldBuilder031.Append(uint64(l))
	l = inst.membershipContainerLength027
	inst.membershipContainerLength027 = 0
	inst.membershipSupportFieldBuilder032.Append(uint64(l))
}
func (inst *InEntityPersiststateTableSectionBlobInAttr) handleNonScalarSupportColumns() {
	var l int
	var _ = l
}
func (inst *InEntityPersiststateTableSectionBlobInAttr) applyAmbientMemberships() {
	if inst.state != runtime.EntityStateInAttribute {
		return
	}
	for _, v := range inst.parent.parent.ambientHighCardRef {
		inst.AddMembershipHighCardRefP(v)
	}
}
func (inst *InEntityPersiststateTableSectionBlobInAttr) completeAttribute() {
	inst.handleMembershipSupportColumns()
	inst.handleNonScalarSupportColumns()
}
func (inst *InEntityPersiststateTableSectionBlobInAttr) EndSection() *InEntityPersiststateTable {
	inst.applyAmbientMemberships()
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInitial
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent.parent
	}

	inst.completeAttribute()
	inst.parent.EndSection()
	return inst.parent.parent
}
func (inst *InEntityPersiststateTableSectionBlobInAttr) EndAttribute() *InEntityPersiststateTableSectionBlob {
	inst.applyAmbientMemberships()
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInSection
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent
	}

	inst.completeAttribute()
	inst.parent.endAttribute()
	return inst.parent
}
func (inst *InEntityPersiststateTableSectionBlobInAttr) EndAttributeP() {
	inst.EndAttribute()
}

func (inst *InEntityPersiststateTableSectionBlobInAttr) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityPersiststateTableSectionBlobInAttr) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}

type InEntityPersiststateTableSectionF64 struct {
	errs                  []error
	inAttr                *InEntityPersiststateTableSectionF64InAttr
	state                 runtime.EntityStateE
	attributeCount        int
	parent                *InEntityPersiststateTable
	scalarFieldBuilder043 *array.Float64Builder
	scalarListBuilder043  *array.ListBuilder
}

func NewInEntityPersiststateTableSectionF64(builder *array.RecordBuilder, parent *InEntityPersiststateTable) (inst *InEntityPersiststateTableSectionF64) {
	inst = &InEntityPersiststateTableSectionF64{}
	inAttr := NewInEntityPersiststateTableSectionF64InAttr(builder, inst)
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.inAttr = inAttr
	inst.parent = parent
	inst.scalarFieldBuilder043 = builder.Field(43).(*array.ListBuilder).ValueBuilder().(*array.Float64Builder)
	inst.scalarListBuilder043 = builder.Field(43).(*array.ListBuilder)

	return inst
}
func (inst *InEntityPersiststateTableSectionF64) endAttribute() {
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInSection
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
}
func (inst *InEntityPersiststateTableSectionF64) BeginAttribute(value43 float64) *InEntityPersiststateTableSectionF64InAttr {
	switch inst.state {
	case runtime.EntityStateInSection:
		inst.state = runtime.EntityStateInAttribute
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.inAttr
	}
	inst.scalarFieldBuilder043.Append(value43)
	inst.attributeCount++

	inst.inAttr.state = inst.state
	return inst.inAttr
}

type InEntityPersiststateTableSectionF64Attr struct {
	Value float64
}

func (inst *InEntityPersiststateTableSectionF64) Add(attr InEntityPersiststateTableSectionF64Attr) *InEntityPersiststateTableSectionF64InAttr {
	a := inst.BeginAttribute(attr.Value)
	return a
}
func (inst *InEntityPersiststateTableSectionF64) CheckErrors() (err error) {
	err = eh.CheckErrors(slices.Concat(inst.errs, inst.inAttr.errs))
	return
}
func (inst *InEntityPersiststateTableSectionF64) EndSection() *InEntityPersiststateTable {
	switch inst.state {
	case runtime.EntityStateInSection:
		inst.state = runtime.EntityStateInitial
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent
	}

	return inst.parent
}

func (inst *InEntityPersiststateTableSectionF64) beginSection() {
	inst.state = runtime.EntityStateInSection
	inst.attributeCount = 0
	inst.inAttr.beginAttribute()
}

func (inst *InEntityPersiststateTableSectionF64) resetSection() {
	inst.clearErrors()
	inst.inAttr.clearErrors()
	inst.attributeCount = 0
	inst.state = runtime.EntityStateInitial
}

func (inst *InEntityPersiststateTableSectionF64) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityPersiststateTableSectionF64) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}

type InEntityPersiststateTableSectionF64InAttr struct {
	errs                             []error
	state                            runtime.EntityStateE
	parent                           *InEntityPersiststateTableSectionF64
	scalarFieldBuilder043            *array.Float64Builder
	scalarListBuilder043             *array.ListBuilder
	membershipFieldBuilder044        *array.Uint64Builder
	membershipListBuilder044         *array.ListBuilder
	membershipFieldBuilder045        *array.Uint64Builder
	membershipListBuilder045         *array.ListBuilder
	membershipFieldBuilder046        *array.BinaryBuilder
	membershipListBuilder046         *array.ListBuilder
	membershipFieldBuilder047        *array.Uint64Builder
	membershipListBuilder047         *array.ListBuilder
	membershipFieldBuilder048        *array.BinaryBuilder
	membershipListBuilder048         *array.ListBuilder
	membershipSupportFieldBuilder049 *array.Uint64Builder
	membershipSupportListBuilder049  *array.ListBuilder
	membershipSupportFieldBuilder050 *array.Uint64Builder
	membershipSupportListBuilder050  *array.ListBuilder
	membershipSupportFieldBuilder051 *array.Uint64Builder
	membershipSupportListBuilder051  *array.ListBuilder
	membershipSupportFieldBuilder052 *array.Uint64Builder
	membershipSupportListBuilder052  *array.ListBuilder

	membershipContainerLength044 int

	membershipContainerLength045 int

	membershipContainerLength046 int

	membershipContainerLength047 int

	membershipContainerLength048 int
}

func NewInEntityPersiststateTableSectionF64InAttr(builder *array.RecordBuilder, parent *InEntityPersiststateTableSectionF64) (inst *InEntityPersiststateTableSectionF64InAttr) {
	inst = &InEntityPersiststateTableSectionF64InAttr{}
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.parent = parent
	inst.scalarFieldBuilder043 = builder.Field(43).(*array.ListBuilder).ValueBuilder().(*array.Float64Builder)
	inst.scalarListBuilder043 = builder.Field(43).(*array.ListBuilder)
	inst.membershipFieldBuilder044 = builder.Field(44).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder044 = builder.Field(44).(*array.ListBuilder)
	inst.membershipFieldBuilder045 = builder.Field(45).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder045 = builder.Field(45).(*array.ListBuilder)
	inst.membershipFieldBuilder046 = builder.Field(46).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.membershipListBuilder046 = builder.Field(46).(*array.ListBuilder)
	inst.membershipFieldBuilder047 = builder.Field(47).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder047 = builder.Field(47).(*array.ListBuilder)
	inst.membershipFieldBuilder048 = builder.Field(48).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.membershipListBuilder048 = builder.Field(48).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder049 = builder.Field(49).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder049 = builder.Field(49).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder050 = builder.Field(50).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder050 = builder.Field(50).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder051 = builder.Field(51).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder051 = builder.Field(51).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder052 = builder.Field(52).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder052 = builder.Field(52).(*array.ListBuilder)

	return inst
}
func (inst *InEntityPersiststateTableSectionF64InAttr) beginAttribute() {
	inst.membershipListBuilder044.Append(true)
	inst.membershipListBuilder045.Append(true)
	inst.membershipListBuilder046.Append(true)
	inst.membershipListBuilder047.Append(true)
	inst.membershipListBuilder048.Append(true)
	inst.membershipContainerLength044 = 0
	inst.membershipContainerLength045 = 0
	inst.membershipContainerLength046 = 0
	inst.membershipContainerLength047 = 0
	inst.membershipContainerLength048 = 0
	inst.scalarListBuilder043.Append(true)
	inst.membershipSupportListBuilder049.Append(true)
	inst.membershipSupportListBuilder050.Append(true)
	inst.membershipSupportListBuilder051.Append(true)
	inst.membershipSupportListBuilder052.Append(true)
	inst.state = runtime.EntityStateInSection
	inst.clearErrors()
}
func (inst *InEntityPersiststateTableSectionF64InAttr) AddMembershipHighCardRef(hr44 uint64) *InEntityPersiststateTableSectionF64InAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder044.Append(hr44)
	inst.membershipContainerLength044++
	return inst
}
func (inst *InEntityPersiststateTableSectionF64InAttr) AddMembershipHighCardRefP(hr44 uint64) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder044.Append(hr44)
	inst.membershipContainerLength044++
	return
}
func (inst *InEntityPersiststateTableSectionF64InAttr) AddMembershipLowCardRef(lr45 uint64) *InEntityPersiststateTableSectionF64InAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder045.Append(lr45)
	inst.membershipContainerLength045++
	return inst
}
func (inst *InEntityPersiststateTableSectionF64InAttr) AddMembershipLowCardRefP(lr45 uint64) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder045.Append(lr45)
	inst.membershipContainerLength045++
	return
}
func (inst *InEntityPersiststateTableSectionF64InAttr) AddMembershipLowCardVerbatim(lv46 []byte) *InEntityPersiststateTableSectionF64InAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder046.Append(lv46)
	inst.membershipContainerLength046++
	return inst
}
func (inst *InEntityPersiststateTableSectionF64InAttr) AddMembershipLowCardVerbatimP(lv46 []byte) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder046.Append(lv46)
	inst.membershipContainerLength046++
	return
}
func (inst *InEntityPersiststateTableSectionF64InAttr) AddMembershipMixedLowCardRef(lmr47 uint64, mrhp48 []byte) *InEntityPersiststateTableSectionF64InAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder047.Append(lmr47)
	inst.membershipFieldBuilder048.Append(mrhp48)
	inst.membershipContainerLength047++
	inst.membershipContainerLength048++
	return inst
}
func (inst *InEntityPersiststateTableSectionF64InAttr) AddMembershipMixedLowCardRefP(lmr47 uint64, mrhp48 []byte) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder047.Append(lmr47)
	inst.membershipFieldBuilder048.Append(mrhp48)
	inst.membershipContainerLength047++
	inst.membershipContainerLength048++
	return
}
func (inst *InEntityPersiststateTableSectionF64InAttr) handleMembershipSupportColumns() {
	var l int
	var _ = l
	l = inst.membershipContainerLength044
	inst.membershipContainerLength044 = 0
	inst.membershipSupportFieldBuilder049.Append(uint64(l))
	l = inst.membershipContainerLength045
	inst.membershipContainerLength045 = 0
	inst.membershipSupportFieldBuilder050.Append(uint64(l))
	l = inst.membershipContainerLength046
	inst.membershipContainerLength046 = 0
	inst.membershipSupportFieldBuilder051.Append(uint64(l))
	l = inst.membershipContainerLength047
	inst.membershipContainerLength047 = 0
	inst.membershipSupportFieldBuilder052.Append(uint64(l))
}
func (inst *InEntityPersiststateTableSectionF64InAttr) handleNonScalarSupportColumns() {
	var l int
	var _ = l
}
func (inst *InEntityPersiststateTableSectionF64InAttr) applyAmbientMemberships() {
	if inst.state != runtime.EntityStateInAttribute {
		return
	}
	for _, v := range inst.parent.parent.ambientHighCardRef {
		inst.AddMembershipHighCardRefP(v)
	}
}
func (inst *InEntityPersiststateTableSectionF64InAttr) completeAttribute() {
	inst.handleMembershipSupportColumns()
	inst.handleNonScalarSupportColumns()
}
func (inst *InEntityPersiststateTableSectionF64InAttr) EndSection() *InEntityPersiststateTable {
	inst.applyAmbientMemberships()
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInitial
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent.parent
	}

	inst.completeAttribute()
	inst.parent.EndSection()
	return inst.parent.parent
}
func (inst *InEntityPersiststateTableSectionF64InAttr) EndAttribute() *InEntityPersiststateTableSectionF64 {
	inst.applyAmbientMemberships()
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInSection
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent
	}

	inst.completeAttribute()
	inst.parent.endAttribute()
	return inst.parent
}
func (inst *InEntityPersiststateTableSectionF64InAttr) EndAttributeP() {
	inst.EndAttribute()
}

func (inst *InEntityPersiststateTableSectionF64InAttr) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityPersiststateTableSectionF64InAttr) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}

type InEntityPersiststateTableSectionString struct {
	errs                  []error
	inAttr                *InEntityPersiststateTableSectionStringInAttr
	state                 runtime.EntityStateE
	attributeCount        int
	parent                *InEntityPersiststateTable
	scalarFieldBuilder013 *array.StringBuilder
	scalarListBuilder013  *array.ListBuilder
}

func NewInEntityPersiststateTableSectionString(builder *array.RecordBuilder, parent *InEntityPersiststateTable) (inst *InEntityPersiststateTableSectionString) {
	inst = &InEntityPersiststateTableSectionString{}
	inAttr := NewInEntityPersiststateTableSectionStringInAttr(builder, inst)
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.inAttr = inAttr
	inst.parent = parent
	inst.scalarFieldBuilder013 = builder.Field(13).(*array.ListBuilder).ValueBuilder().(*array.StringBuilder)
	inst.scalarListBuilder013 = builder.Field(13).(*array.ListBuilder)

	return inst
}
func (inst *InEntityPersiststateTableSectionString) endAttribute() {
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInSection
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
}
func (inst *InEntityPersiststateTableSectionString) BeginAttribute(value13 string) *InEntityPersiststateTableSectionStringInAttr {
	switch inst.state {
	case runtime.EntityStateInSection:
		inst.state = runtime.EntityStateInAttribute
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.inAttr
	}
	inst.scalarFieldBuilder013.Append(value13)
	inst.attributeCount++

	inst.inAttr.state = inst.state
	return inst.inAttr
}

type InEntityPersiststateTableSectionStringAttr struct {
	Value string
}

func (inst *InEntityPersiststateTableSectionString) Add(attr InEntityPersiststateTableSectionStringAttr) *InEntityPersiststateTableSectionStringInAttr {
	a := inst.BeginAttribute(attr.Value)
	return a
}
func (inst *InEntityPersiststateTableSectionString) CheckErrors() (err error) {
	err = eh.CheckErrors(slices.Concat(inst.errs, inst.inAttr.errs))
	return
}
func (inst *InEntityPersiststateTableSectionString) EndSection() *InEntityPersiststateTable {
	switch inst.state {
	case runtime.EntityStateInSection:
		inst.state = runtime.EntityStateInitial
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent
	}

	return inst.parent
}

func (inst *InEntityPersiststateTableSectionString) beginSection() {
	inst.state = runtime.EntityStateInSection
	inst.attributeCount = 0
	inst.inAttr.beginAttribute()
}

func (inst *InEntityPersiststateTableSectionString) resetSection() {
	inst.clearErrors()
	inst.inAttr.clearErrors()
	inst.attributeCount = 0
	inst.state = runtime.EntityStateInitial
}

func (inst *InEntityPersiststateTableSectionString) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityPersiststateTableSectionString) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}

type InEntityPersiststateTableSectionStringInAttr struct {
	errs                             []error
	state                            runtime.EntityStateE
	parent                           *InEntityPersiststateTableSectionString
	scalarFieldBuilder013            *array.StringBuilder
	scalarListBuilder013             *array.ListBuilder
	membershipFieldBuilder014        *array.Uint64Builder
	membershipListBuilder014         *array.ListBuilder
	membershipFieldBuilder015        *array.Uint64Builder
	membershipListBuilder015         *array.ListBuilder
	membershipFieldBuilder016        *array.BinaryBuilder
	membershipListBuilder016         *array.ListBuilder
	membershipFieldBuilder017        *array.Uint64Builder
	membershipListBuilder017         *array.ListBuilder
	membershipFieldBuilder018        *array.BinaryBuilder
	membershipListBuilder018         *array.ListBuilder
	membershipSupportFieldBuilder019 *array.Uint64Builder
	membershipSupportListBuilder019  *array.ListBuilder
	membershipSupportFieldBuilder020 *array.Uint64Builder
	membershipSupportListBuilder020  *array.ListBuilder
	membershipSupportFieldBuilder021 *array.Uint64Builder
	membershipSupportListBuilder021  *array.ListBuilder
	membershipSupportFieldBuilder022 *array.Uint64Builder
	membershipSupportListBuilder022  *array.ListBuilder

	membershipContainerLength014 int

	membershipContainerLength015 int

	membershipContainerLength016 int

	membershipContainerLength017 int

	membershipContainerLength018 int
}

func NewInEntityPersiststateTableSectionStringInAttr(builder *array.RecordBuilder, parent *InEntityPersiststateTableSectionString) (inst *InEntityPersiststateTableSectionStringInAttr) {
	inst = &InEntityPersiststateTableSectionStringInAttr{}
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.parent = parent
	inst.scalarFieldBuilder013 = builder.Field(13).(*array.ListBuilder).ValueBuilder().(*array.StringBuilder)
	inst.scalarListBuilder013 = builder.Field(13).(*array.ListBuilder)
	inst.membershipFieldBuilder014 = builder.Field(14).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder014 = builder.Field(14).(*array.ListBuilder)
	inst.membershipFieldBuilder015 = builder.Field(15).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder015 = builder.Field(15).(*array.ListBuilder)
	inst.membershipFieldBuilder016 = builder.Field(16).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.membershipListBuilder016 = builder.Field(16).(*array.ListBuilder)
	inst.membershipFieldBuilder017 = builder.Field(17).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder017 = builder.Field(17).(*array.ListBuilder)
	inst.membershipFieldBuilder018 = builder.Field(18).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.membershipListBuilder018 = builder.Field(18).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder019 = builder.Field(19).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder019 = builder.Field(19).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder020 = builder.Field(20).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder020 = builder.Field(20).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder021 = builder.Field(21).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder021 = builder.Field(21).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder022 = builder.Field(22).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder022 = builder.Field(22).(*array.ListBuilder)

	return inst
}
func (inst *InEntityPersiststateTableSectionStringInAttr) beginAttribute() {
	inst.membershipListBuilder014.Append(true)
	inst.membershipListBuilder015.Append(true)
	inst.membershipListBuilder016.Append(true)
	inst.membershipListBuilder017.Append(true)
	inst.membershipListBuilder018.Append(true)
	inst.membershipContainerLength014 = 0
	inst.membershipContainerLength015 = 0
	inst.membershipContainerLength016 = 0
	inst.membershipContainerLength017 = 0
	inst.membershipContainerLength018 = 0
	inst.scalarListBuilder013.Append(true)
	inst.membershipSupportListBuilder019.Append(true)
	inst.membershipSupportListBuilder020.Append(true)
	inst.membershipSupportListBuilder021.Append(true)
	inst.membershipSupportListBuilder022.Append(true)
	inst.state = runtime.EntityStateInSection
	inst.clearErrors()
}
func (inst *InEntityPersiststateTableSectionStringInAttr) AddMembershipHighCardRef(hr14 uint64) *InEntityPersiststateTableSectionStringInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder014.Append(hr14)
	inst.membershipContainerLength014++
	return inst
}
func (inst *InEntityPersiststateTableSectionStringInAttr) AddMembershipHighCardRefP(hr14 uint64) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder014.Append(hr14)
	inst.membershipContainerLength014++
	return
}
func (inst *InEntityPersiststateTableSectionStringInAttr) AddMembershipLowCardRef(lr15 uint64) *InEntityPersiststateTableSectionStringInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder015.Append(lr15)
	inst.membershipContainerLength015++
	return inst
}
func (inst *InEntityPersiststateTableSectionStringInAttr) AddMembershipLowCardRefP(lr15 uint64) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder015.Append(lr15)
	inst.membershipContainerLength015++
	return
}
func (inst *InEntityPersiststateTableSectionStringInAttr) AddMembershipLowCardVerbatim(lv16 []byte) *InEntityPersiststateTableSectionStringInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder016.Append(lv16)
	inst.membershipContainerLength016++
	return inst
}
func (inst *InEntityPersiststateTableSectionStringInAttr) AddMembershipLowCardVerbatimP(lv16 []byte) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder016.Append(lv16)
	inst.membershipContainerLength016++
	return
}
func (inst *InEntityPersiststateTableSectionStringInAttr) AddMembershipMixedLowCardRef(lmr17 uint64, mrhp18 []byte) *InEntityPersiststateTableSectionStringInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder017.Append(lmr17)
	inst.membershipFieldBuilder018.Append(mrhp18)
	inst.membershipContainerLength017++
	inst.membershipContainerLength018++
	return inst
}
func (inst *InEntityPersiststateTableSectionStringInAttr) AddMembershipMixedLowCardRefP(lmr17 uint64, mrhp18 []byte) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder017.Append(lmr17)
	inst.membershipFieldBuilder018.Append(mrhp18)
	inst.membershipContainerLength017++
	inst.membershipContainerLength018++
	return
}
func (inst *InEntityPersiststateTableSectionStringInAttr) handleMembershipSupportColumns() {
	var l int
	var _ = l
	l = inst.membershipContainerLength014
	inst.membershipContainerLength014 = 0
	inst.membershipSupportFieldBuilder019.Append(uint64(l))
	l = inst.membershipContainerLength015
	inst.membershipContainerLength015 = 0
	inst.membershipSupportFieldBuilder020.Append(uint64(l))
	l = inst.membershipContainerLength016
	inst.membershipContainerLength016 = 0
	inst.membershipSupportFieldBuilder021.Append(uint64(l))
	l = inst.membershipContainerLength017
	inst.membershipContainerLength017 = 0
	inst.membershipSupportFieldBuilder022.Append(uint64(l))
}
func (inst *InEntityPersiststateTableSectionStringInAttr) handleNonScalarSupportColumns() {
	var l int
	var _ = l
}
func (inst *InEntityPersiststateTableSectionStringInAttr) applyAmbientMemberships() {
	if inst.state != runtime.EntityStateInAttribute {
		return
	}
	for _, v := range inst.parent.parent.ambientHighCardRef {
		inst.AddMembershipHighCardRefP(v)
	}
}
func (inst *InEntityPersiststateTableSectionStringInAttr) completeAttribute() {
	inst.handleMembershipSupportColumns()
	inst.handleNonScalarSupportColumns()
}
func (inst *InEntityPersiststateTableSectionStringInAttr) EndSection() *InEntityPersiststateTable {
	inst.applyAmbientMemberships()
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInitial
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent.parent
	}

	inst.completeAttribute()
	inst.parent.EndSection()
	return inst.parent.parent
}
func (inst *InEntityPersiststateTableSectionStringInAttr) EndAttribute() *InEntityPersiststateTableSectionString {
	inst.applyAmbientMemberships()
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInSection
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent
	}

	inst.completeAttribute()
	inst.parent.endAttribute()
	return inst.parent
}
func (inst *InEntityPersiststateTableSectionStringInAttr) EndAttributeP() {
	inst.EndAttribute()
}

func (inst *InEntityPersiststateTableSectionStringInAttr) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityPersiststateTableSectionStringInAttr) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}

type InEntityPersiststateTableSectionSymbol struct {
	errs                  []error
	inAttr                *InEntityPersiststateTableSectionSymbolInAttr
	state                 runtime.EntityStateE
	attributeCount        int
	parent                *InEntityPersiststateTable
	scalarFieldBuilder003 *array.StringBuilder
	scalarListBuilder003  *array.ListBuilder
}

func NewInEntityPersiststateTableSectionSymbol(builder *array.RecordBuilder, parent *InEntityPersiststateTable) (inst *InEntityPersiststateTableSectionSymbol) {
	inst = &InEntityPersiststateTableSectionSymbol{}
	inAttr := NewInEntityPersiststateTableSectionSymbolInAttr(builder, inst)
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.inAttr = inAttr
	inst.parent = parent
	inst.scalarFieldBuilder003 = builder.Field(3).(*array.ListBuilder).ValueBuilder().(*array.StringBuilder)
	inst.scalarListBuilder003 = builder.Field(3).(*array.ListBuilder)

	return inst
}
func (inst *InEntityPersiststateTableSectionSymbol) endAttribute() {
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInSection
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
}
func (inst *InEntityPersiststateTableSectionSymbol) BeginAttribute(value3 string) *InEntityPersiststateTableSectionSymbolInAttr {
	switch inst.state {
	case runtime.EntityStateInSection:
		inst.state = runtime.EntityStateInAttribute
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.inAttr
	}
	inst.scalarFieldBuilder003.Append(value3)
	inst.attributeCount++

	inst.inAttr.state = inst.state
	return inst.inAttr
}

type InEntityPersiststateTableSectionSymbolAttr struct {
	Value string
}

func (inst *InEntityPersiststateTableSectionSymbol) Add(attr InEntityPersiststateTableSectionSymbolAttr) *InEntityPersiststateTableSectionSymbolInAttr {
	a := inst.BeginAttribute(attr.Value)
	return a
}
func (inst *InEntityPersiststateTableSectionSymbol) CheckErrors() (err error) {
	err = eh.CheckErrors(slices.Concat(inst.errs, inst.inAttr.errs))
	return
}
func (inst *InEntityPersiststateTableSectionSymbol) EndSection() *InEntityPersiststateTable {
	switch inst.state {
	case runtime.EntityStateInSection:
		inst.state = runtime.EntityStateInitial
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent
	}

	return inst.parent
}

func (inst *InEntityPersiststateTableSectionSymbol) beginSection() {
	inst.state = runtime.EntityStateInSection
	inst.attributeCount = 0
	inst.inAttr.beginAttribute()
}

func (inst *InEntityPersiststateTableSectionSymbol) resetSection() {
	inst.clearErrors()
	inst.inAttr.clearErrors()
	inst.attributeCount = 0
	inst.state = runtime.EntityStateInitial
}

func (inst *InEntityPersiststateTableSectionSymbol) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityPersiststateTableSectionSymbol) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}

type InEntityPersiststateTableSectionSymbolInAttr struct {
	errs                             []error
	state                            runtime.EntityStateE
	parent                           *InEntityPersiststateTableSectionSymbol
	scalarFieldBuilder003            *array.StringBuilder
	scalarListBuilder003             *array.ListBuilder
	membershipFieldBuilder004        *array.Uint64Builder
	membershipListBuilder004         *array.ListBuilder
	membershipFieldBuilder005        *array.Uint64Builder
	membershipListBuilder005         *array.ListBuilder
	membershipFieldBuilder006        *array.BinaryBuilder
	membershipListBuilder006         *array.ListBuilder
	membershipFieldBuilder007        *array.Uint64Builder
	membershipListBuilder007         *array.ListBuilder
	membershipFieldBuilder008        *array.BinaryBuilder
	membershipListBuilder008         *array.ListBuilder
	membershipSupportFieldBuilder009 *array.Uint64Builder
	membershipSupportListBuilder009  *array.ListBuilder
	membershipSupportFieldBuilder010 *array.Uint64Builder
	membershipSupportListBuilder010  *array.ListBuilder
	membershipSupportFieldBuilder011 *array.Uint64Builder
	membershipSupportListBuilder011  *array.ListBuilder
	membershipSupportFieldBuilder012 *array.Uint64Builder
	membershipSupportListBuilder012  *array.ListBuilder

	membershipContainerLength004 int

	membershipContainerLength005 int

	membershipContainerLength006 int

	membershipContainerLength007 int

	membershipContainerLength008 int
}

func NewInEntityPersiststateTableSectionSymbolInAttr(builder *array.RecordBuilder, parent *InEntityPersiststateTableSectionSymbol) (inst *InEntityPersiststateTableSectionSymbolInAttr) {
	inst = &InEntityPersiststateTableSectionSymbolInAttr{}
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.parent = parent
	inst.scalarFieldBuilder003 = builder.Field(3).(*array.ListBuilder).ValueBuilder().(*array.StringBuilder)
	inst.scalarListBuilder003 = builder.Field(3).(*array.ListBuilder)
	inst.membershipFieldBuilder004 = builder.Field(4).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder004 = builder.Field(4).(*array.ListBuilder)
	inst.membershipFieldBuilder005 = builder.Field(5).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder005 = builder.Field(5).(*array.ListBuilder)
	inst.membershipFieldBuilder006 = builder.Field(6).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.membershipListBuilder006 = builder.Field(6).(*array.ListBuilder)
	inst.membershipFieldBuilder007 = builder.Field(7).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder007 = builder.Field(7).(*array.ListBuilder)
	inst.membershipFieldBuilder008 = builder.Field(8).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.membershipListBuilder008 = builder.Field(8).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder009 = builder.Field(9).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder009 = builder.Field(9).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder010 = builder.Field(10).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder010 = builder.Field(10).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder011 = builder.Field(11).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder011 = builder.Field(11).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder012 = builder.Field(12).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder012 = builder.Field(12).(*array.ListBuilder)

	return inst
}
func (inst *InEntityPersiststateTableSectionSymbolInAttr) beginAttribute() {
	inst.membershipListBuilder004.Append(true)
	inst.membershipListBuilder005.Append(true)
	inst.membershipListBuilder006.Append(true)
	inst.membershipListBuilder007.Append(true)
	inst.membershipListBuilder008.Append(true)
	inst.membershipContainerLength004 = 0
	inst.membershipContainerLength005 = 0
	inst.membershipContainerLength006 = 0
	inst.membershipContainerLength007 = 0
	inst.membershipContainerLength008 = 0
	inst.scalarListBuilder003.Append(true)
	inst.membershipSupportListBuilder009.Append(true)
	inst.membershipSupportListBuilder010.Append(true)
	inst.membershipSupportListBuilder011.Append(true)
	inst.membershipSupportListBuilder012.Append(true)
	inst.state = runtime.EntityStateInSection
	inst.clearErrors()
}
func (inst *InEntityPersiststateTableSectionSymbolInAttr) AddMembershipHighCardRef(hr4 uint64) *InEntityPersiststateTableSectionSymbolInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder004.Append(hr4)
	inst.membershipContainerLength004++
	return inst
}
func (inst *InEntityPersiststateTableSectionSymbolInAttr) AddMembershipHighCardRefP(hr4 uint64) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder004.Append(hr4)
	inst.membershipContainerLength004++
	return
}
func (inst *InEntityPersiststateTableSectionSymbolInAttr) AddMembershipLowCardRef(lr5 uint64) *InEntityPersiststateTableSectionSymbolInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder005.Append(lr5)
	inst.membershipContainerLength005++
	return inst
}
func (inst *InEntityPersiststateTableSectionSymbolInAttr) AddMembershipLowCardRefP(lr5 uint64) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder005.Append(lr5)
	inst.membershipContainerLength005++
	return
}
func (inst *InEntityPersiststateTableSectionSymbolInAttr) AddMembershipLowCardVerbatim(lv6 []byte) *InEntityPersiststateTableSectionSymbolInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder006.Append(lv6)
	inst.membershipContainerLength006++
	return inst
}
func (inst *InEntityPersiststateTableSectionSymbolInAttr) AddMembershipLowCardVerbatimP(lv6 []byte) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder006.Append(lv6)
	inst.membershipContainerLength006++
	return
}
func (inst *InEntityPersiststateTableSectionSymbolInAttr) AddMembershipMixedLowCardRef(lmr7 uint64, mrhp8 []byte) *InEntityPersiststateTableSectionSymbolInAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder007.Append(lmr7)
	inst.membershipFieldBuilder008.Append(mrhp8)
	inst.membershipContainerLength007++
	inst.membershipContainerLength008++
	return inst
}
func (inst *InEntityPersiststateTableSectionSymbolInAttr) AddMembershipMixedLowCardRefP(lmr7 uint64, mrhp8 []byte) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder007.Append(lmr7)
	inst.membershipFieldBuilder008.Append(mrhp8)
	inst.membershipContainerLength007++
	inst.membershipContainerLength008++
	return
}
func (inst *InEntityPersiststateTableSectionSymbolInAttr) handleMembershipSupportColumns() {
	var l int
	var _ = l
	l = inst.membershipContainerLength004
	inst.membershipContainerLength004 = 0
	inst.membershipSupportFieldBuilder009.Append(uint64(l))
	l = inst.membershipContainerLength005
	inst.membershipContainerLength005 = 0
	inst.membershipSupportFieldBuilder010.Append(uint64(l))
	l = inst.membershipContainerLength006
	inst.membershipContainerLength006 = 0
	inst.membershipSupportFieldBuilder011.Append(uint64(l))
	l = inst.membershipContainerLength007
	inst.membershipContainerLength007 = 0
	inst.membershipSupportFieldBuilder012.Append(uint64(l))
}
func (inst *InEntityPersiststateTableSectionSymbolInAttr) handleNonScalarSupportColumns() {
	var l int
	var _ = l
}
func (inst *InEntityPersiststateTableSectionSymbolInAttr) applyAmbientMemberships() {
	if inst.state != runtime.EntityStateInAttribute {
		return
	}
	for _, v := range inst.parent.parent.ambientHighCardRef {
		inst.AddMembershipHighCardRefP(v)
	}
}
func (inst *InEntityPersiststateTableSectionSymbolInAttr) completeAttribute() {
	inst.handleMembershipSupportColumns()
	inst.handleNonScalarSupportColumns()
}
func (inst *InEntityPersiststateTableSectionSymbolInAttr) EndSection() *InEntityPersiststateTable {
	inst.applyAmbientMemberships()
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInitial
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent.parent
	}

	inst.completeAttribute()
	inst.parent.EndSection()
	return inst.parent.parent
}
func (inst *InEntityPersiststateTableSectionSymbolInAttr) EndAttribute() *InEntityPersiststateTableSectionSymbol {
	inst.applyAmbientMemberships()
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInSection
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent
	}

	inst.completeAttribute()
	inst.parent.endAttribute()
	return inst.parent
}
func (inst *InEntityPersiststateTableSectionSymbolInAttr) EndAttributeP() {
	inst.EndAttribute()
}

func (inst *InEntityPersiststateTableSectionSymbolInAttr) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityPersiststateTableSectionSymbolInAttr) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}

type InEntityPersiststateTableSectionU64 struct {
	errs                  []error
	inAttr                *InEntityPersiststateTableSectionU64InAttr
	state                 runtime.EntityStateE
	attributeCount        int
	parent                *InEntityPersiststateTable
	scalarFieldBuilder033 *array.Uint64Builder
	scalarListBuilder033  *array.ListBuilder
}

func NewInEntityPersiststateTableSectionU64(builder *array.RecordBuilder, parent *InEntityPersiststateTable) (inst *InEntityPersiststateTableSectionU64) {
	inst = &InEntityPersiststateTableSectionU64{}
	inAttr := NewInEntityPersiststateTableSectionU64InAttr(builder, inst)
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.inAttr = inAttr
	inst.parent = parent
	inst.scalarFieldBuilder033 = builder.Field(33).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.scalarListBuilder033 = builder.Field(33).(*array.ListBuilder)

	return inst
}
func (inst *InEntityPersiststateTableSectionU64) endAttribute() {
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInSection
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
}
func (inst *InEntityPersiststateTableSectionU64) BeginAttribute(value33 uint64) *InEntityPersiststateTableSectionU64InAttr {
	switch inst.state {
	case runtime.EntityStateInSection:
		inst.state = runtime.EntityStateInAttribute
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.inAttr
	}
	inst.scalarFieldBuilder033.Append(value33)
	inst.attributeCount++

	inst.inAttr.state = inst.state
	return inst.inAttr
}

type InEntityPersiststateTableSectionU64Attr struct {
	Value uint64
}

func (inst *InEntityPersiststateTableSectionU64) Add(attr InEntityPersiststateTableSectionU64Attr) *InEntityPersiststateTableSectionU64InAttr {
	a := inst.BeginAttribute(attr.Value)
	return a
}
func (inst *InEntityPersiststateTableSectionU64) CheckErrors() (err error) {
	err = eh.CheckErrors(slices.Concat(inst.errs, inst.inAttr.errs))
	return
}
func (inst *InEntityPersiststateTableSectionU64) EndSection() *InEntityPersiststateTable {
	switch inst.state {
	case runtime.EntityStateInSection:
		inst.state = runtime.EntityStateInitial
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent
	}

	return inst.parent
}

func (inst *InEntityPersiststateTableSectionU64) beginSection() {
	inst.state = runtime.EntityStateInSection
	inst.attributeCount = 0
	inst.inAttr.beginAttribute()
}

func (inst *InEntityPersiststateTableSectionU64) resetSection() {
	inst.clearErrors()
	inst.inAttr.clearErrors()
	inst.attributeCount = 0
	inst.state = runtime.EntityStateInitial
}

func (inst *InEntityPersiststateTableSectionU64) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityPersiststateTableSectionU64) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}

type InEntityPersiststateTableSectionU64InAttr struct {
	errs                             []error
	state                            runtime.EntityStateE
	parent                           *InEntityPersiststateTableSectionU64
	scalarFieldBuilder033            *array.Uint64Builder
	scalarListBuilder033             *array.ListBuilder
	membershipFieldBuilder034        *array.Uint64Builder
	membershipListBuilder034         *array.ListBuilder
	membershipFieldBuilder035        *array.Uint64Builder
	membershipListBuilder035         *array.ListBuilder
	membershipFieldBuilder036        *array.BinaryBuilder
	membershipListBuilder036         *array.ListBuilder
	membershipFieldBuilder037        *array.Uint64Builder
	membershipListBuilder037         *array.ListBuilder
	membershipFieldBuilder038        *array.BinaryBuilder
	membershipListBuilder038         *array.ListBuilder
	membershipSupportFieldBuilder039 *array.Uint64Builder
	membershipSupportListBuilder039  *array.ListBuilder
	membershipSupportFieldBuilder040 *array.Uint64Builder
	membershipSupportListBuilder040  *array.ListBuilder
	membershipSupportFieldBuilder041 *array.Uint64Builder
	membershipSupportListBuilder041  *array.ListBuilder
	membershipSupportFieldBuilder042 *array.Uint64Builder
	membershipSupportListBuilder042  *array.ListBuilder

	membershipContainerLength034 int

	membershipContainerLength035 int

	membershipContainerLength036 int

	membershipContainerLength037 int

	membershipContainerLength038 int
}

func NewInEntityPersiststateTableSectionU64InAttr(builder *array.RecordBuilder, parent *InEntityPersiststateTableSectionU64) (inst *InEntityPersiststateTableSectionU64InAttr) {
	inst = &InEntityPersiststateTableSectionU64InAttr{}
	inst.errs = make([]error, 0, 8)
	inst.state = runtime.EntityStateInitial
	inst.parent = parent
	inst.scalarFieldBuilder033 = builder.Field(33).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.scalarListBuilder033 = builder.Field(33).(*array.ListBuilder)
	inst.membershipFieldBuilder034 = builder.Field(34).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder034 = builder.Field(34).(*array.ListBuilder)
	inst.membershipFieldBuilder035 = builder.Field(35).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder035 = builder.Field(35).(*array.ListBuilder)
	inst.membershipFieldBuilder036 = builder.Field(36).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.membershipListBuilder036 = builder.Field(36).(*array.ListBuilder)
	inst.membershipFieldBuilder037 = builder.Field(37).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipListBuilder037 = builder.Field(37).(*array.ListBuilder)
	inst.membershipFieldBuilder038 = builder.Field(38).(*array.ListBuilder).ValueBuilder().(*array.BinaryBuilder)
	inst.membershipListBuilder038 = builder.Field(38).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder039 = builder.Field(39).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder039 = builder.Field(39).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder040 = builder.Field(40).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder040 = builder.Field(40).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder041 = builder.Field(41).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder041 = builder.Field(41).(*array.ListBuilder)
	inst.membershipSupportFieldBuilder042 = builder.Field(42).(*array.ListBuilder).ValueBuilder().(*array.Uint64Builder)
	inst.membershipSupportListBuilder042 = builder.Field(42).(*array.ListBuilder)

	return inst
}
func (inst *InEntityPersiststateTableSectionU64InAttr) beginAttribute() {
	inst.membershipListBuilder034.Append(true)
	inst.membershipListBuilder035.Append(true)
	inst.membershipListBuilder036.Append(true)
	inst.membershipListBuilder037.Append(true)
	inst.membershipListBuilder038.Append(true)
	inst.membershipContainerLength034 = 0
	inst.membershipContainerLength035 = 0
	inst.membershipContainerLength036 = 0
	inst.membershipContainerLength037 = 0
	inst.membershipContainerLength038 = 0
	inst.scalarListBuilder033.Append(true)
	inst.membershipSupportListBuilder039.Append(true)
	inst.membershipSupportListBuilder040.Append(true)
	inst.membershipSupportListBuilder041.Append(true)
	inst.membershipSupportListBuilder042.Append(true)
	inst.state = runtime.EntityStateInSection
	inst.clearErrors()
}
func (inst *InEntityPersiststateTableSectionU64InAttr) AddMembershipHighCardRef(hr34 uint64) *InEntityPersiststateTableSectionU64InAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder034.Append(hr34)
	inst.membershipContainerLength034++
	return inst
}
func (inst *InEntityPersiststateTableSectionU64InAttr) AddMembershipHighCardRefP(hr34 uint64) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder034.Append(hr34)
	inst.membershipContainerLength034++
	return
}
func (inst *InEntityPersiststateTableSectionU64InAttr) AddMembershipLowCardRef(lr35 uint64) *InEntityPersiststateTableSectionU64InAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder035.Append(lr35)
	inst.membershipContainerLength035++
	return inst
}
func (inst *InEntityPersiststateTableSectionU64InAttr) AddMembershipLowCardRefP(lr35 uint64) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder035.Append(lr35)
	inst.membershipContainerLength035++
	return
}
func (inst *InEntityPersiststateTableSectionU64InAttr) AddMembershipLowCardVerbatim(lv36 []byte) *InEntityPersiststateTableSectionU64InAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder036.Append(lv36)
	inst.membershipContainerLength036++
	return inst
}
func (inst *InEntityPersiststateTableSectionU64InAttr) AddMembershipLowCardVerbatimP(lv36 []byte) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder036.Append(lv36)
	inst.membershipContainerLength036++
	return
}
func (inst *InEntityPersiststateTableSectionU64InAttr) AddMembershipMixedLowCardRef(lmr37 uint64, mrhp38 []byte) *InEntityPersiststateTableSectionU64InAttr {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst
	}
	inst.membershipFieldBuilder037.Append(lmr37)
	inst.membershipFieldBuilder038.Append(mrhp38)
	inst.membershipContainerLength037++
	inst.membershipContainerLength038++
	return inst
}
func (inst *InEntityPersiststateTableSectionU64InAttr) AddMembershipMixedLowCardRefP(lmr37 uint64, mrhp38 []byte) {
	if inst.state != runtime.EntityStateInAttribute {
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return
	}
	inst.membershipFieldBuilder037.Append(lmr37)
	inst.membershipFieldBuilder038.Append(mrhp38)
	inst.membershipContainerLength037++
	inst.membershipContainerLength038++
	return
}
func (inst *InEntityPersiststateTableSectionU64InAttr) handleMembershipSupportColumns() {
	var l int
	var _ = l
	l = inst.membershipContainerLength034
	inst.membershipContainerLength034 = 0
	inst.membershipSupportFieldBuilder039.Append(uint64(l))
	l = inst.membershipContainerLength035
	inst.membershipContainerLength035 = 0
	inst.membershipSupportFieldBuilder040.Append(uint64(l))
	l = inst.membershipContainerLength036
	inst.membershipContainerLength036 = 0
	inst.membershipSupportFieldBuilder041.Append(uint64(l))
	l = inst.membershipContainerLength037
	inst.membershipContainerLength037 = 0
	inst.membershipSupportFieldBuilder042.Append(uint64(l))
}
func (inst *InEntityPersiststateTableSectionU64InAttr) handleNonScalarSupportColumns() {
	var l int
	var _ = l
}
func (inst *InEntityPersiststateTableSectionU64InAttr) applyAmbientMemberships() {
	if inst.state != runtime.EntityStateInAttribute {
		return
	}
	for _, v := range inst.parent.parent.ambientHighCardRef {
		inst.AddMembershipHighCardRefP(v)
	}
}
func (inst *InEntityPersiststateTableSectionU64InAttr) completeAttribute() {
	inst.handleMembershipSupportColumns()
	inst.handleNonScalarSupportColumns()
}
func (inst *InEntityPersiststateTableSectionU64InAttr) EndSection() *InEntityPersiststateTable {
	inst.applyAmbientMemberships()
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInitial
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent.parent
	}

	inst.completeAttribute()
	inst.parent.EndSection()
	return inst.parent.parent
}
func (inst *InEntityPersiststateTableSectionU64InAttr) EndAttribute() *InEntityPersiststateTableSectionU64 {
	inst.applyAmbientMemberships()
	switch inst.state {
	case runtime.EntityStateInAttribute:
		inst.state = runtime.EntityStateInSection
		break
	default:
		inst.AppendError(runtime.ErrInvalidStateTransition)
		return inst.parent
	}

	inst.completeAttribute()
	inst.parent.endAttribute()
	return inst.parent
}
func (inst *InEntityPersiststateTableSectionU64InAttr) EndAttributeP() {
	inst.EndAttribute()
}

func (inst *InEntityPersiststateTableSectionU64InAttr) AppendError(err error) {
	inst.errs = eh.AppendError(inst.errs, err)
}
func (inst *InEntityPersiststateTableSectionU64InAttr) clearErrors() {
	inst.errs = eh.ClearErrors(inst.errs)
}
