// Code generated by boxer/public/semistructured/leeway/marshall/go/marshallgen — DO NOT EDIT.

package sysmfacts

import (
	"iter"

	"github.com/stergiotis/boxer/public/observability/eh/eb"
	dmlruntime "github.com/stergiotis/boxer/public/semistructured/leeway/dml/runtime"
	raruntime "github.com/stergiotis/boxer/public/semistructured/leeway/readaccess/runtime"
)

// --- Caller-assigned membership ids (registry-stable target). ---

const (
	kindSysmKindCpuInfo     uint64 = 2305843022098595841
	kindSysmCpuInfoHost     uint64 = 2305843022098595844
	kindSysmCpuModelName    uint64 = 2305843022098595854
	kindSysmCpuLogicalCores uint64 = 2305843022098595855
)

// sysCpuInfoSymbolAttrI is the InAttr-side view of the symbol section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type sysCpuInfoSymbolAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// sysCpuInfoSymbolSecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type sysCpuInfoSymbolSecI[Attr any, Ent any] interface {
	BeginAttribute(value string) Attr
	EndSection() Ent
}

// sysCpuInfoI32ArrayAttrI is the InAttr-side view of the i32Array section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type sysCpuInfoI32ArrayAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// sysCpuInfoI32ArraySecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type sysCpuInfoI32ArraySecI[Attr any, Ent any] interface {
	BeginAttributeSingle(value int32) Attr
	EndSection() Ent
}

// sysCpuInfoEntityI is the entity-builder surface sysCpuInfoAddSections drives.
// It always lists the per-section getters; the entity-frame methods
// (BeginEntity / plain setters / CommitEntity) are added only for the
// full codec's BuildEntities. AddSections stacks sections onto a frame
// the caller already owns, so it needs none of them — which lets a
// store drive it with a builder whose frame control is unexported
// (ADR-0100 SD6). Ent is the builder pointer.
type sysCpuInfoEntityI[
	SymbolAttr sysCpuInfoSymbolAttrI,
	SymbolSec sysCpuInfoSymbolSecI[SymbolAttr, Ent],
	I32ArrayAttr sysCpuInfoI32ArrayAttrI,
	I32ArraySec sysCpuInfoI32ArraySecI[I32ArrayAttr, Ent],
	Ent any,
] interface {
	GetSectionSymbol() SymbolSec
	GetSectionI32Array() I32ArraySec
}

// sysCpuInfoAddSections contributes this kind's tagged sections to the OPEN
// entity on dml — the BuildEntities body without the entity frame.
// The caller owns BeginEntity / plain setters / CommitEntity.
func sysCpuInfoAddSections[
	SymbolAttr sysCpuInfoSymbolAttrI,
	SymbolSec sysCpuInfoSymbolSecI[SymbolAttr, Ent],
	I32ArrayAttr sysCpuInfoI32ArrayAttrI,
	I32ArraySec sysCpuInfoI32ArraySecI[I32ArrayAttr, Ent],
	Ent any,
	DML sysCpuInfoEntityI[
		SymbolAttr, SymbolSec,
		I32ArrayAttr, I32ArraySec,
		Ent,
	],
](dml DML, row SysCpuInfo) (err error) {
	// --- symbol. ---
	symbolSec := dml.GetSectionSymbol()
	symbolSecAttr_Kind := symbolSec.BeginAttribute(row.Kind)
	symbolSecAttr_Kind.AddMembershipLowCardRefP(kindSysmKindCpuInfo)
	symbolSecAttr_Kind.EndAttributeP()
	symbolSecAttr_Host := symbolSec.BeginAttribute(row.Host)
	symbolSecAttr_Host.AddMembershipLowCardRefP(kindSysmCpuInfoHost)
	symbolSecAttr_Host.EndAttributeP()
	symbolSecAttr_ModelName := symbolSec.BeginAttribute(row.ModelName)
	symbolSecAttr_ModelName.AddMembershipLowCardRefP(kindSysmCpuModelName)
	symbolSecAttr_ModelName.EndAttributeP()
	symbolSec.EndSection()
	// --- i32Array. ---
	i32ArraySec := dml.GetSectionI32Array()
	i32ArraySecAttr_LogicalCores := i32ArraySec.BeginAttributeSingle(row.LogicalCores)
	i32ArraySecAttr_LogicalCores.AddMembershipLowCardRefP(kindSysmCpuLogicalCores)
	i32ArraySecAttr_LogicalCores.EndAttributeP()
	i32ArraySec.EndSection()
	return
}

// sysCpuInfoSymbolAttrsReadI is the Attributes-side view of the symbol section.
type sysCpuInfoSymbolAttrsReadI interface {
	GetAttrValueValue(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) string
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// sysCpuInfoSymbolMembsReadI is the Memberships-side view of the symbol section.
type sysCpuInfoSymbolMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// sysCpuInfoI32ArrayAttrsReadI is the Attributes-side view of the i32Array section.
type sysCpuInfoI32ArrayAttrsReadI interface {
	GetAttrValueSingle(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) (int32, error)
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// sysCpuInfoI32ArrayMembsReadI is the Memberships-side view of the i32Array section.
type sysCpuInfoI32ArrayMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// sysCpuInfoReadRow reads row i as one optional SysCpuInfo component: presence-
// gated (a row carrying none of the kind's memberships yields
// present=false), membership-matched. A slot carrying more
// attributes than this kind's shape admits is an error, for every
// shape including containers. Plain-
// bound fields stay zero — the caller owns the envelope. The
// Attrs/Membs readers bind by type inference at the call site, as
// with FillFromArrow.
func sysCpuInfoReadRow[
	SymbolAttrs sysCpuInfoSymbolAttrsReadI,
	SymbolMembs sysCpuInfoSymbolMembsReadI,
	I32ArrayAttrs sysCpuInfoI32ArrayAttrsReadI,
	I32ArrayMembs sysCpuInfoI32ArrayMembsReadI,
](
	i int,
	symbolAttrs SymbolAttrs,
	symbolMembs SymbolMembs,
	i32ArrayAttrs I32ArrayAttrs,
	i32ArrayMembs I32ArrayMembs,
) (row SysCpuInfo, present bool, err error) {
	// --- symbol. ---
	var symbolKindVal string
	var symbolKindCount int
	var symbolKindLastAttr int64
	var symbolHostVal string
	var symbolHostCount int
	var symbolHostLastAttr int64
	var symbolModelNameVal string
	var symbolModelNameCount int
	var symbolModelNameLastAttr int64
	nsymbol := symbolAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nsymbol; attrJ++ {
		for membID := range symbolMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindSysmKindCpuInfo:
				if symbolKindLastAttr != attrJ+1 {
					symbolKindLastAttr = attrJ + 1
					symbolKindCount++
				}
				val := symbolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				symbolKindVal = val
			case kindSysmCpuInfoHost:
				if symbolHostLastAttr != attrJ+1 {
					symbolHostLastAttr = attrJ + 1
					symbolHostCount++
				}
				val := symbolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				symbolHostVal = val
			case kindSysmCpuModelName:
				if symbolModelNameLastAttr != attrJ+1 {
					symbolModelNameLastAttr = attrJ + 1
					symbolModelNameCount++
				}
				val := symbolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				symbolModelNameVal = val
			}
		}
	}
	if symbolKindCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbol").Str("membership", "sysmKindCpuInfo").Int("got", symbolKindCount).Errorf("slot symbol@sysmKindCpuInfo (field Kind) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolKindCount)
		return
	}
	if symbolKindCount == 1 {
		row.Kind = symbolKindVal
		present = true
	}
	if symbolHostCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbol").Str("membership", "sysmCpuInfoHost").Int("got", symbolHostCount).Errorf("slot symbol@sysmCpuInfoHost (field Host) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolHostCount)
		return
	}
	if symbolHostCount == 1 {
		row.Host = symbolHostVal
		present = true
	}
	if symbolModelNameCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbol").Str("membership", "sysmCpuModelName").Int("got", symbolModelNameCount).Errorf("slot symbol@sysmCpuModelName (field ModelName) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolModelNameCount)
		return
	}
	if symbolModelNameCount == 1 {
		row.ModelName = symbolModelNameVal
		present = true
	}
	// --- i32Array. ---
	var i32ArrayLogicalCoresVal int32
	var i32ArrayLogicalCoresCount int
	var i32ArrayLogicalCoresLastAttr int64
	ni32Array := i32ArrayAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < ni32Array; attrJ++ {
		for membID := range i32ArrayMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindSysmCpuLogicalCores:
				if i32ArrayLogicalCoresLastAttr != attrJ+1 {
					i32ArrayLogicalCoresLastAttr = attrJ + 1
					i32ArrayLogicalCoresCount++
				}
				val, valErr := i32ArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "i32Array").Str("membership", "sysmCpuLogicalCores").Str("field", "LogicalCores").Errorf("slot i32Array@sysmCpuLogicalCores (field LogicalCores) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				i32ArrayLogicalCoresVal = val
			}
		}
	}
	if i32ArrayLogicalCoresCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "i32Array").Str("membership", "sysmCpuLogicalCores").Int("got", i32ArrayLogicalCoresCount).Errorf("slot i32Array@sysmCpuLogicalCores (field LogicalCores) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", i32ArrayLogicalCoresCount)
		return
	}
	if i32ArrayLogicalCoresCount == 1 {
		row.LogicalCores = i32ArrayLogicalCoresVal
		present = true
	}
	return
}
