// Code generated by boxer/public/semistructured/leeway/marshall/go/marshallgen — DO NOT EDIT.

package llmfacts

import (
	"iter"

	"github.com/stergiotis/boxer/public/observability/eh/eb"
	dmlruntime "github.com/stergiotis/boxer/public/semistructured/leeway/dml/runtime"
	raruntime "github.com/stergiotis/boxer/public/semistructured/leeway/readaccess/runtime"
)

// --- Caller-assigned membership ids (registry-stable target). ---

const (
	kindRuntimeKindLlmCall     uint64 = 9223372049739677798
	kindLlmCallId              uint64 = 9223372049739677799
	kindLlmCallApp             uint64 = 9223372049739677800
	kindLlmCallInstance        uint64 = 9223372049739677801
	kindLlmCallPurpose         uint64 = 9223372049739677802
	kindLlmCallSensitivity     uint64 = 9223372049739677803
	kindLlmCallModel           uint64 = 9223372049739677804
	kindLlmCallEndpointHost    uint64 = 9223372049739677805
	kindLlmCallMessages        uint64 = 9223372049739677806
	kindLlmCallTools           uint64 = 9223372049739677807
	kindLlmCallPromptBytes     uint64 = 9223372049739677808
	kindLlmCallCompletionBytes uint64 = 9223372049739677809
	kindLlmCallInputTokens     uint64 = 9223372049739677810
	kindLlmCallOutputTokens    uint64 = 9223372049739677811
	kindLlmCallToolCalls       uint64 = 9223372049739677812
	kindLlmCallFinishReason    uint64 = 9223372049739677813
	kindLlmCallElapsedMs       uint64 = 9223372049739677814
	kindLlmCallIncomplete      uint64 = 9223372049739677815
	kindLlmCallRefused         uint64 = 9223372049739677816
	kindLlmCallError           uint64 = 9223372049739677817
)

// llmCallSymbolAttrI is the InAttr-side view of the symbol section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type llmCallSymbolAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// llmCallSymbolSecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type llmCallSymbolSecI[Attr any, Ent any] interface {
	BeginAttribute(value string) Attr
	EndSection() Ent
}

// llmCallU64ArrayAttrI is the InAttr-side view of the u64Array section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type llmCallU64ArrayAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// llmCallU64ArraySecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type llmCallU64ArraySecI[Attr any, Ent any] interface {
	BeginAttributeSingle(value uint64) Attr
	EndSection() Ent
}

// llmCallU32ArrayAttrI is the InAttr-side view of the u32Array section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type llmCallU32ArrayAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// llmCallU32ArraySecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type llmCallU32ArraySecI[Attr any, Ent any] interface {
	BeginAttributeSingle(value uint32) Attr
	EndSection() Ent
}

// llmCallBoolAttrI is the InAttr-side view of the bool section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type llmCallBoolAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// llmCallBoolSecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type llmCallBoolSecI[Attr any, Ent any] interface {
	BeginAttribute(value bool) Attr
	EndSection() Ent
}

// llmCallStringArrayAttrI is the InAttr-side view of the stringArray section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type llmCallStringArrayAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	AddToContainerP(value string)
	EndAttributeP()
}

// llmCallStringArraySecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type llmCallStringArraySecI[Attr any, Ent any] interface {
	BeginAttribute() Attr
	EndSection() Ent
}

// llmCallEntityI is the entity-builder surface llmCallAddSections drives.
// It always lists the per-section getters; the entity-frame methods
// (BeginEntity / plain setters / CommitEntity) are added only for the
// full codec's BuildEntities. AddSections stacks sections onto a frame
// the caller already owns, so it needs none of them — which lets a
// store drive it with a builder whose frame control is unexported
// (ADR-0100 SD6). Ent is the builder pointer.
type llmCallEntityI[
	SymbolAttr llmCallSymbolAttrI,
	SymbolSec llmCallSymbolSecI[SymbolAttr, Ent],
	U64ArrayAttr llmCallU64ArrayAttrI,
	U64ArraySec llmCallU64ArraySecI[U64ArrayAttr, Ent],
	U32ArrayAttr llmCallU32ArrayAttrI,
	U32ArraySec llmCallU32ArraySecI[U32ArrayAttr, Ent],
	BoolAttr llmCallBoolAttrI,
	BoolSec llmCallBoolSecI[BoolAttr, Ent],
	StringArrayAttr llmCallStringArrayAttrI,
	StringArraySec llmCallStringArraySecI[StringArrayAttr, Ent],
	Ent any,
] interface {
	GetSectionSymbol() SymbolSec
	GetSectionU64Array() U64ArraySec
	GetSectionU32Array() U32ArraySec
	GetSectionBool() BoolSec
	GetSectionStringArray() StringArraySec
}

// llmCallEmitSectionSymbol writes this kind's symbol attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func llmCallEmitSectionSymbol[
	SymbolAttr llmCallSymbolAttrI,
	SymbolSec llmCallSymbolSecI[SymbolAttr, Ent],
	Ent any,
](symbolSec SymbolSec, row LlmCall) (err error) {
	symbolSecAttr_Kind := symbolSec.BeginAttribute(row.Kind)
	symbolSecAttr_Kind.AddMembershipLowCardRefP(kindRuntimeKindLlmCall)
	symbolSecAttr_Kind.EndAttributeP()
	symbolSecAttr_CallId := symbolSec.BeginAttribute(row.CallId)
	symbolSecAttr_CallId.AddMembershipLowCardRefP(kindLlmCallId)
	symbolSecAttr_CallId.EndAttributeP()
	symbolSecAttr_App := symbolSec.BeginAttribute(row.App)
	symbolSecAttr_App.AddMembershipLowCardRefP(kindLlmCallApp)
	symbolSecAttr_App.EndAttributeP()
	symbolSecAttr_Purpose := symbolSec.BeginAttribute(row.Purpose)
	symbolSecAttr_Purpose.AddMembershipLowCardRefP(kindLlmCallPurpose)
	symbolSecAttr_Purpose.EndAttributeP()
	symbolSecAttr_Sensitivity := symbolSec.BeginAttribute(row.Sensitivity)
	symbolSecAttr_Sensitivity.AddMembershipLowCardRefP(kindLlmCallSensitivity)
	symbolSecAttr_Sensitivity.EndAttributeP()
	symbolSecAttr_Model := symbolSec.BeginAttribute(row.Model)
	symbolSecAttr_Model.AddMembershipLowCardRefP(kindLlmCallModel)
	symbolSecAttr_Model.EndAttributeP()
	symbolSecAttr_EndpointHost := symbolSec.BeginAttribute(row.EndpointHost)
	symbolSecAttr_EndpointHost.AddMembershipLowCardRefP(kindLlmCallEndpointHost)
	symbolSecAttr_EndpointHost.EndAttributeP()
	symbolSecAttr_FinishReason := symbolSec.BeginAttribute(row.FinishReason)
	symbolSecAttr_FinishReason.AddMembershipLowCardRefP(kindLlmCallFinishReason)
	symbolSecAttr_FinishReason.EndAttributeP()
	return
}

// llmCallEmitSectionU64Array writes this kind's u64Array attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func llmCallEmitSectionU64Array[
	U64ArrayAttr llmCallU64ArrayAttrI,
	U64ArraySec llmCallU64ArraySecI[U64ArrayAttr, Ent],
	Ent any,
](u64ArraySec U64ArraySec, row LlmCall) (err error) {
	u64ArraySecAttr_Instance := u64ArraySec.BeginAttributeSingle(row.Instance)
	u64ArraySecAttr_Instance.AddMembershipLowCardRefP(kindLlmCallInstance)
	u64ArraySecAttr_Instance.EndAttributeP()
	u64ArraySecAttr_PromptBytes := u64ArraySec.BeginAttributeSingle(row.PromptBytes)
	u64ArraySecAttr_PromptBytes.AddMembershipLowCardRefP(kindLlmCallPromptBytes)
	u64ArraySecAttr_PromptBytes.EndAttributeP()
	u64ArraySecAttr_CompletionBytes := u64ArraySec.BeginAttributeSingle(row.CompletionBytes)
	u64ArraySecAttr_CompletionBytes.AddMembershipLowCardRefP(kindLlmCallCompletionBytes)
	u64ArraySecAttr_CompletionBytes.EndAttributeP()
	u64ArraySecAttr_ElapsedMs := u64ArraySec.BeginAttributeSingle(row.ElapsedMs)
	u64ArraySecAttr_ElapsedMs.AddMembershipLowCardRefP(kindLlmCallElapsedMs)
	u64ArraySecAttr_ElapsedMs.EndAttributeP()
	return
}

// llmCallEmitSectionU32Array writes this kind's u32Array attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func llmCallEmitSectionU32Array[
	U32ArrayAttr llmCallU32ArrayAttrI,
	U32ArraySec llmCallU32ArraySecI[U32ArrayAttr, Ent],
	Ent any,
](u32ArraySec U32ArraySec, row LlmCall) (err error) {
	u32ArraySecAttr_Messages := u32ArraySec.BeginAttributeSingle(row.Messages)
	u32ArraySecAttr_Messages.AddMembershipLowCardRefP(kindLlmCallMessages)
	u32ArraySecAttr_Messages.EndAttributeP()
	u32ArraySecAttr_Tools := u32ArraySec.BeginAttributeSingle(row.Tools)
	u32ArraySecAttr_Tools.AddMembershipLowCardRefP(kindLlmCallTools)
	u32ArraySecAttr_Tools.EndAttributeP()
	u32ArraySecAttr_InputTokens := u32ArraySec.BeginAttributeSingle(row.InputTokens)
	u32ArraySecAttr_InputTokens.AddMembershipLowCardRefP(kindLlmCallInputTokens)
	u32ArraySecAttr_InputTokens.EndAttributeP()
	u32ArraySecAttr_OutputTokens := u32ArraySec.BeginAttributeSingle(row.OutputTokens)
	u32ArraySecAttr_OutputTokens.AddMembershipLowCardRefP(kindLlmCallOutputTokens)
	u32ArraySecAttr_OutputTokens.EndAttributeP()
	u32ArraySecAttr_ToolCalls := u32ArraySec.BeginAttributeSingle(row.ToolCalls)
	u32ArraySecAttr_ToolCalls.AddMembershipLowCardRefP(kindLlmCallToolCalls)
	u32ArraySecAttr_ToolCalls.EndAttributeP()
	return
}

// llmCallEmitSectionBool writes this kind's bool attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func llmCallEmitSectionBool[
	BoolAttr llmCallBoolAttrI,
	BoolSec llmCallBoolSecI[BoolAttr, Ent],
	Ent any,
](boolSec BoolSec, row LlmCall) (err error) {
	boolSecAttr_Incomplete := boolSec.BeginAttribute(row.Incomplete)
	boolSecAttr_Incomplete.AddMembershipLowCardRefP(kindLlmCallIncomplete)
	boolSecAttr_Incomplete.EndAttributeP()
	boolSecAttr_Refused := boolSec.BeginAttribute(row.Refused)
	boolSecAttr_Refused.AddMembershipLowCardRefP(kindLlmCallRefused)
	boolSecAttr_Refused.EndAttributeP()
	return
}

// llmCallEmitSectionStringArray writes this kind's stringArray attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func llmCallEmitSectionStringArray[
	StringArrayAttr llmCallStringArrayAttrI,
	StringArraySec llmCallStringArraySecI[StringArrayAttr, Ent],
	Ent any,
](stringArraySec StringArraySec, row LlmCall) (err error) {
	if len(row.Error) > 0 {
		stringArraySecAttr_Error := stringArraySec.BeginAttribute()
		for _, v := range row.Error {
			stringArraySecAttr_Error.AddToContainerP(v)
		}
		stringArraySecAttr_Error.AddMembershipLowCardRefP(kindLlmCallError)
		stringArraySecAttr_Error.EndAttributeP()
	}
	return
}

// llmCallAddSections contributes this kind's tagged sections to the OPEN
// entity on dml — the BuildEntities body without the entity frame.
// The caller owns BeginEntity / plain setters / CommitEntity.
func llmCallAddSections[
	SymbolAttr llmCallSymbolAttrI,
	SymbolSec llmCallSymbolSecI[SymbolAttr, Ent],
	U64ArrayAttr llmCallU64ArrayAttrI,
	U64ArraySec llmCallU64ArraySecI[U64ArrayAttr, Ent],
	U32ArrayAttr llmCallU32ArrayAttrI,
	U32ArraySec llmCallU32ArraySecI[U32ArrayAttr, Ent],
	BoolAttr llmCallBoolAttrI,
	BoolSec llmCallBoolSecI[BoolAttr, Ent],
	StringArrayAttr llmCallStringArrayAttrI,
	StringArraySec llmCallStringArraySecI[StringArrayAttr, Ent],
	Ent any,
	DML llmCallEntityI[
		SymbolAttr, SymbolSec,
		U64ArrayAttr, U64ArraySec,
		U32ArrayAttr, U32ArraySec,
		BoolAttr, BoolSec,
		StringArrayAttr, StringArraySec,
		Ent,
	],
](dml DML, row LlmCall) (err error) {
	// --- symbol. ---
	symbolSec := dml.GetSectionSymbol()
	err = llmCallEmitSectionSymbol(symbolSec, row)
	if err != nil {
		return
	}
	symbolSec.EndSection()
	// --- u64Array. ---
	u64ArraySec := dml.GetSectionU64Array()
	err = llmCallEmitSectionU64Array(u64ArraySec, row)
	if err != nil {
		return
	}
	u64ArraySec.EndSection()
	// --- u32Array. ---
	u32ArraySec := dml.GetSectionU32Array()
	err = llmCallEmitSectionU32Array(u32ArraySec, row)
	if err != nil {
		return
	}
	u32ArraySec.EndSection()
	// --- bool. ---
	boolSec := dml.GetSectionBool()
	err = llmCallEmitSectionBool(boolSec, row)
	if err != nil {
		return
	}
	boolSec.EndSection()
	// --- stringArray. ---
	stringArraySec := dml.GetSectionStringArray()
	err = llmCallEmitSectionStringArray(stringArraySec, row)
	if err != nil {
		return
	}
	stringArraySec.EndSection()
	return
}

// llmCallSymbolAttrsReadI is the Attributes-side view of the symbol section.
type llmCallSymbolAttrsReadI interface {
	GetAttrValueValue(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) string
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// llmCallSymbolMembsReadI is the Memberships-side view of the symbol section.
type llmCallSymbolMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// llmCallU64ArrayAttrsReadI is the Attributes-side view of the u64Array section.
type llmCallU64ArrayAttrsReadI interface {
	GetAttrValueSingle(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) (uint64, error)
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// llmCallU64ArrayMembsReadI is the Memberships-side view of the u64Array section.
type llmCallU64ArrayMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// llmCallU32ArrayAttrsReadI is the Attributes-side view of the u32Array section.
type llmCallU32ArrayAttrsReadI interface {
	GetAttrValueSingle(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) (uint32, error)
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// llmCallU32ArrayMembsReadI is the Memberships-side view of the u32Array section.
type llmCallU32ArrayMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// llmCallBoolAttrsReadI is the Attributes-side view of the bool section.
type llmCallBoolAttrsReadI interface {
	GetAttrValueValue(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) bool
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// llmCallBoolMembsReadI is the Memberships-side view of the bool section.
type llmCallBoolMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// llmCallStringArrayAttrsReadI is the Attributes-side view of the stringArray section.
type llmCallStringArrayAttrsReadI interface {
	GetAttrValueValue(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[string]
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// llmCallStringArrayMembsReadI is the Memberships-side view of the stringArray section.
type llmCallStringArrayMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// llmCallReadRow reads row i as one optional LlmCall component: presence-
// gated (a row carrying none of the kind's memberships yields
// present=false), membership-matched. A slot carrying more
// attributes than this kind's shape admits is an error, for every
// shape including containers. Plain-
// bound fields stay zero — the caller owns the envelope. The
// Attrs/Membs readers bind by type inference at the call site, as
// with FillFromArrow.
func llmCallReadRow[
	SymbolAttrs llmCallSymbolAttrsReadI,
	SymbolMembs llmCallSymbolMembsReadI,
	U64ArrayAttrs llmCallU64ArrayAttrsReadI,
	U64ArrayMembs llmCallU64ArrayMembsReadI,
	U32ArrayAttrs llmCallU32ArrayAttrsReadI,
	U32ArrayMembs llmCallU32ArrayMembsReadI,
	BoolAttrs llmCallBoolAttrsReadI,
	BoolMembs llmCallBoolMembsReadI,
	StringArrayAttrs llmCallStringArrayAttrsReadI,
	StringArrayMembs llmCallStringArrayMembsReadI,
](
	i int,
	symbolAttrs SymbolAttrs,
	symbolMembs SymbolMembs,
	u64ArrayAttrs U64ArrayAttrs,
	u64ArrayMembs U64ArrayMembs,
	u32ArrayAttrs U32ArrayAttrs,
	u32ArrayMembs U32ArrayMembs,
	boolAttrs BoolAttrs,
	boolMembs BoolMembs,
	stringArrayAttrs StringArrayAttrs,
	stringArrayMembs StringArrayMembs,
) (row LlmCall, present bool, err error) {
	// --- symbol. ---
	var symbolKindVal string
	var symbolKindCount int
	var symbolKindLastAttr int64
	var symbolCallIdVal string
	var symbolCallIdCount int
	var symbolCallIdLastAttr int64
	var symbolAppVal string
	var symbolAppCount int
	var symbolAppLastAttr int64
	var symbolPurposeVal string
	var symbolPurposeCount int
	var symbolPurposeLastAttr int64
	var symbolSensitivityVal string
	var symbolSensitivityCount int
	var symbolSensitivityLastAttr int64
	var symbolModelVal string
	var symbolModelCount int
	var symbolModelLastAttr int64
	var symbolEndpointHostVal string
	var symbolEndpointHostCount int
	var symbolEndpointHostLastAttr int64
	var symbolFinishReasonVal string
	var symbolFinishReasonCount int
	var symbolFinishReasonLastAttr int64
	nsymbol := symbolAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nsymbol; attrJ++ {
		for membID := range symbolMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindRuntimeKindLlmCall:
				if symbolKindLastAttr != attrJ+1 {
					symbolKindLastAttr = attrJ + 1
					symbolKindCount++
				}
				val := symbolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				symbolKindVal = val
			case kindLlmCallId:
				if symbolCallIdLastAttr != attrJ+1 {
					symbolCallIdLastAttr = attrJ + 1
					symbolCallIdCount++
				}
				val := symbolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				symbolCallIdVal = val
			case kindLlmCallApp:
				if symbolAppLastAttr != attrJ+1 {
					symbolAppLastAttr = attrJ + 1
					symbolAppCount++
				}
				val := symbolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				symbolAppVal = val
			case kindLlmCallPurpose:
				if symbolPurposeLastAttr != attrJ+1 {
					symbolPurposeLastAttr = attrJ + 1
					symbolPurposeCount++
				}
				val := symbolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				symbolPurposeVal = val
			case kindLlmCallSensitivity:
				if symbolSensitivityLastAttr != attrJ+1 {
					symbolSensitivityLastAttr = attrJ + 1
					symbolSensitivityCount++
				}
				val := symbolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				symbolSensitivityVal = val
			case kindLlmCallModel:
				if symbolModelLastAttr != attrJ+1 {
					symbolModelLastAttr = attrJ + 1
					symbolModelCount++
				}
				val := symbolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				symbolModelVal = val
			case kindLlmCallEndpointHost:
				if symbolEndpointHostLastAttr != attrJ+1 {
					symbolEndpointHostLastAttr = attrJ + 1
					symbolEndpointHostCount++
				}
				val := symbolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				symbolEndpointHostVal = val
			case kindLlmCallFinishReason:
				if symbolFinishReasonLastAttr != attrJ+1 {
					symbolFinishReasonLastAttr = attrJ + 1
					symbolFinishReasonCount++
				}
				val := symbolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				symbolFinishReasonVal = val
			}
		}
	}
	if symbolKindCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbol").Str("membership", "runtimeKindLlmCall").Int("got", symbolKindCount).Errorf("slot symbol@runtimeKindLlmCall (field Kind) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolKindCount)
		return
	}
	if symbolKindCount == 1 {
		row.Kind = symbolKindVal
		present = true
	}
	if symbolCallIdCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbol").Str("membership", "llmCallId").Int("got", symbolCallIdCount).Errorf("slot symbol@llmCallId (field CallId) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolCallIdCount)
		return
	}
	if symbolCallIdCount == 1 {
		row.CallId = symbolCallIdVal
		present = true
	}
	if symbolAppCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbol").Str("membership", "llmCallApp").Int("got", symbolAppCount).Errorf("slot symbol@llmCallApp (field App) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolAppCount)
		return
	}
	if symbolAppCount == 1 {
		row.App = symbolAppVal
		present = true
	}
	if symbolPurposeCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbol").Str("membership", "llmCallPurpose").Int("got", symbolPurposeCount).Errorf("slot symbol@llmCallPurpose (field Purpose) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolPurposeCount)
		return
	}
	if symbolPurposeCount == 1 {
		row.Purpose = symbolPurposeVal
		present = true
	}
	if symbolSensitivityCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbol").Str("membership", "llmCallSensitivity").Int("got", symbolSensitivityCount).Errorf("slot symbol@llmCallSensitivity (field Sensitivity) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolSensitivityCount)
		return
	}
	if symbolSensitivityCount == 1 {
		row.Sensitivity = symbolSensitivityVal
		present = true
	}
	if symbolModelCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbol").Str("membership", "llmCallModel").Int("got", symbolModelCount).Errorf("slot symbol@llmCallModel (field Model) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolModelCount)
		return
	}
	if symbolModelCount == 1 {
		row.Model = symbolModelVal
		present = true
	}
	if symbolEndpointHostCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbol").Str("membership", "llmCallEndpointHost").Int("got", symbolEndpointHostCount).Errorf("slot symbol@llmCallEndpointHost (field EndpointHost) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolEndpointHostCount)
		return
	}
	if symbolEndpointHostCount == 1 {
		row.EndpointHost = symbolEndpointHostVal
		present = true
	}
	if symbolFinishReasonCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbol").Str("membership", "llmCallFinishReason").Int("got", symbolFinishReasonCount).Errorf("slot symbol@llmCallFinishReason (field FinishReason) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolFinishReasonCount)
		return
	}
	if symbolFinishReasonCount == 1 {
		row.FinishReason = symbolFinishReasonVal
		present = true
	}
	// --- u64Array. ---
	var u64ArrayInstanceVal uint64
	var u64ArrayInstanceCount int
	var u64ArrayInstanceLastAttr int64
	var u64ArrayPromptBytesVal uint64
	var u64ArrayPromptBytesCount int
	var u64ArrayPromptBytesLastAttr int64
	var u64ArrayCompletionBytesVal uint64
	var u64ArrayCompletionBytesCount int
	var u64ArrayCompletionBytesLastAttr int64
	var u64ArrayElapsedMsVal uint64
	var u64ArrayElapsedMsCount int
	var u64ArrayElapsedMsLastAttr int64
	nu64Array := u64ArrayAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nu64Array; attrJ++ {
		for membID := range u64ArrayMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindLlmCallInstance:
				if u64ArrayInstanceLastAttr != attrJ+1 {
					u64ArrayInstanceLastAttr = attrJ + 1
					u64ArrayInstanceCount++
				}
				val, valErr := u64ArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "u64Array").Str("membership", "llmCallInstance").Str("field", "Instance").Errorf("slot u64Array@llmCallInstance (field Instance) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				u64ArrayInstanceVal = val
			case kindLlmCallPromptBytes:
				if u64ArrayPromptBytesLastAttr != attrJ+1 {
					u64ArrayPromptBytesLastAttr = attrJ + 1
					u64ArrayPromptBytesCount++
				}
				val, valErr := u64ArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "u64Array").Str("membership", "llmCallPromptBytes").Str("field", "PromptBytes").Errorf("slot u64Array@llmCallPromptBytes (field PromptBytes) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				u64ArrayPromptBytesVal = val
			case kindLlmCallCompletionBytes:
				if u64ArrayCompletionBytesLastAttr != attrJ+1 {
					u64ArrayCompletionBytesLastAttr = attrJ + 1
					u64ArrayCompletionBytesCount++
				}
				val, valErr := u64ArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "u64Array").Str("membership", "llmCallCompletionBytes").Str("field", "CompletionBytes").Errorf("slot u64Array@llmCallCompletionBytes (field CompletionBytes) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				u64ArrayCompletionBytesVal = val
			case kindLlmCallElapsedMs:
				if u64ArrayElapsedMsLastAttr != attrJ+1 {
					u64ArrayElapsedMsLastAttr = attrJ + 1
					u64ArrayElapsedMsCount++
				}
				val, valErr := u64ArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "u64Array").Str("membership", "llmCallElapsedMs").Str("field", "ElapsedMs").Errorf("slot u64Array@llmCallElapsedMs (field ElapsedMs) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				u64ArrayElapsedMsVal = val
			}
		}
	}
	if u64ArrayInstanceCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "u64Array").Str("membership", "llmCallInstance").Int("got", u64ArrayInstanceCount).Errorf("slot u64Array@llmCallInstance (field Instance) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", u64ArrayInstanceCount)
		return
	}
	if u64ArrayInstanceCount == 1 {
		row.Instance = u64ArrayInstanceVal
		present = true
	}
	if u64ArrayPromptBytesCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "u64Array").Str("membership", "llmCallPromptBytes").Int("got", u64ArrayPromptBytesCount).Errorf("slot u64Array@llmCallPromptBytes (field PromptBytes) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", u64ArrayPromptBytesCount)
		return
	}
	if u64ArrayPromptBytesCount == 1 {
		row.PromptBytes = u64ArrayPromptBytesVal
		present = true
	}
	if u64ArrayCompletionBytesCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "u64Array").Str("membership", "llmCallCompletionBytes").Int("got", u64ArrayCompletionBytesCount).Errorf("slot u64Array@llmCallCompletionBytes (field CompletionBytes) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", u64ArrayCompletionBytesCount)
		return
	}
	if u64ArrayCompletionBytesCount == 1 {
		row.CompletionBytes = u64ArrayCompletionBytesVal
		present = true
	}
	if u64ArrayElapsedMsCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "u64Array").Str("membership", "llmCallElapsedMs").Int("got", u64ArrayElapsedMsCount).Errorf("slot u64Array@llmCallElapsedMs (field ElapsedMs) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", u64ArrayElapsedMsCount)
		return
	}
	if u64ArrayElapsedMsCount == 1 {
		row.ElapsedMs = u64ArrayElapsedMsVal
		present = true
	}
	// --- u32Array. ---
	var u32ArrayMessagesVal uint32
	var u32ArrayMessagesCount int
	var u32ArrayMessagesLastAttr int64
	var u32ArrayToolsVal uint32
	var u32ArrayToolsCount int
	var u32ArrayToolsLastAttr int64
	var u32ArrayInputTokensVal uint32
	var u32ArrayInputTokensCount int
	var u32ArrayInputTokensLastAttr int64
	var u32ArrayOutputTokensVal uint32
	var u32ArrayOutputTokensCount int
	var u32ArrayOutputTokensLastAttr int64
	var u32ArrayToolCallsVal uint32
	var u32ArrayToolCallsCount int
	var u32ArrayToolCallsLastAttr int64
	nu32Array := u32ArrayAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nu32Array; attrJ++ {
		for membID := range u32ArrayMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindLlmCallMessages:
				if u32ArrayMessagesLastAttr != attrJ+1 {
					u32ArrayMessagesLastAttr = attrJ + 1
					u32ArrayMessagesCount++
				}
				val, valErr := u32ArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "u32Array").Str("membership", "llmCallMessages").Str("field", "Messages").Errorf("slot u32Array@llmCallMessages (field Messages) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				u32ArrayMessagesVal = val
			case kindLlmCallTools:
				if u32ArrayToolsLastAttr != attrJ+1 {
					u32ArrayToolsLastAttr = attrJ + 1
					u32ArrayToolsCount++
				}
				val, valErr := u32ArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "u32Array").Str("membership", "llmCallTools").Str("field", "Tools").Errorf("slot u32Array@llmCallTools (field Tools) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				u32ArrayToolsVal = val
			case kindLlmCallInputTokens:
				if u32ArrayInputTokensLastAttr != attrJ+1 {
					u32ArrayInputTokensLastAttr = attrJ + 1
					u32ArrayInputTokensCount++
				}
				val, valErr := u32ArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "u32Array").Str("membership", "llmCallInputTokens").Str("field", "InputTokens").Errorf("slot u32Array@llmCallInputTokens (field InputTokens) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				u32ArrayInputTokensVal = val
			case kindLlmCallOutputTokens:
				if u32ArrayOutputTokensLastAttr != attrJ+1 {
					u32ArrayOutputTokensLastAttr = attrJ + 1
					u32ArrayOutputTokensCount++
				}
				val, valErr := u32ArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "u32Array").Str("membership", "llmCallOutputTokens").Str("field", "OutputTokens").Errorf("slot u32Array@llmCallOutputTokens (field OutputTokens) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				u32ArrayOutputTokensVal = val
			case kindLlmCallToolCalls:
				if u32ArrayToolCallsLastAttr != attrJ+1 {
					u32ArrayToolCallsLastAttr = attrJ + 1
					u32ArrayToolCallsCount++
				}
				val, valErr := u32ArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "u32Array").Str("membership", "llmCallToolCalls").Str("field", "ToolCalls").Errorf("slot u32Array@llmCallToolCalls (field ToolCalls) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				u32ArrayToolCallsVal = val
			}
		}
	}
	if u32ArrayMessagesCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "u32Array").Str("membership", "llmCallMessages").Int("got", u32ArrayMessagesCount).Errorf("slot u32Array@llmCallMessages (field Messages) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", u32ArrayMessagesCount)
		return
	}
	if u32ArrayMessagesCount == 1 {
		row.Messages = u32ArrayMessagesVal
		present = true
	}
	if u32ArrayToolsCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "u32Array").Str("membership", "llmCallTools").Int("got", u32ArrayToolsCount).Errorf("slot u32Array@llmCallTools (field Tools) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", u32ArrayToolsCount)
		return
	}
	if u32ArrayToolsCount == 1 {
		row.Tools = u32ArrayToolsVal
		present = true
	}
	if u32ArrayInputTokensCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "u32Array").Str("membership", "llmCallInputTokens").Int("got", u32ArrayInputTokensCount).Errorf("slot u32Array@llmCallInputTokens (field InputTokens) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", u32ArrayInputTokensCount)
		return
	}
	if u32ArrayInputTokensCount == 1 {
		row.InputTokens = u32ArrayInputTokensVal
		present = true
	}
	if u32ArrayOutputTokensCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "u32Array").Str("membership", "llmCallOutputTokens").Int("got", u32ArrayOutputTokensCount).Errorf("slot u32Array@llmCallOutputTokens (field OutputTokens) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", u32ArrayOutputTokensCount)
		return
	}
	if u32ArrayOutputTokensCount == 1 {
		row.OutputTokens = u32ArrayOutputTokensVal
		present = true
	}
	if u32ArrayToolCallsCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "u32Array").Str("membership", "llmCallToolCalls").Int("got", u32ArrayToolCallsCount).Errorf("slot u32Array@llmCallToolCalls (field ToolCalls) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", u32ArrayToolCallsCount)
		return
	}
	if u32ArrayToolCallsCount == 1 {
		row.ToolCalls = u32ArrayToolCallsVal
		present = true
	}
	// --- bool. ---
	var boolIncompleteVal bool
	var boolIncompleteCount int
	var boolIncompleteLastAttr int64
	var boolRefusedVal bool
	var boolRefusedCount int
	var boolRefusedLastAttr int64
	nbool := boolAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nbool; attrJ++ {
		for membID := range boolMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindLlmCallIncomplete:
				if boolIncompleteLastAttr != attrJ+1 {
					boolIncompleteLastAttr = attrJ + 1
					boolIncompleteCount++
				}
				val := boolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				boolIncompleteVal = val
			case kindLlmCallRefused:
				if boolRefusedLastAttr != attrJ+1 {
					boolRefusedLastAttr = attrJ + 1
					boolRefusedCount++
				}
				val := boolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				boolRefusedVal = val
			}
		}
	}
	if boolIncompleteCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "bool").Str("membership", "llmCallIncomplete").Int("got", boolIncompleteCount).Errorf("slot bool@llmCallIncomplete (field Incomplete) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", boolIncompleteCount)
		return
	}
	if boolIncompleteCount == 1 {
		row.Incomplete = boolIncompleteVal
		present = true
	}
	if boolRefusedCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "bool").Str("membership", "llmCallRefused").Int("got", boolRefusedCount).Errorf("slot bool@llmCallRefused (field Refused) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", boolRefusedCount)
		return
	}
	if boolRefusedCount == 1 {
		row.Refused = boolRefusedVal
		present = true
	}
	// --- stringArray. ---
	var stringArrayErrorSlice []string
	var stringArrayErrorCount int
	var stringArrayErrorLastAttr int64
	nstringArray := stringArrayAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nstringArray; attrJ++ {
		for membID := range stringArrayMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindLlmCallError:
				if stringArrayErrorLastAttr != attrJ+1 {
					stringArrayErrorLastAttr = attrJ + 1
					stringArrayErrorCount++
				}
				for v := range stringArrayAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
					stringArrayErrorSlice = append(stringArrayErrorSlice, v)
				}
			}
		}
	}
	if stringArrayErrorCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "llmCallError").Int("got", stringArrayErrorCount).Errorf("slot stringArray@llmCallError (field Error) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", stringArrayErrorCount)
		return
	}
	if stringArrayErrorSlice != nil {
		row.Error = stringArrayErrorSlice
		present = true
	}
	return
}
