//go:build integration

package anchor

import (
	"context"
	"embed"
	_ "embed"
	"fmt"
	"strings"
	"testing"

	"github.com/stergiotis/boxer/public/keelson/data/chclient"
	"github.com/stergiotis/boxer/public/semistructured/leeway/lwsqlsurface"
	"github.com/stergiotis/boxer/public/unsafeperf"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

//go:embed *.sql
var sqlFileContent embed.FS

func getSqlContent(path string, t *testing.T) string {
	b, err := sqlFileContent.ReadFile(path)
	require.NoError(t, err, path)
	return unsafeperf.UnsafeBytesToString(b)
}

func TestLeewayClickHouse(t *testing.T) {
	ctx := context.Background()
	ch := newAnchorChClient()

	if err := ch.Ping(ctx); err != nil {
		t.Skipf("ClickHouse not available on %s, skipping test: %v", chclient.ConfigFromEnv().URL, err)
	}

	err := setupClickHouseDdl(ctx, ch)
	require.NoError(t, err)

	// Query 1 uses the co/ragged function pack (ADR-0162); reconcile the
	// whole read surface the way any connecting host would (ADR-0171 §SD2).
	err = lwsqlsurface.Install(ctx, ch)
	require.NoError(t, err)

	records, err := GenerateAlpineEvents(nil, 20)
	require.NoError(t, err)
	records, err = GenerateCyberThreatEvents(records)
	require.NoError(t, err)
	records, err = GenerateDroneMissionEvents(records)
	require.NoError(t, err)

	defer func() {
		for _, r := range records {
			r.Release()
		}
	}()

	t.Log("Inserting Arrow records into ClickHouse...")
	err = ch.InsertArrow(ctx, "anchor.facts", records)
	require.NoError(t, err)

	// The .out.sql artifacts are the executable (physical, canonical) form of
	// the friendly-handle sources, regenerated by TestDqlPipelineGeneration.
	for _, p := range []string{
		"card_anchor_dql_query1.out.sql",
		"card_anchor_dql_query2.out.sql",
		"card_anchor_dql_query3.out.sql",
		"card_anchor_dql_query4.out.sql",
		"card_anchor_dql_query5.out.sql",
		"card_anchor_dql_query6.out.sql",
		"card_anchor_dql_query7.out.sql",
	} {
		q := getSqlContent(p, t)
		result, err := queryToString(ctx, ch, q)
		assert.NoError(t, err, q, result)
		fmt.Printf("=== %s ===\n%s\n", p, result)
	}

	// Query 8 is the write-back demo (ADR-0181 §SD8 M2): create the silver
	// target, execute the INSERT … SELECT whose mints adopted its names, and
	// verify the slice landed. Types are the plain equivalents of facts' —
	// an INSERT converts, and a Memory-engine fixture earns no codecs.
	err = ch.Exec(ctx, `CREATE OR REPLACE TABLE anchor.silver (
		"id:id:u64:47::0:" UInt64,
		"id:naturalKey:y:4::0:" String,
		"tv:symbol:value:val:s:124::I:0::data" Array(String),
		"tv:symbol:lr:lr:u64:1247:::0::data" Array(UInt64),
		"tv:symbol:lrcard:lrcard:u64:4E:::0::data" Array(UInt64)
	) ENGINE = Memory`)
	require.NoError(t, err)
	err = ch.Exec(ctx, getSqlContent("card_anchor_dql_query8.out.sql", t))
	require.NoError(t, err)
	silver, err := queryToString(ctx, ch,
		`SELECT count(), countIf(has("tv:symbol:value:val:s:124::I:0::data", 'DDOS')) FROM anchor.silver`)
	require.NoError(t, err)
	require.Equal(t, "20\t2", strings.TrimSpace(silver),
		"the cyber slice: 20 incidents, of which the two DDOS rows (i ∈ {5,15})")
}
