// Code generated by boxer/public/semistructured/leeway/marshall/go/marshallgen — DO NOT EDIT.

package sharedsection

import (
	"iter"

	"github.com/stergiotis/boxer/public/observability/eh/eb"
	dmlruntime "github.com/stergiotis/boxer/public/semistructured/leeway/dml/runtime"
	raruntime "github.com/stergiotis/boxer/public/semistructured/leeway/readaccess/runtime"
)

// --- Caller-assigned membership ids (registry-stable target). ---

const (
	kindAssetPhase uint64 = 7002
)

// stateSymbolAttrI is the InAttr-side view of the symbol section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type stateSymbolAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// stateSymbolSecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type stateSymbolSecI[Attr any, Ent any] interface {
	BeginAttribute(value string) Attr
	EndSection() Ent
}

// stateEntityI is the entity-builder surface stateAddSections drives.
// It always lists the per-section getters; the entity-frame methods
// (BeginEntity / plain setters / CommitEntity) are added only for the
// full codec's BuildEntities. AddSections stacks sections onto a frame
// the caller already owns, so it needs none of them — which lets a
// store drive it with a builder whose frame control is unexported
// (ADR-0100 SD6). Ent is the builder pointer.
type stateEntityI[
	SymbolAttr stateSymbolAttrI,
	SymbolSec stateSymbolSecI[SymbolAttr, Ent],
	Ent any,
] interface {
	GetSectionSymbol() SymbolSec
}

// stateEmitSectionSymbol writes this kind's symbol attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func stateEmitSectionSymbol[
	SymbolAttr stateSymbolAttrI,
	SymbolSec stateSymbolSecI[SymbolAttr, Ent],
	Ent any,
](symbolSec SymbolSec, row State) (err error) {
	symbolSecAttr_Phase := symbolSec.BeginAttribute(row.Phase)
	symbolSecAttr_Phase.AddMembershipLowCardRefP(kindAssetPhase)
	symbolSecAttr_Phase.EndAttributeP()
	return
}

// stateAddSections contributes this kind's tagged sections to the OPEN
// entity on dml — the BuildEntities body without the entity frame.
// The caller owns BeginEntity / plain setters / CommitEntity.
func stateAddSections[
	SymbolAttr stateSymbolAttrI,
	SymbolSec stateSymbolSecI[SymbolAttr, Ent],
	Ent any,
	DML stateEntityI[
		SymbolAttr, SymbolSec,
		Ent,
	],
](dml DML, row State) (err error) {
	// --- symbol. ---
	symbolSec := dml.GetSectionSymbol()
	err = stateEmitSectionSymbol(symbolSec, row)
	if err != nil {
		return
	}
	symbolSec.EndSection()
	return
}

// stateSymbolAttrsReadI is the Attributes-side view of the symbol section.
type stateSymbolAttrsReadI interface {
	GetAttrValueValue(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) string
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// stateSymbolMembsReadI is the Memberships-side view of the symbol section.
type stateSymbolMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// stateReadRow reads row i as one optional State component: presence-
// gated (a row carrying none of the kind's memberships yields
// present=false), membership-matched. A slot carrying more
// attributes than this kind's shape admits is an error, for every
// shape including containers. Plain-
// bound fields stay zero — the caller owns the envelope. The
// Attrs/Membs readers bind by type inference at the call site, as
// with FillFromArrow.
func stateReadRow[
	SymbolAttrs stateSymbolAttrsReadI,
	SymbolMembs stateSymbolMembsReadI,
](
	i int,
	symbolAttrs SymbolAttrs,
	symbolMembs SymbolMembs,
) (row State, present bool, err error) {
	// --- symbol. ---
	var symbolPhaseVal string
	var symbolPhaseCount int
	var symbolPhaseLastAttr int64
	nsymbol := symbolAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nsymbol; attrJ++ {
		for membID := range symbolMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindAssetPhase:
				if symbolPhaseLastAttr != attrJ+1 {
					symbolPhaseLastAttr = attrJ + 1
					symbolPhaseCount++
				}
				val := symbolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				symbolPhaseVal = val
			}
		}
	}
	if symbolPhaseCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbol").Str("membership", "assetPhase").Int("got", symbolPhaseCount).Errorf("slot symbol@assetPhase (field Phase) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolPhaseCount)
		return
	}
	if symbolPhaseCount == 1 {
		row.Phase = symbolPhaseVal
		present = true
	}
	return
}
