// Code generated by boxer/public/semistructured/leeway/marshall/go/marshallgen — DO NOT EDIT.

package mddocfacts

import (
	"iter"

	"github.com/stergiotis/boxer/public/observability/eh/eb"
	dmlruntime "github.com/stergiotis/boxer/public/semistructured/leeway/dml/runtime"
	raruntime "github.com/stergiotis/boxer/public/semistructured/leeway/readaccess/runtime"
)

// --- Caller-assigned membership ids (registry-stable target). ---

const (
	kindMdTagKind    uint64 = 5764607535919136814
	kindMdTagDoc     uint64 = 5764607535919136815
	kindMdTagDocHash uint64 = 5764607535919136816
	kindMdTagOrdinal uint64 = 5764607535919136817
	kindMdTagLine    uint64 = 5764607535919136818
	kindMdTagSection uint64 = 5764607535919136819
	kindMdTagSource  uint64 = 5764607535919136820
	kindMdTagName    uint64 = 5764607535919136821
)

// mdTagSymbolAttrI is the InAttr-side view of the symbol section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type mdTagSymbolAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// mdTagSymbolSecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type mdTagSymbolSecI[Attr any, Ent any] interface {
	BeginAttribute(value string) Attr
	EndSection() Ent
}

// mdTagForeignKeyAttrI is the InAttr-side view of the foreignKey section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type mdTagForeignKeyAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// mdTagForeignKeySecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type mdTagForeignKeySecI[Attr any, Ent any] interface {
	BeginAttribute(value uint64) Attr
	EndSection() Ent
}

// mdTagBlobArrayAttrI is the InAttr-side view of the blobArray section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type mdTagBlobArrayAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// mdTagBlobArraySecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type mdTagBlobArraySecI[Attr any, Ent any] interface {
	BeginAttributeSingle(value []byte) Attr
	EndSection() Ent
}

// mdTagU64ArrayAttrI is the InAttr-side view of the u64Array section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type mdTagU64ArrayAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// mdTagU64ArraySecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type mdTagU64ArraySecI[Attr any, Ent any] interface {
	BeginAttributeSingle(value uint64) Attr
	EndSection() Ent
}

// mdTagEntityI is the entity-builder surface mdTagAddSections drives.
// It always lists the per-section getters; the entity-frame methods
// (BeginEntity / plain setters / CommitEntity) are added only for the
// full codec's BuildEntities. AddSections stacks sections onto a frame
// the caller already owns, so it needs none of them — which lets a
// store drive it with a builder whose frame control is unexported
// (ADR-0100 SD6). Ent is the builder pointer.
type mdTagEntityI[
	SymbolAttr mdTagSymbolAttrI,
	SymbolSec mdTagSymbolSecI[SymbolAttr, Ent],
	ForeignKeyAttr mdTagForeignKeyAttrI,
	ForeignKeySec mdTagForeignKeySecI[ForeignKeyAttr, Ent],
	BlobArrayAttr mdTagBlobArrayAttrI,
	BlobArraySec mdTagBlobArraySecI[BlobArrayAttr, Ent],
	U64ArrayAttr mdTagU64ArrayAttrI,
	U64ArraySec mdTagU64ArraySecI[U64ArrayAttr, Ent],
	Ent any,
] interface {
	GetSectionSymbol() SymbolSec
	GetSectionForeignKey() ForeignKeySec
	GetSectionBlobArray() BlobArraySec
	GetSectionU64Array() U64ArraySec
}

// mdTagEmitSectionSymbol writes this kind's symbol attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func mdTagEmitSectionSymbol[
	SymbolAttr mdTagSymbolAttrI,
	SymbolSec mdTagSymbolSecI[SymbolAttr, Ent],
	Ent any,
](symbolSec SymbolSec, row MdTag) (err error) {
	symbolSecAttr_Kind := symbolSec.BeginAttribute(row.Kind)
	symbolSecAttr_Kind.AddMembershipLowCardRefP(kindMdTagKind)
	symbolSecAttr_Kind.EndAttributeP()
	symbolSecAttr_Source := symbolSec.BeginAttribute(row.Source)
	symbolSecAttr_Source.AddMembershipLowCardRefP(kindMdTagSource)
	symbolSecAttr_Source.EndAttributeP()
	symbolSecAttr_Name := symbolSec.BeginAttribute(row.Name)
	symbolSecAttr_Name.AddMembershipLowCardRefP(kindMdTagName)
	symbolSecAttr_Name.EndAttributeP()
	return
}

// mdTagEmitSectionForeignKey writes this kind's foreignKey attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func mdTagEmitSectionForeignKey[
	ForeignKeyAttr mdTagForeignKeyAttrI,
	ForeignKeySec mdTagForeignKeySecI[ForeignKeyAttr, Ent],
	Ent any,
](foreignKeySec ForeignKeySec, row MdTag) (err error) {
	foreignKeySecAttr_Doc := foreignKeySec.BeginAttribute(row.Doc)
	foreignKeySecAttr_Doc.AddMembershipLowCardRefP(kindMdTagDoc)
	foreignKeySecAttr_Doc.EndAttributeP()
	return
}

// mdTagEmitSectionBlobArray writes this kind's blobArray attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func mdTagEmitSectionBlobArray[
	BlobArrayAttr mdTagBlobArrayAttrI,
	BlobArraySec mdTagBlobArraySecI[BlobArrayAttr, Ent],
	Ent any,
](blobArraySec BlobArraySec, row MdTag) (err error) {
	blobArraySecAttr_DocHash := blobArraySec.BeginAttributeSingle(row.DocHash)
	blobArraySecAttr_DocHash.AddMembershipLowCardRefP(kindMdTagDocHash)
	blobArraySecAttr_DocHash.EndAttributeP()
	return
}

// mdTagEmitSectionU64Array writes this kind's u64Array attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func mdTagEmitSectionU64Array[
	U64ArrayAttr mdTagU64ArrayAttrI,
	U64ArraySec mdTagU64ArraySecI[U64ArrayAttr, Ent],
	Ent any,
](u64ArraySec U64ArraySec, row MdTag) (err error) {
	u64ArraySecAttr_Ordinal := u64ArraySec.BeginAttributeSingle(row.Ordinal)
	u64ArraySecAttr_Ordinal.AddMembershipLowCardRefP(kindMdTagOrdinal)
	u64ArraySecAttr_Ordinal.EndAttributeP()
	u64ArraySecAttr_Line := u64ArraySec.BeginAttributeSingle(row.Line)
	u64ArraySecAttr_Line.AddMembershipLowCardRefP(kindMdTagLine)
	u64ArraySecAttr_Line.EndAttributeP()
	if row.Section.Has {
		u64ArraySecAttr_Section := u64ArraySec.BeginAttributeSingle(row.Section.Val)
		u64ArraySecAttr_Section.AddMembershipLowCardRefP(kindMdTagSection)
		u64ArraySecAttr_Section.EndAttributeP()
	}
	return
}

// mdTagAddSections contributes this kind's tagged sections to the OPEN
// entity on dml — the BuildEntities body without the entity frame.
// The caller owns BeginEntity / plain setters / CommitEntity.
func mdTagAddSections[
	SymbolAttr mdTagSymbolAttrI,
	SymbolSec mdTagSymbolSecI[SymbolAttr, Ent],
	ForeignKeyAttr mdTagForeignKeyAttrI,
	ForeignKeySec mdTagForeignKeySecI[ForeignKeyAttr, Ent],
	BlobArrayAttr mdTagBlobArrayAttrI,
	BlobArraySec mdTagBlobArraySecI[BlobArrayAttr, Ent],
	U64ArrayAttr mdTagU64ArrayAttrI,
	U64ArraySec mdTagU64ArraySecI[U64ArrayAttr, Ent],
	Ent any,
	DML mdTagEntityI[
		SymbolAttr, SymbolSec,
		ForeignKeyAttr, ForeignKeySec,
		BlobArrayAttr, BlobArraySec,
		U64ArrayAttr, U64ArraySec,
		Ent,
	],
](dml DML, row MdTag) (err error) {
	// --- symbol. ---
	symbolSec := dml.GetSectionSymbol()
	err = mdTagEmitSectionSymbol(symbolSec, row)
	if err != nil {
		return
	}
	symbolSec.EndSection()
	// --- foreignKey. ---
	foreignKeySec := dml.GetSectionForeignKey()
	err = mdTagEmitSectionForeignKey(foreignKeySec, row)
	if err != nil {
		return
	}
	foreignKeySec.EndSection()
	// --- blobArray. ---
	blobArraySec := dml.GetSectionBlobArray()
	err = mdTagEmitSectionBlobArray(blobArraySec, row)
	if err != nil {
		return
	}
	blobArraySec.EndSection()
	// --- u64Array. ---
	u64ArraySec := dml.GetSectionU64Array()
	err = mdTagEmitSectionU64Array(u64ArraySec, row)
	if err != nil {
		return
	}
	u64ArraySec.EndSection()
	return
}

// mdTagSymbolAttrsReadI is the Attributes-side view of the symbol section.
type mdTagSymbolAttrsReadI interface {
	GetAttrValueValue(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) string
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// mdTagSymbolMembsReadI is the Memberships-side view of the symbol section.
type mdTagSymbolMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// mdTagForeignKeyAttrsReadI is the Attributes-side view of the foreignKey section.
type mdTagForeignKeyAttrsReadI interface {
	GetAttrValueValue(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) uint64
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// mdTagForeignKeyMembsReadI is the Memberships-side view of the foreignKey section.
type mdTagForeignKeyMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// mdTagBlobArrayAttrsReadI is the Attributes-side view of the blobArray section.
type mdTagBlobArrayAttrsReadI interface {
	GetAttrValueSingle(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) ([]byte, error)
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// mdTagBlobArrayMembsReadI is the Memberships-side view of the blobArray section.
type mdTagBlobArrayMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// mdTagU64ArrayAttrsReadI is the Attributes-side view of the u64Array section.
type mdTagU64ArrayAttrsReadI interface {
	GetAttrValueSingle(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) (uint64, error)
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// mdTagU64ArrayMembsReadI is the Memberships-side view of the u64Array section.
type mdTagU64ArrayMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// mdTagReadRow reads row i as one optional MdTag component: presence-
// gated (a row carrying none of the kind's memberships yields
// present=false), membership-matched. A slot carrying more
// attributes than this kind's shape admits is an error, for every
// shape including containers. Plain-
// bound fields stay zero — the caller owns the envelope. The
// Attrs/Membs readers bind by type inference at the call site, as
// with FillFromArrow.
func mdTagReadRow[
	SymbolAttrs mdTagSymbolAttrsReadI,
	SymbolMembs mdTagSymbolMembsReadI,
	ForeignKeyAttrs mdTagForeignKeyAttrsReadI,
	ForeignKeyMembs mdTagForeignKeyMembsReadI,
	BlobArrayAttrs mdTagBlobArrayAttrsReadI,
	BlobArrayMembs mdTagBlobArrayMembsReadI,
	U64ArrayAttrs mdTagU64ArrayAttrsReadI,
	U64ArrayMembs mdTagU64ArrayMembsReadI,
](
	i int,
	symbolAttrs SymbolAttrs,
	symbolMembs SymbolMembs,
	foreignKeyAttrs ForeignKeyAttrs,
	foreignKeyMembs ForeignKeyMembs,
	blobArrayAttrs BlobArrayAttrs,
	blobArrayMembs BlobArrayMembs,
	u64ArrayAttrs U64ArrayAttrs,
	u64ArrayMembs U64ArrayMembs,
) (row MdTag, present bool, err error) {
	// --- symbol. ---
	var symbolKindVal string
	var symbolKindCount int
	var symbolKindLastAttr int64
	var symbolSourceVal string
	var symbolSourceCount int
	var symbolSourceLastAttr int64
	var symbolNameVal string
	var symbolNameCount int
	var symbolNameLastAttr int64
	nsymbol := symbolAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nsymbol; attrJ++ {
		for membID := range symbolMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindMdTagKind:
				if symbolKindLastAttr != attrJ+1 {
					symbolKindLastAttr = attrJ + 1
					symbolKindCount++
				}
				val := symbolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				symbolKindVal = val
			case kindMdTagSource:
				if symbolSourceLastAttr != attrJ+1 {
					symbolSourceLastAttr = attrJ + 1
					symbolSourceCount++
				}
				val := symbolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				symbolSourceVal = val
			case kindMdTagName:
				if symbolNameLastAttr != attrJ+1 {
					symbolNameLastAttr = attrJ + 1
					symbolNameCount++
				}
				val := symbolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				symbolNameVal = val
			}
		}
	}
	if symbolKindCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbol").Str("membership", "mdTagKind").Int("got", symbolKindCount).Errorf("slot symbol@mdTagKind (field Kind) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolKindCount)
		return
	}
	if symbolKindCount == 1 {
		row.Kind = symbolKindVal
		present = true
	}
	if symbolSourceCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbol").Str("membership", "mdTagSource").Int("got", symbolSourceCount).Errorf("slot symbol@mdTagSource (field Source) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolSourceCount)
		return
	}
	if symbolSourceCount == 1 {
		row.Source = symbolSourceVal
		present = true
	}
	if symbolNameCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "symbol").Str("membership", "mdTagName").Int("got", symbolNameCount).Errorf("slot symbol@mdTagName (field Name) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", symbolNameCount)
		return
	}
	if symbolNameCount == 1 {
		row.Name = symbolNameVal
		present = true
	}
	// --- foreignKey. ---
	var foreignKeyDocVal uint64
	var foreignKeyDocCount int
	var foreignKeyDocLastAttr int64
	nforeignKey := foreignKeyAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nforeignKey; attrJ++ {
		for membID := range foreignKeyMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindMdTagDoc:
				if foreignKeyDocLastAttr != attrJ+1 {
					foreignKeyDocLastAttr = attrJ + 1
					foreignKeyDocCount++
				}
				val := foreignKeyAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				foreignKeyDocVal = val
			}
		}
	}
	if foreignKeyDocCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "foreignKey").Str("membership", "mdTagDoc").Int("got", foreignKeyDocCount).Errorf("slot foreignKey@mdTagDoc (field Doc) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", foreignKeyDocCount)
		return
	}
	if foreignKeyDocCount == 1 {
		row.Doc = foreignKeyDocVal
		present = true
	}
	// --- blobArray. ---
	var blobArrayDocHashVal []byte
	var blobArrayDocHashCount int
	var blobArrayDocHashLastAttr int64
	nblobArray := blobArrayAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nblobArray; attrJ++ {
		for membID := range blobArrayMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindMdTagDocHash:
				if blobArrayDocHashLastAttr != attrJ+1 {
					blobArrayDocHashLastAttr = attrJ + 1
					blobArrayDocHashCount++
				}
				val, valErr := blobArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "blobArray").Str("membership", "mdTagDocHash").Str("field", "DocHash").Errorf("slot blobArray@mdTagDocHash (field DocHash) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				cp := make([]byte, len(val))
				copy(cp, val)
				blobArrayDocHashVal = cp
			}
		}
	}
	if blobArrayDocHashCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "blobArray").Str("membership", "mdTagDocHash").Int("got", blobArrayDocHashCount).Errorf("slot blobArray@mdTagDocHash (field DocHash) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", blobArrayDocHashCount)
		return
	}
	if blobArrayDocHashCount == 1 {
		row.DocHash = blobArrayDocHashVal
		present = true
	}
	// --- u64Array. ---
	var u64ArrayOrdinalVal uint64
	var u64ArrayOrdinalCount int
	var u64ArrayOrdinalLastAttr int64
	var u64ArrayLineVal uint64
	var u64ArrayLineCount int
	var u64ArrayLineLastAttr int64
	var u64ArraySectionVal uint64
	var u64ArraySectionCount int
	var u64ArraySectionLastAttr int64
	nu64Array := u64ArrayAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nu64Array; attrJ++ {
		for membID := range u64ArrayMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindMdTagOrdinal:
				if u64ArrayOrdinalLastAttr != attrJ+1 {
					u64ArrayOrdinalLastAttr = attrJ + 1
					u64ArrayOrdinalCount++
				}
				val, valErr := u64ArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "u64Array").Str("membership", "mdTagOrdinal").Str("field", "Ordinal").Errorf("slot u64Array@mdTagOrdinal (field Ordinal) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				u64ArrayOrdinalVal = val
			case kindMdTagLine:
				if u64ArrayLineLastAttr != attrJ+1 {
					u64ArrayLineLastAttr = attrJ + 1
					u64ArrayLineCount++
				}
				val, valErr := u64ArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "u64Array").Str("membership", "mdTagLine").Str("field", "Line").Errorf("slot u64Array@mdTagLine (field Line) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				u64ArrayLineVal = val
			case kindMdTagSection:
				if u64ArraySectionLastAttr != attrJ+1 {
					u64ArraySectionLastAttr = attrJ + 1
					u64ArraySectionCount++
				}
				val, valErr := u64ArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "u64Array").Str("membership", "mdTagSection").Str("field", "Section").Errorf("slot u64Array@mdTagSection (field Section) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				u64ArraySectionVal = val
			}
		}
	}
	if u64ArrayOrdinalCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "u64Array").Str("membership", "mdTagOrdinal").Int("got", u64ArrayOrdinalCount).Errorf("slot u64Array@mdTagOrdinal (field Ordinal) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", u64ArrayOrdinalCount)
		return
	}
	if u64ArrayOrdinalCount == 1 {
		row.Ordinal = u64ArrayOrdinalVal
		present = true
	}
	if u64ArrayLineCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "u64Array").Str("membership", "mdTagLine").Int("got", u64ArrayLineCount).Errorf("slot u64Array@mdTagLine (field Line) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", u64ArrayLineCount)
		return
	}
	if u64ArrayLineCount == 1 {
		row.Line = u64ArrayLineVal
		present = true
	}
	if u64ArraySectionCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "u64Array").Str("membership", "mdTagSection").Int("got", u64ArraySectionCount).Errorf("slot u64Array@mdTagSection (field Section) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", u64ArraySectionCount)
		return
	}
	if u64ArraySectionCount == 1 {
		row.Section.Val = u64ArraySectionVal
		row.Section.Has = true
		present = true
	}
	return
}
