// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package dto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PopTranslation struct {
	_tab flatbuffers.Table
}

func GetRootAsPopTranslation(buf []byte, offset flatbuffers.UOffsetT) *PopTranslation {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PopTranslation{}
	x.Init(buf, n+offset)
	return x
}

func FinishPopTranslationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPopTranslation(buf []byte, offset flatbuffers.UOffsetT) *PopTranslation {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PopTranslation{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPopTranslationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PopTranslation) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PopTranslation) Table() flatbuffers.Table {
	return rcv._tab
}

func PopTranslationStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func PopTranslationEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
