//go:build llm_generated_opus47

package env

import (
	"fmt"
	"os"
	"slices"
	"strings"
	"text/tabwriter"

	cli "github.com/urfave/cli/v2"
)

// NewCliCommand returns the `env` parent command. Currently exposes
// `env list`, the runtime introspection surface per ADR-0009 §4.
// Mounted into the boxer top-level CLI by public/app/main.go.
//
// extraSubcommands lets sibling packages (notably envdoc) attach their
// own subcommands without forming an env → … → env import cycle —
// public/app/main.go passes them in at wire-up time.
func NewCliCommand(extraSubcommands ...*cli.Command) (cmd *cli.Command) {
	subs := make([]*cli.Command, 0, 1+len(extraSubcommands))
	subs = append(subs, newListCommand())
	subs = append(subs, extraSubcommands...)
	cmd = &cli.Command{
		Name:        "env",
		Usage:       "introspect the env-var registry (ADR-0009)",
		Subcommands: subs,
	}
	return
}

func newListCommand() (cmd *cli.Command) {
	cmd = &cli.Command{
		Name:  "list",
		Usage: "list registered env vars; filter with --category/--origin/--prefix",
		Description: "Lists every env-var Spec registered with the boxer registry by " +
			"this binary's link-time package graph. Sensitive vars display the " +
			"current value as <redacted>. Variables declared in packages this " +
			"binary does not link in (e.g. test-only specs) do not appear; the " +
			"complete catalogue lives in doc/env-vars.md (generated by " +
			"`boxer env gen-docs`).",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "category",
				Usage: "show only specs whose Category equals this value",
			},
			&cli.StringFlag{
				Name:  "origin",
				Usage: "show only specs whose Origin.Module equals this module path",
			},
			&cli.StringFlag{
				Name:  "prefix",
				Usage: "show only specs whose Name starts with this prefix",
			},
		},
		Action: runList,
	}
	return
}

func runList(ctx *cli.Context) (err error) {
	specs := Snapshot()
	cat := ctx.String("category")
	origin := ctx.String("origin")
	prefix := ctx.String("prefix")

	filtered := make([]Spec, 0, len(specs))
	for _, s := range specs {
		if cat != "" && string(s.Category) != cat {
			continue
		}
		if origin != "" && s.Origin.Module != origin {
			continue
		}
		if prefix != "" && !strings.HasPrefix(s.Name, prefix) {
			continue
		}
		filtered = append(filtered, s)
	}

	if len(filtered) == 0 {
		_, err = fmt.Fprintln(os.Stdout, "no env vars match the supplied filters")
		return
	}

	w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
	_, err = fmt.Fprintln(w, "NAME\tTYPE\tCATEGORY\tDEFAULT\tCURRENT\tSENSITIVE\tDESCRIPTION")
	if err != nil {
		return
	}
	for _, s := range filtered {
		current := formatCurrent(s)
		sens := ""
		if s.Sensitive {
			sens = "yes"
		}
		desc := s.Description
		// Truncate Description portion before appending the allowed
		// suffix so the suffix — the whole point of a categorial type
		// — never gets chopped mid-list.
		if len(desc) > 70 {
			desc = desc[:67] + "..."
		}
		if len(s.Allowed) > 0 {
			desc += " (one of: " + strings.Join(s.Allowed, "|") + ")"
		}
		_, err = fmt.Fprintf(w, "%s\t%s\t%s\t%s\t%s\t%s\t%s\n",
			s.Name, s.Type, s.Category, displayValue(s.Default), current, sens, desc)
		if err != nil {
			return
		}
	}
	err = w.Flush()
	return
}

// formatCurrent returns the live env value for a registered spec,
// redacted when Sensitive. Returns the empty string when the env var
// is unset; the caller's display layer renders that as a "—". For
// categorial specs whose env value is outside the declared set, the
// raw value is annotated as "<raw> [invalid; using <default>]" so
// operators see why Get() returns the default.
func formatCurrent(s Spec) (out string) {
	v, ok := LookupVar(s.Name)
	if !ok {
		return ""
	}
	raw, set := v.Lookup()
	if !set {
		return ""
	}
	if s.Sensitive {
		return "<redacted>"
	}
	if len(s.Allowed) > 0 && !slices.Contains(s.Allowed, raw) {
		return fmt.Sprintf("%s [invalid; using %s]", raw, s.Default)
	}
	return raw
}

// displayValue replaces empty values with a single-character placeholder
// so tabwriter columns stay visually aligned. tabwriter would otherwise
// collapse an empty cell into the trailing tab and break alignment for
// the row.
func displayValue(s string) (out string) {
	if s == "" {
		return "—"
	}
	return s
}
