// envgen renders the boxer env-var registry to a Diátaxis reference
// markdown file. Backs the //go:generate directive in
// public/config/env/doc_gen.go (ADR-0009 §4).
//
// The blank imports below load every boxer package that declares an
// env-var Spec; declaration registers the spec process-globally, then
// env.Snapshot() returns the sorted view we render.
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/stergiotis/boxer/public/config/env"

	// Side-effect: load every boxer-owned env-var declaration.
	_ "github.com/stergiotis/boxer/public/dev"
	_ "github.com/stergiotis/boxer/public/docgen"
	_ "github.com/stergiotis/boxer/public/llm/openaichat"
	_ "github.com/stergiotis/boxer/public/observability/logging"
	_ "github.com/stergiotis/boxer/public/observability/tracing"
	_ "github.com/stergiotis/boxer/public/semistructured/leeway/ddl/clickhouse"
)

func main() {
	outPath := flag.String("out", "", "output markdown file ('-' for stdout)")
	flag.Parse()
	if *outPath == "" {
		fmt.Fprintln(os.Stderr, "envgen: -out is required")
		os.Exit(2)
	}
	body := render()
	if *outPath == "-" {
		_, err := os.Stdout.WriteString(body)
		if err != nil {
			fmt.Fprintf(os.Stderr, "envgen: write stdout: %v\n", err)
			os.Exit(1)
		}
		return
	}
	err := os.WriteFile(*outPath, []byte(body), 0o644)
	if err != nil {
		fmt.Fprintf(os.Stderr, "envgen: write %s: %v\n", *outPath, err)
		os.Exit(1)
	}
}

// render produces the full markdown body. Sections:
//
//   - YAML front-matter (type=reference, generated=true).
//   - One H2 per Category, sorted; each H2 holds a five-column table
//     (Name, Type, Default, CLI flag, Sensitive, Description). Pipe
//     characters in descriptions are escaped.
//   - An "Origins" H2 with one row per spec mapping Name → declaring
//     module + package.
func render() (out string) {
	specs := env.Snapshot()

	byCat := map[env.CategoryE][]env.Spec{}
	var cats []env.CategoryE
	seen := map[env.CategoryE]bool{}
	for _, s := range specs {
		if !seen[s.Category] {
			seen[s.Category] = true
			cats = append(cats, s.Category)
		}
		byCat[s.Category] = append(byCat[s.Category], s)
	}
	sort.Slice(cats, func(i, j int) bool {
		return string(cats[i]) < string(cats[j])
	})

	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("type: reference\n")
	b.WriteString("audience: contributor\n")
	b.WriteString("status: stable\n")
	b.WriteString("generated: true\n")
	b.WriteString("generator: internal/cmd/envgen\n")
	b.WriteString(fmt.Sprintf("generated-at: %s\n", time.Now().UTC().Format(time.RFC3339)))
	b.WriteString("---\n\n")

	b.WriteString("# Environment variables\n\n")
	b.WriteString("<!-- Generated by internal/cmd/envgen. Do not edit by hand. -->\n\n")
	b.WriteString(fmt.Sprintf("%d variables across %d categories, declared per ADR-0009. Re-run `go generate ./public/config/env/...` after adding or modifying specs.\n\n",
		len(specs), len(cats)))

	for _, c := range cats {
		list := byCat[c]
		sort.Slice(list, func(i, j int) bool {
			return list[i].Name < list[j].Name
		})
		b.WriteString(fmt.Sprintf("## %s (%d)\n\n", c, len(list)))
		b.WriteString("| Name | Type | Default | CLI flag | Sensitive | Description |\n")
		b.WriteString("|------|------|---------|----------|-----------|-------------|\n")
		for _, s := range list {
			b.WriteString(formatRow(s))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Origins\n\n")
	b.WriteString("| Name | Module | Package |\n")
	b.WriteString("|------|--------|---------|\n")
	for _, s := range specs {
		b.WriteString(fmt.Sprintf("| `%s` | `%s` | `%s` |\n",
			s.Name, s.Origin.Module, s.Origin.Package))
	}

	out = b.String()
	return
}

func formatRow(s env.Spec) (row string) {
	name := fmt.Sprintf("`%s`", s.Name)
	typ := string(s.Type)
	if typ == "" {
		typ = "—"
	}
	def := "—"
	if s.Default != "" {
		def = fmt.Sprintf("`%s`", s.Default)
	}
	flagName := "—"
	if s.CliFlagName != "" {
		flagName = fmt.Sprintf("`--%s`", s.CliFlagName)
	}
	sens := ""
	if s.Sensitive {
		sens = "yes"
	}
	desc := strings.ReplaceAll(s.Description, "|", `\|`)
	desc = strings.ReplaceAll(desc, "\n", " ")
	row = fmt.Sprintf("| %s | %s | %s | %s | %s | %s |\n",
		name, typ, def, flagName, sens, desc)
	return
}
