package markdown

import (
	"iter"
	"slices"
	"strings"

	"github.com/stergiotis/boxer/public/containers"
	"github.com/stergiotis/boxer/public/semistructured/markdown/obsidian"
	"github.com/stergiotis/boxer/public/semistructured/markdown/obsidian/resolver"
	"github.com/stergiotis/boxer/public/thestack/fffi2/typed"
	c "github.com/stergiotis/boxer/public/thestack/imzero2/egui2/bindings"
)

// Doc is a parsed Obsidian-flavored markdown document. Construct with
// [Parse]; render once or many times via [Doc.Render]. Doc is immutable
// after construction and safe to share across goroutines provided the
// frame-time render path remains single-threaded.
//
// imageMaxW / imageMaxH cap the bounding box for FitAspectMaxE on
// inline images sourced from [resolver.ResolverI.LoadImage] — see
// [WithImageMaxSize] for the exact meaning, including what a zero axis
// does. Pixels are decoded once at parse time, stashed on a
// runKindImage paragraph run, and re-sent every frame; the bindings
// doc-comment at [c.ImageVersionTracker] explicitly recommends skipping
// the tracker for static assets ("the per-widget-id one-shot upload
// cost is negligible") because per-widget-id tracking would silently
// break the package-level `var doc = markdown.Parse(...)` retain-once /
// render-many idiom when the same Doc is rendered under multiple id
// scopes.
type Doc struct {
	segments    []segment
	frontmatter *containers.BinarySearchGrowingKV[string, interface{}]
	headings    []HeadingInfo
	dropped     map[string]int
	imageMaxW   uint32
	imageMaxH   uint32
}

// KindCount is one AST node kind the lowering could not represent, and
// how many times it occurred in the document. Kind is goldmark's node
// kind name ("RawHTML", "HTMLBlock", "FootnoteLink", …).
type KindCount struct {
	Kind  string
	Count int
}

// Dropped reports, per AST node kind, how many nodes [Parse] skipped —
// text the reader will never see. It is empty for a document the
// lowering represents in full, which is the case for every book in the
// repo's corpus and the property those tests assert.
//
// This exists because the lowering's failure mode for a construct it does
// not know is *invisible*: the default branch drops the node and the
// prose it covered, so a document reads short with nothing to say it
// did. That is how a tag feature once deleted the text it covered. A
// count is not a fix — the construct still does not render — but it
// turns "we hope nothing is lost" into something a test can gate on, and
// tells an author which construct to rewrite.
//
// Comments (`%%…%%`) are NOT counted: an author asking for text to be
// invisible got what they asked for.
//
// The result is sorted by Kind so callers can compare it directly. It is
// freshly allocated per call and safe to keep.
func (inst *Doc) Dropped() (kinds []KindCount) {
	if len(inst.dropped) == 0 {
		return
	}
	kinds = make([]KindCount, 0, len(inst.dropped))
	for kind, count := range inst.dropped {
		kinds = append(kinds, KindCount{Kind: kind, Count: count})
	}
	slices.SortFunc(kinds, func(a, b KindCount) int {
		return strings.Compare(a.Kind, b.Kind)
	})
	return
}

// HeadingInfo describes one top-level heading discovered during [Parse].
// Slug is generated by lower-casing Text and replacing ' ' with '-',
// matching boxer's [resolver.NoopResolver] fragment sanitiser so
// wikilink targets and section anchors collide on the same key. Level
// is 1..6 (CommonMark ATX heading depth).
//
// A heading carrying an explicit anchor takes its Slug from that anchor
// instead of from Text (`## Creating a table {#creating-a-table}` →
// Slug "creating-a-table"), which is how a section keeps its link
// target across a retitling. The anchor is sanitised the same way, so
// Slug is in one form whatever its origin, and it is stripped from Text
// — see [obsidian.FeatureHeadingAnchor] for the syntax and
// [WithFeatures] to turn it off.
//
// HeadingInfo is what callers feed to a help/TOC sidebar or a section
// jump table; the inline styling (bold/italic/code spans inside the
// heading) is intentionally flattened to plain text.
//
// ByteOffset is the offset of the heading's text within the source the
// doc was parsed from (frontmatter included — goldmark segments are
// absolute). It points at the text, not the `#` marker; consumers that
// slice the source into per-section regions (ADR-0164) normalise to the
// enclosing line start themselves. -1 for the degenerate heading with
// no text lines (`##` alone), which also has empty Text and Slug.
type HeadingInfo struct {
	Text       string
	Slug       string
	Level      uint8
	ByteOffset int
}

// Frontmatter returns the YAML frontmatter parsed from the document
// as a key-sorted KV. Iteration via IteratePairs is deterministic
// across frames (Go's map iteration is not, which would otherwise
// re-shuffle frontmatter UI every frame).
//
// Returns nil when frontmatter is disabled (see [WithFeatures]) or
// when the source contains none.
func (inst *Doc) Frontmatter() (fm *containers.BinarySearchGrowingKV[string, interface{}]) {
	fm = inst.frontmatter
	return
}

// Headings returns the top-level headings discovered during [Parse] in
// document order. The returned slice is owned by Doc; callers that
// mutate it MUST copy first.
//
// The slice is empty for documents without headings. Use this to build
// a table-of-contents sidebar or to resolve in-doc section anchors
// (`#section-slug`) to display titles.
func (inst *Doc) Headings() (headings []HeadingInfo) {
	headings = inst.headings
	return
}

// SlugHeading returns the URL-fragment slug for a heading text, matching
// boxer's [resolver.NoopResolver] sanitiser: lower-cased, ' ' replaced
// by '-'. Exported so help/TOC consumers compose link targets that
// resolve against the same fragment keys [Doc.Headings] populates.
func SlugHeading(text string) (slug string) {
	slug = strings.ToLower(text)
	slug = strings.ReplaceAll(slug, " ", "-")
	return
}

// Render emits the document into the current egui Ui scope, deriving
// ids for embedded widgets (code blocks, blockquotes, callouts, inline
// images) from ids.PrepareSeq(0), PrepareSeq(1), … in document order.
//
// Render does NOT open its own [bindings.IdScope]. Callers that may
// render multiple instances of any markdown doc under the same parent
// scope MUST wrap the call:
//
//	for range c.IdScope(ids.PrepareStr("help-section")) {
//	    helpDoc.Render(ids)
//	}
//
// Rendering inside a layout container that owns its own id context (a
// [bindings.CollapsingHeader] body, [bindings.Window] body, etc.)
// usually does not need an extra wrap — the outer container already
// scopes the ids.
func (inst *Doc) Render(ids *c.WidgetIdStack, opts ...RenderOpt) {
	inst.renderCollect(ids, nil, false, opts)
}

// CodeBlockAction is one code/verbatim block whose action button was
// clicked during a [Doc.RenderActions]/[Doc.RenderActionsN] frame. Text is
// the block's verbatim source (what the author wrote, before the
// highlighter's canonicalisation); Lang is the normalised fence language
// ("go", "sql", "" for an unlabelled/indented block); Index is the block's
// 0-based ordinal among the code blocks in the document, stable across
// frames. Button is the 0-based index of the clicked button within the
// label list — always 0 for the single-button [Doc.RenderActions].
type CodeBlockAction struct {
	Text   string
	Lang   string
	Index  int
	Button int
}

// RenderActions renders the document like [Doc.Render] but additionally
// places a small button labelled `label` above every code/verbatim
// block, and returns the blocks whose button was clicked this frame.
//
// It is an immediate-mode API: the whole document is drawn eagerly when
// RenderActions is called (the returned sequence merely replays clicks
// already captured), so ranging over it, breaking early, or ignoring it
// entirely all leave the same pixels on screen. A single frame can yield
// more than one action when the user clicks several buttons before the
// next paint, so the sequence may produce zero, one, or many values.
//
// Typical use — wire the button to any per-block action:
//
//	for act := range doc.RenderActions(ids, "Copy", markdown.WithScrollToSection(s)) {
//		text := act.Text
//		go func() { _, _ = bus.Request(clipboardbroker.SubjectWrite, []byte(text)) }()
//	}
//
// The renderer itself performs no action — it only reports clicks; the
// caller decides what a click means. CodeView's built-in selectable text
// (Ctrl+C) is unaffected and present whether or not buttons are shown.
func (inst *Doc) RenderActions(ids *c.WidgetIdStack, label string, opts ...RenderOpt) iter.Seq[CodeBlockAction] {
	actions := inst.renderCollect(ids, []string{label}, true, opts)
	return slices.Values(actions)
}

// RenderActionsN is [Doc.RenderActions] with more than one button per
// code/verbatim block: it places one small button for each entry of labels
// (left to right, in a horizontal row) above every block, and returns the
// blocks whose button was clicked this frame, each [CodeBlockAction]
// carrying the 0-based index of the clicked button in its Button field.
// [Doc.RenderActions] is the single-button special case. The same
// immediate-mode contract applies — the document is drawn eagerly and the
// sequence merely replays this frame's clicks.
//
//	for act := range doc.RenderActionsN(ids, []string{"Insert", "Replace"}) {
//		switch act.Button {
//		case 0:
//			insertAtCursor(act.Text)
//		case 1:
//			replaceBuffer(act.Text)
//		}
//	}
func (inst *Doc) RenderActionsN(ids *c.WidgetIdStack, labels []string, opts ...RenderOpt) iter.Seq[CodeBlockAction] {
	actions := inst.renderCollect(ids, labels, true, opts)
	return slices.Values(actions)
}

// renderCollect is the shared render core. actionsEnabled gates the
// per-code-block action buttons (one per actionLabels entry); when true the
// returned slice holds every block whose button was clicked this frame, in
// document order. [Doc.Render] calls it with actions disabled (nil return);
// [Doc.RenderActions]/[Doc.RenderActionsN] wrap the slice as an iter.Seq.
func (inst *Doc) renderCollect(ids *c.WidgetIdStack, actionLabels []string, actionsEnabled bool, opts []RenderOpt) (actions []CodeBlockAction) {
	var ro renderOptions
	for _, opt := range opts {
		opt(&ro)
	}
	rc := renderCtx{
		ids:            ids,
		imageMaxW:      inst.imageMaxW,
		imageMaxH:      inst.imageMaxH,
		scrollToSlug:   ro.scrollToSlug,
		headings:       inst.headings,
		actionsEnabled: actionsEnabled,
		actionLabels:   actionLabels,
		linkClaims:     ro.linkClaims,
		linkClicked:    ro.linkClicked,
		actionAccept:   ro.actionAccept,
	}
	var visible []bool
	if ro.sectionAccept != nil {
		visible = visibleSegments(inst.segments, inst.headings, ro.sectionAccept)
		// Skipped headings would desynchronise the scroll dispatch's
		// heading ordinals (renderCtx.headingIdx), so a section filter
		// disarms scroll-to-section outright — the documented
		// incompatibility on [WithSectionFilter], enforced rather than
		// left to the caller.
		rc.scrollToSlug = ""
	}
	for i := range inst.segments {
		if visible != nil && !visible[i] {
			continue
		}
		inst.segments[i].render(&rc)
	}
	actions = rc.codeActions
	return
}

// visibleSegments computes, per top-level segment, whether it renders
// under the section filter. A section is a top-level heading and
// everything after it up to the next top-level heading; the region
// before the first heading is the doc-level section, slug "". Headings
// nested inside containers (blockquotes, callouts, list items) are not
// section boundaries — they stay with their enclosing section,
// mirroring parseAndLower's side-table collection rule, which is also
// what keeps the walk's heading ordinals aligned with Doc.headings.
func visibleSegments(segments []segment, headings []HeadingInfo, accept func(slug string) bool) (visible []bool) {
	visible = make([]bool, len(segments))
	hIdx := 0
	cur := accept("")
	for i := range segments {
		if segments[i].kind == segKindHeading && hIdx < len(headings) {
			cur = accept(headings[hIdx].Slug)
			hIdx++
		}
		visible[i] = cur
	}
	return
}

// RenderOpt configures a single [Doc.Render] call. Construct via the
// `With*` helpers; passing options to one call does not affect later
// calls — every Render starts from defaults.
type RenderOpt func(*renderOptions)

type renderOptions struct {
	scrollToSlug  string
	linkClaims    func(url string) bool
	linkClicked   func(label string, url string)
	actionAccept  func(text string, lang string) bool
	sectionAccept func(slug string) bool
}

// WithScrollToSection asks the next [Doc.Render] to schedule an egui
// ScrollArea scroll-to-top exactly once, when the heading whose
// [SlugHeading] matches slug is about to render. Empty slug is a
// no-op. The underlying [bindings.ScrollToCursor] op is silently
// dropped when the doc renders outside a ScrollArea, so passing this
// hint is safe even in tooltip / popup contexts that don't scroll.
//
// Callers are expected to gate this option on their own
// "selection-just-changed" signal — re-passing the same slug every
// frame keeps re-scrolling and prevents the user from scrolling
// away. See helphost.HelpHost for the typical "last-scrolled vs
// currently-selected" guard.
func WithScrollToSection(slug string) (opt RenderOpt) {
	opt = func(o *renderOptions) {
		o.scrollToSlug = slug
	}
	return
}

// WithLinkRouter lets the host take ownership of the links it recognises,
// so a link into content the host itself can display navigates in place
// instead of leaving for a browser.
//
// `claims` runs during layout, once per link, and decides how that link
// RENDERS: true makes it an in-document link — visually a link, but a widget
// whose click the host hears about — and false leaves it the ordinary
// [c.HyperlinkTo] hyperlink. It must be a pure function of the URL, because
// it is consulted every frame and a link that changes shape mid-scroll reads
// as a glitch.
//
// `clicked` fires during the render of the frame the click landed on. That is
// the immediate-mode contract the code-block actions already follow: the
// document is drawn eagerly and the callback merely reports what the user
// did to it. A host that navigates in response should record the intent and
// act on it, rather than re-entering Render from inside the callback.
//
// Either function may be nil, which disables routing entirely.
func WithLinkRouter(claims func(url string) bool, clicked func(label string, url string)) (opt RenderOpt) {
	opt = func(o *renderOptions) {
		o.linkClaims = claims
		o.linkClicked = clicked
	}
	return
}

// WithCodeActionFilter limits which fenced blocks carry an action-button row.
//
// `accept` runs during layout, once per block, and decides whether that block
// gets the buttons at all. Without it every fenced block gets them, and a host
// that can only act on some kinds is left suppressing the CLICK while the
// BUTTONS still render — which shows the reader an affordance that does
// nothing. Deciding it here is the only place the buttons can be withheld.
//
// It must be a pure function of the block, because it is consulted every
// frame. Nil accepts everything, which is the default and the behaviour
// before this existed.
func WithCodeActionFilter(accept func(text string, lang string) bool) (opt RenderOpt) {
	opt = func(o *renderOptions) {
		o.actionAccept = accept
	}
	return
}

// WithSectionFilter renders only the sections accept admits: the
// doc-level region before the first heading is consulted as slug "",
// and each top-level heading (with everything under it, to the next
// top-level heading) as its [SlugHeading] slug. Filtering to a matched
// section usually wants its subsections too — expanding the accepted
// set to descendants is the caller's job (help/search.ExpandDescendants),
// because only the caller knows its hit semantics. `accept` must be a
// pure function of the slug for the frame, like the other With* hooks.
//
// Two consequences to design around (ADR-0164 §SD4):
//
//   - Skipping segments shifts the seq-derived ids of everything that
//     still renders (the "ID derivation order" invariant in
//     EXPLANATION.md), so wrap a filtered render in an IdScope keyed
//     by the filter state — abandoning per-widget egui state on filter
//     change is the accepted cost. Keep the UNfiltered path outside
//     that scope so its state survives.
//   - [WithScrollToSection] cannot work across skipped headings (the
//     dispatch counts heading ordinals); combining them disarms the
//     scroll rather than corrupting it.
//
// [CodeBlockAction.Index] stays the ordinal within the *rendered*
// subset — consumers that key on it must not mix indices across
// different filters.
func WithSectionFilter(accept func(slug string) bool) (opt RenderOpt) {
	opt = func(o *renderOptions) {
		o.sectionAccept = accept
	}
	return
}

// renderCtx threads the per-Render-invocation id sequence counter and
// the configured fit cap through the recursive segment walk. A single
// instance is allocated per Render call and threaded by pointer;
// idSeq is bumped at each id-needing widget.
type renderCtx struct {
	ids       *c.WidgetIdStack
	idSeq     uint64
	imageMaxW uint32
	imageMaxH uint32

	// emittedAny goes true once the first segment of this Render call has
	// been reached, and exists only so a heading knows whether it opens
	// the document. A leading heading takes no gap above it; every later
	// one does. It tracks what actually rendered, so under
	// [WithSectionFilter] the first ADMITTED segment is the one treated
	// as the start.
	emittedAny bool

	// Scroll-to-section state. scrollToSlug is the caller-provided
	// target ([WithScrollToSection]); empty disables the dispatch.
	// headings mirrors [Doc.headings] for slug→ordinal lookup at
	// render time, and headingIdx is bumped as the walker emits each
	// heading segment so the dispatch matches against the correct
	// occurrence of the slug when a doc reuses a heading text.
	scrollToSlug string
	headings     []HeadingInfo
	headingIdx   int

	// Code-block action state ([Doc.RenderActions]/[Doc.RenderActionsN]).
	// When actionsEnabled is set, each code block emits one small button per
	// actionLabels entry (in a horizontal row); a click appends a
	// [CodeBlockAction] (carrying the clicked button's 0-based index) to
	// codeActions. codeBlockIdx is bumped per code block so each action
	// carries a stable 0-based ordinal. All are zero/empty under the plain
	// [Doc.Render] path.
	actionsEnabled bool
	actionLabels   []string
	codeActions    []CodeBlockAction
	codeBlockIdx   int

	// Link routing state ([WithLinkRouter]). Both nil under the plain path,
	// which is what keeps every link an ordinary hyperlink.
	linkClaims  func(url string) bool
	linkClicked func(label string, url string)

	// actionAccept gates the per-block action buttons ([WithCodeActionFilter]).
	// Nil accepts every block.
	actionAccept func(text string, lang string) bool
}

// Option configures [Parse]. Pass options at construction time.
type Option func(*config)

type config struct {
	features  obsidian.FeatureE
	resolver  resolver.ResolverI
	imageMaxW uint32
	imageMaxH uint32
}

// imageMaxDefaultW / imageMaxDefaultH are the FitAspectMaxE bounding box
// used when WithImageMaxSize is not supplied. Tuned for typical
// embedded screenshots and asset previews in a sidebar or panel layout;
// callers driving full-width content (e.g. a Markdown reader window)
// should override.
const (
	imageMaxDefaultW uint32 = 800
	imageMaxDefaultH uint32 = 600
)

func defaultConfig() (cfg config) {
	cfg.features = obsidian.FeatureFrontmatter |
		obsidian.FeatureGFM |
		obsidian.FeatureWikilink |
		obsidian.FeatureEmbed |
		obsidian.FeatureCallout |
		obsidian.FeatureHighlight |
		obsidian.FeatureComment |
		obsidian.FeatureTag |
		obsidian.FeatureHeadingAnchor
	cfg.resolver = resolver.NoopResolver{}
	cfg.imageMaxW = imageMaxDefaultW
	cfg.imageMaxH = imageMaxDefaultH
	return
}

// WithFeatures overrides the default obsidian feature set. The default
// covers everything the renderer can lower: frontmatter, GFM (tables,
// strikethrough, task lists), wikilinks, embeds, callouts, ==highlight==
// and %%comment%% stripping, `#tag` spans, and `{#anchor}` heading
// anchors ([obsidian.FeatureHeadingAnchor], which feeds
// [HeadingInfo.Slug]).
//
// Two things the default set does NOT include, contrary to what this
// comment used to claim:
//
//   - GFM footnotes. goldmark's footnote extension is wired to no
//     feature flag at all, so `[^1]` and `[^1]: text` stay literal prose
//     on every path. Nothing is lost, but nothing is rendered as a
//     footnote either.
//   - Math. [obsidian.FeatureMath] is declared and reserved but wired to
//     nothing, and is deliberately not part of [obsidian.FeatureAll];
//     setting it changes neither parse nor render.
//
// Enabling a feature the lowering does not handle is worse than leaving it
// off: an unrecognised inline node reaches the default branch of emitInline
// and is DROPPED, so the text disappears from the document rather than
// rendering unstyled. Every flag in the default set has a case, and
// [Doc.Dropped] reports whatever still got skipped.
func WithFeatures(features obsidian.FeatureE) (opt Option) {
	opt = func(cfg *config) {
		cfg.features = features
	}
	return
}

// WithResolver supplies a custom wikilink/embed resolver. Defaults to
// [resolver.NoopResolver] which generates `/page#heading` URLs without
// vault knowledge. Vault-aware UIs implement [resolver.ResolverI] and
// pass it via this option so wikilinks land on real notes.
//
// The resolver's LoadImage method is consulted at parse time to decode
// inline images (CommonMark `![alt](url)` and Obsidian `![[file.png]]`)
// into RGBA8 pixels. NoopResolver returns ok=false from LoadImage, so
// the default behaviour is the pre-image-widget glyph-hyperlink
// fallback. Supply a vault-aware resolver to opt into real inline
// image rendering.
func WithResolver(r resolver.ResolverI) (opt Option) {
	opt = func(cfg *config) {
		if r != nil {
			cfg.resolver = r
		}
	}
	return
}

// WithImageMaxSize caps the bounding box used when rendering inline
// images: an image larger than (maxW × maxH) is scaled down
// aspect-preserving to fit inside it. Zero on an axis means "no cap on
// that axis". Defaults are (800, 600).
//
// The cap only ever shrinks. An image smaller than the box renders at
// its native size, never blown up to fill it — the renderer passes
// min(cap, native) per axis rather than the cap itself. This is a
// deliberate change of an exported option's semantics (ADR-0180 item 5):
//
//   - A zero axis used to mean "fill available", which inside a vertical
//     ScrollArea — where every markdown document lives — measures ~0 and
//     collapsed the image to nothing. Nobody wants that in a reader.
//   - The cap used to be a target rather than a ceiling, so a 128×80
//     asset under the default box rendered upscaled and soft.
//
// The cap is per-Doc, not per-image; Obsidian's `![[img.png|300]]` size
// suffix is parsed off and ignored (honouring it needs a per-run cap).
func WithImageMaxSize(maxW uint32, maxH uint32) (opt Option) {
	opt = func(cfg *config) {
		cfg.imageMaxW = maxW
		cfg.imageMaxH = maxH
	}
	return
}

// Parse parses obsidian-flavored markdown and returns a renderable
// [Doc]. Hoist the result to a package-level var to amortise parse cost
// across many render frames — it mirrors the
// [codeview.PrepareSql] retain-once / render-many pattern.
func Parse(md []byte, opts ...Option) (doc *Doc) {
	cfg := defaultConfig()
	for _, opt := range opts {
		opt(&cfg)
	}

	segments, frontmatter, headings, dropped := parseAndLower(md, &cfg)
	doc = &Doc{
		segments:    segments,
		frontmatter: frontmatter,
		headings:    headings,
		dropped:     dropped,
		imageMaxW:   cfg.imageMaxW,
		imageMaxH:   cfg.imageMaxH,
	}
	return
}

// segKindE tags a segment in the lowered document tree.
type segKindE uint8

const (
	segKindParagraph segKindE = iota
	segKindHeading
	segKindCodeBlock
	segKindList
	segKindListItem
	segKindBlockquote
	segKindHorizontalRule
	segKindCallout
	segKindTable
)

// runKindE tags a run inside a paragraph or heading segment.
type runKindE uint8

const (
	runKindAtoms runKindE = iota
	runKindLink
	// runKindImage carries pre-decoded RGBA8 pixels plus native
	// dimensions, sourced from resolver.LoadImage at parse time. Rendered
	// inline inside the paragraph's HorizontalWrapped flow via c.Image
	// with FitAspectMaxE and the [Doc]'s configured cap.
	runKindImage
)

// paragraphRun is one slice of a paragraph or heading. A paragraph with
// no embedded hyperlinks has exactly one runKindAtoms run; one with
// hyperlinks (or images) has alternating atoms / link / image runs in
// flow order.
type paragraphRun struct {
	kind  runKindE
	atoms typed.RetainedFffiHolderTyped[c.AtomsS]
	label string
	url   string

	// runKindImage fields. imgPixels is row-major RGBA8 in
	// (imgHeightPx × imgWidthPx) order. Alt-text / Title are not
	// carried — egui's Image widget exposes no tooltip slot through
	// our binding today, so storing them would be premature.
	imgPixels   []uint32
	imgWidthPx  uint32
	imgHeightPx uint32
}

// segment is one node of the lowered document tree. The interpretation
// of each field depends on kind:
//
//   - segKindParagraph / segKindHeading: runs is the inline flow.
//     headingLevel is 1..6 on a heading
//     (0 on a paragraph) and drives the
//     gap the renderer sets above it —
//     the font size is already baked into
//     the runs.
//   - segKindCodeBlock:                  code holds the retained job;
//     codeText holds the verbatim source
//     and codeLang the fence language,
//     both surfaced by [Doc.RenderActions].
//   - segKindList:                       children is a slice of segKindListItem
//     segments; listOrdered + listStart
//     drive the bullet glyph. For an
//     ordered list, listMarkerDigits is
//     the width every marker is padded
//     to so item bodies line up across a
//     digit boundary, and listMarkers
//     holds one pre-built monospace
//     Atoms blob per item (empty for a
//     bullet list, which needs no
//     holder).
//   - segKindListItem:                   children is the item's nested blocks.
//   - segKindBlockquote:                 children is the quoted blocks.
//   - segKindHorizontalRule:             no payload.
//   - segKindCallout:                    children is the inner blocks; the
//     callout* fields drive theme,
//     title and the foldable variant.
//   - segKindTable:                      tableCols is the column count,
//     tableHeader the header row's cell
//     texts (empty ⇒ headerless) and
//     tableCells the body cells in
//     row-major order. Row count is
//     len(tableCells)/tableCols — it is
//     derived, never stored, so the two
//     cannot disagree. tableColRunes is
//     the widest cell per column, in
//     runes, and drives the initial
//     column widths.
type segment struct {
	kind               segKindE
	runs               []paragraphRun
	code               typed.RetainedFffiHolderTyped[c.CodeViewJobS]
	codeText           string
	codeLang           string
	children           []segment
	headingLevel       uint8
	listOrdered        bool
	listStart          uint32
	listMarkerDigits   uint8
	listMarkers        []typed.RetainedFffiHolderTyped[c.AtomsS]
	calloutType        string
	calloutTitle       string
	calloutFoldable    bool
	calloutDefaultOpen bool
	tableCols          uint32
	tableColRunes      []uint32
	tableHeader        []string
	tableCells         []string
}
