#!/bin/bash
# Provision an extracted airgap bundle (see scripts/dev/airgap-bundle.sh; ADR-0095)
# on a target host with no network: position the shipped toolchains, write an
# offline environment file, preflight the non-vendorable requirements, and
# (by default) build.
#
# This is a thin wrapper over scripts/dev/airgap-lib.sh (the canonical core).
#
# Run it from inside the extracted tree:
#     tar -I zstd -xf boxer-airgap-*.tar.zst   # or: tar -xzf ... for the .gz form
#     boxer/scripts/dev/airgap-unbundle.sh
#
# It is idempotent: re-running re-derives the env file and rebuilds.
#
#   --no-build    provision + preflight only; print how to build yourself.
#   --env-only    just (re)write boxer-airgap.env and exit.
#
# After it runs, `source boxer-airgap.env` in any shell to get an offline-
# configured Go (and, in full scope, Rust) toolchain on PATH.

set -euo pipefail

here=$(dirname "$(readlink -f "$BASH_SOURCE")")
repo=$(readlink -f "$here/../..")
# shellcheck source=scripts/dev/airgap-lib.sh
source "$here/airgap-lib.sh"
cd "$repo"

mode=build
case "${1:-}" in
    --no-build) mode=no-build ;;
    --env-only) mode=env-only ;;
    "" ) ;;
    -h|--help) grep '^#' "$BASH_SOURCE" | sed 's/^# \?//'; exit 0 ;;
    *) echo "ERROR: unknown argument: $1" >&2; exit 2 ;;
esac

manifest="$repo/_airgap/MANIFEST"
[ -f "$manifest" ] || airgap_die "$manifest missing — is this an extracted airgap bundle?"
scope="$(sed -n 's/^scope=//p' "$manifest")"
tags="$(tr -d '\n' < "$repo/tags")"

go_tc="$repo/_airgap/toolchains/go"
rust_tc="$repo/_airgap/toolchains/rust"
cargo_home="$repo/_airgap/cargo"
[ -d "$go_tc" ] || airgap_die "shipped Go SDK missing at $go_tc."

# ---- offline environment file -----------------------------------------------
airgap_step "write boxer-airgap.env"
{
    echo "# Sourced offline build environment for boxer. Generated by airgap-unbundle.sh."
    airgap_go_env_lines "$go_tc" single
    if [ "$scope" = full ]; then
        airgap_cargo_env_lines "$rust_tc" "$cargo_home"
    fi
    echo "# Point boxer's OpenAI-compatible client at the environment's ollama, e.g.:"
    echo "#   export OPENAI_BASE_URL=http://127.0.0.1:11434/v1"
} > "$repo/boxer-airgap.env"

# Materialize the cargo source-replacement config with an absolute vendor path.
if [ "$scope" = full ]; then
    [ -d "$rust_tc" ] || airgap_die "full scope but Rust toolchain missing at $rust_tc."
    airgap_cargo_config_materialize "$repo/_airgap/cargo-config.toml.in" \
        "$cargo_home/config.toml" "$repo/rust/vendor"
    echo "    wrote $cargo_home/config.toml (vendored sources -> $repo/rust/vendor)"
fi

[ "$mode" = env-only ] && { echo "=== env-only: done ==="; exit 0; }

# ---- preflight the things no vendoring can supply ---------------------------
airgap_step "preflight (warnings only)"
if [ "$scope" = full ]; then
    airgap_preflight_c_compiler
fi
airgap_preflight_vulkan
# Environment-provided runtime deps (informational — not bundled by design).
airgap_preflight_services clickhouse ffmpeg ollama

[ "$mode" = no-build ] && {
    echo "=== no-build: provisioned. To build: ==="
    echo "    source boxer-airgap.env"
    echo "    go build -tags \"\$(tr -d '\\n' < tags)\" -o app ./public/app"
    [ "$scope" = full ] && echo "    ( cd rust/imzero2 && ./build_rust_headless.sh )"
    exit 0
}

# ---- build ------------------------------------------------------------------
# shellcheck disable=SC1091
source "$repo/boxer-airgap.env"

airgap_step "build Go: app (aggregate CLI)"
go build -tags "$tags" -o "$repo/app" ./public/app
airgap_step "build Go: imzero2 host (tags + binary_log, per build_go.sh)"
go build -tags "$tags,binary_log" -o "$repo/rust/imzero2/main_go" ./public/thestack/cmd/imzero2/

if [ "$scope" = full ]; then
    airgap_step "build Rust: imzero2 headless render host (offline)"
    ( cd rust/imzero2 && ./build_rust_headless.sh )   # CARGO_NET_OFFLINE keeps it offline
else
    airgap_step "place prebuilt imzero2 (go-only scope)"
    dst="rust/imzero2/target/headless/release/imzero2"
    mkdir -p "$(dirname "$dst")"
    cp "$repo/_airgap/prebuilt/imzero2" "$dst"
    echo "    installed $dst"
fi

echo "=== done. Built binaries: ==="
echo "    $repo/app                                   (aggregate CLI; try: ./app dev entry-points)"
echo "    $repo/rust/imzero2/main_go                  (imzero2 Go host)"
echo "    $repo/rust/imzero2/target/headless/release/imzero2  (Rust render head)"
echo "    Run the headless HMI with rust/imzero2/hmi_headless.sh once a Vulkan ICD is present."
