// Code generated; Leeway CT (github.com/stergiotis/boxer/public/app) DO NOT EDIT.

package ctabb

import "github.com/stergiotis/boxer/public/semistructured/leeway/canonicaltypes"

var U8 = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 8, ByteOrderModifier: 0, ScalarModifier: 0}
var I8 = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 8, ByteOrderModifier: 0, ScalarModifier: 0}
var F8 = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 8, ByteOrderModifier: 0, ScalarModifier: 0}
var U16 = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 16, ByteOrderModifier: 0, ScalarModifier: 0}
var I16 = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 16, ByteOrderModifier: 0, ScalarModifier: 0}
var F16 = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 16, ByteOrderModifier: 0, ScalarModifier: 0}
var U32 = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 32, ByteOrderModifier: 0, ScalarModifier: 0}
var I32 = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 32, ByteOrderModifier: 0, ScalarModifier: 0}
var F32 = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 32, ByteOrderModifier: 0, ScalarModifier: 0}
var U64 = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 64, ByteOrderModifier: 0, ScalarModifier: 0}
var I64 = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 64, ByteOrderModifier: 0, ScalarModifier: 0}
var F64 = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 64, ByteOrderModifier: 0, ScalarModifier: 0}
var U8l = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 8, ByteOrderModifier: 'l', ScalarModifier: 0}
var I8l = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 8, ByteOrderModifier: 'l', ScalarModifier: 0}
var F8l = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 8, ByteOrderModifier: 'l', ScalarModifier: 0}
var U16l = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 16, ByteOrderModifier: 'l', ScalarModifier: 0}
var I16l = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 16, ByteOrderModifier: 'l', ScalarModifier: 0}
var F16l = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 16, ByteOrderModifier: 'l', ScalarModifier: 0}
var U32l = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 32, ByteOrderModifier: 'l', ScalarModifier: 0}
var I32l = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 32, ByteOrderModifier: 'l', ScalarModifier: 0}
var F32l = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 32, ByteOrderModifier: 'l', ScalarModifier: 0}
var U64l = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 64, ByteOrderModifier: 'l', ScalarModifier: 0}
var I64l = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 64, ByteOrderModifier: 'l', ScalarModifier: 0}
var F64l = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 64, ByteOrderModifier: 'l', ScalarModifier: 0}
var U8n = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 8, ByteOrderModifier: 'n', ScalarModifier: 0}
var I8n = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 8, ByteOrderModifier: 'n', ScalarModifier: 0}
var F8n = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 8, ByteOrderModifier: 'n', ScalarModifier: 0}
var U16n = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 16, ByteOrderModifier: 'n', ScalarModifier: 0}
var I16n = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 16, ByteOrderModifier: 'n', ScalarModifier: 0}
var F16n = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 16, ByteOrderModifier: 'n', ScalarModifier: 0}
var U32n = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 32, ByteOrderModifier: 'n', ScalarModifier: 0}
var I32n = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 32, ByteOrderModifier: 'n', ScalarModifier: 0}
var F32n = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 32, ByteOrderModifier: 'n', ScalarModifier: 0}
var U64n = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 64, ByteOrderModifier: 'n', ScalarModifier: 0}
var I64n = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 64, ByteOrderModifier: 'n', ScalarModifier: 0}
var F64n = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 64, ByteOrderModifier: 'n', ScalarModifier: 0}
var U8h = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 8, ByteOrderModifier: 0, ScalarModifier: 'h'}
var I8h = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 8, ByteOrderModifier: 0, ScalarModifier: 'h'}
var F8h = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 8, ByteOrderModifier: 0, ScalarModifier: 'h'}
var U16h = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 16, ByteOrderModifier: 0, ScalarModifier: 'h'}
var I16h = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 16, ByteOrderModifier: 0, ScalarModifier: 'h'}
var F16h = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 16, ByteOrderModifier: 0, ScalarModifier: 'h'}
var U32h = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 32, ByteOrderModifier: 0, ScalarModifier: 'h'}
var I32h = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 32, ByteOrderModifier: 0, ScalarModifier: 'h'}
var F32h = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 32, ByteOrderModifier: 0, ScalarModifier: 'h'}
var U64h = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 64, ByteOrderModifier: 0, ScalarModifier: 'h'}
var I64h = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 64, ByteOrderModifier: 0, ScalarModifier: 'h'}
var F64h = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 64, ByteOrderModifier: 0, ScalarModifier: 'h'}
var U8lh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 8, ByteOrderModifier: 'l', ScalarModifier: 'h'}
var I8lh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 8, ByteOrderModifier: 'l', ScalarModifier: 'h'}
var F8lh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 8, ByteOrderModifier: 'l', ScalarModifier: 'h'}
var U16lh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 16, ByteOrderModifier: 'l', ScalarModifier: 'h'}
var I16lh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 16, ByteOrderModifier: 'l', ScalarModifier: 'h'}
var F16lh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 16, ByteOrderModifier: 'l', ScalarModifier: 'h'}
var U32lh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 32, ByteOrderModifier: 'l', ScalarModifier: 'h'}
var I32lh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 32, ByteOrderModifier: 'l', ScalarModifier: 'h'}
var F32lh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 32, ByteOrderModifier: 'l', ScalarModifier: 'h'}
var U64lh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 64, ByteOrderModifier: 'l', ScalarModifier: 'h'}
var I64lh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 64, ByteOrderModifier: 'l', ScalarModifier: 'h'}
var F64lh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 64, ByteOrderModifier: 'l', ScalarModifier: 'h'}
var U8nh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 8, ByteOrderModifier: 'n', ScalarModifier: 'h'}
var I8nh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 8, ByteOrderModifier: 'n', ScalarModifier: 'h'}
var F8nh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 8, ByteOrderModifier: 'n', ScalarModifier: 'h'}
var U16nh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 16, ByteOrderModifier: 'n', ScalarModifier: 'h'}
var I16nh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 16, ByteOrderModifier: 'n', ScalarModifier: 'h'}
var F16nh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 16, ByteOrderModifier: 'n', ScalarModifier: 'h'}
var U32nh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 32, ByteOrderModifier: 'n', ScalarModifier: 'h'}
var I32nh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 32, ByteOrderModifier: 'n', ScalarModifier: 'h'}
var F32nh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 32, ByteOrderModifier: 'n', ScalarModifier: 'h'}
var U64nh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 64, ByteOrderModifier: 'n', ScalarModifier: 'h'}
var I64nh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 64, ByteOrderModifier: 'n', ScalarModifier: 'h'}
var F64nh = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 64, ByteOrderModifier: 'n', ScalarModifier: 'h'}
var U8m = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 8, ByteOrderModifier: 0, ScalarModifier: 'm'}
var I8m = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 8, ByteOrderModifier: 0, ScalarModifier: 'm'}
var F8m = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 8, ByteOrderModifier: 0, ScalarModifier: 'm'}
var U16m = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 16, ByteOrderModifier: 0, ScalarModifier: 'm'}
var I16m = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 16, ByteOrderModifier: 0, ScalarModifier: 'm'}
var F16m = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 16, ByteOrderModifier: 0, ScalarModifier: 'm'}
var U32m = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 32, ByteOrderModifier: 0, ScalarModifier: 'm'}
var I32m = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 32, ByteOrderModifier: 0, ScalarModifier: 'm'}
var F32m = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 32, ByteOrderModifier: 0, ScalarModifier: 'm'}
var U64m = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 64, ByteOrderModifier: 0, ScalarModifier: 'm'}
var I64m = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 64, ByteOrderModifier: 0, ScalarModifier: 'm'}
var F64m = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 64, ByteOrderModifier: 0, ScalarModifier: 'm'}
var U8lm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 8, ByteOrderModifier: 'l', ScalarModifier: 'm'}
var I8lm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 8, ByteOrderModifier: 'l', ScalarModifier: 'm'}
var F8lm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 8, ByteOrderModifier: 'l', ScalarModifier: 'm'}
var U16lm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 16, ByteOrderModifier: 'l', ScalarModifier: 'm'}
var I16lm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 16, ByteOrderModifier: 'l', ScalarModifier: 'm'}
var F16lm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 16, ByteOrderModifier: 'l', ScalarModifier: 'm'}
var U32lm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 32, ByteOrderModifier: 'l', ScalarModifier: 'm'}
var I32lm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 32, ByteOrderModifier: 'l', ScalarModifier: 'm'}
var F32lm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 32, ByteOrderModifier: 'l', ScalarModifier: 'm'}
var U64lm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 64, ByteOrderModifier: 'l', ScalarModifier: 'm'}
var I64lm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 64, ByteOrderModifier: 'l', ScalarModifier: 'm'}
var F64lm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 64, ByteOrderModifier: 'l', ScalarModifier: 'm'}
var U8nm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 8, ByteOrderModifier: 'n', ScalarModifier: 'm'}
var I8nm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 8, ByteOrderModifier: 'n', ScalarModifier: 'm'}
var F8nm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 8, ByteOrderModifier: 'n', ScalarModifier: 'm'}
var U16nm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 16, ByteOrderModifier: 'n', ScalarModifier: 'm'}
var I16nm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 16, ByteOrderModifier: 'n', ScalarModifier: 'm'}
var F16nm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 16, ByteOrderModifier: 'n', ScalarModifier: 'm'}
var U32nm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 32, ByteOrderModifier: 'n', ScalarModifier: 'm'}
var I32nm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 32, ByteOrderModifier: 'n', ScalarModifier: 'm'}
var F32nm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 32, ByteOrderModifier: 'n', ScalarModifier: 'm'}
var U64nm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'u', Width: 64, ByteOrderModifier: 'n', ScalarModifier: 'm'}
var I64nm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'i', Width: 64, ByteOrderModifier: 'n', ScalarModifier: 'm'}
var F64nm = canonicaltypes.MachineNumericTypeAstNode{BaseType: 'f', Width: 64, ByteOrderModifier: 'n', ScalarModifier: 'm'}
var B = canonicaltypes.StringAstNode{BaseType: 'b', WidthModifier: 0, Width: 0, ScalarModifier: 0}
var Y = canonicaltypes.StringAstNode{BaseType: 'y', WidthModifier: 0, Width: 0, ScalarModifier: 0}
var S = canonicaltypes.StringAstNode{BaseType: 's', WidthModifier: 0, Width: 0, ScalarModifier: 0}
var Bh = canonicaltypes.StringAstNode{BaseType: 'b', WidthModifier: 0, Width: 0, ScalarModifier: 'h'}
var Yh = canonicaltypes.StringAstNode{BaseType: 'y', WidthModifier: 0, Width: 0, ScalarModifier: 'h'}
var Sh = canonicaltypes.StringAstNode{BaseType: 's', WidthModifier: 0, Width: 0, ScalarModifier: 'h'}
var Bm = canonicaltypes.StringAstNode{BaseType: 'b', WidthModifier: 0, Width: 0, ScalarModifier: 'm'}
var Ym = canonicaltypes.StringAstNode{BaseType: 'y', WidthModifier: 0, Width: 0, ScalarModifier: 'm'}
var Sm = canonicaltypes.StringAstNode{BaseType: 's', WidthModifier: 0, Width: 0, ScalarModifier: 'm'}
var Z32 = canonicaltypes.TemporalTypeAstNode{BaseType: 'z', Width: 32, ScalarModifier: 0}
var D32 = canonicaltypes.TemporalTypeAstNode{BaseType: 'd', Width: 32, ScalarModifier: 0}
var T32 = canonicaltypes.TemporalTypeAstNode{BaseType: 't', Width: 32, ScalarModifier: 0}
var Z64 = canonicaltypes.TemporalTypeAstNode{BaseType: 'z', Width: 64, ScalarModifier: 0}
var D64 = canonicaltypes.TemporalTypeAstNode{BaseType: 'd', Width: 64, ScalarModifier: 0}
var T64 = canonicaltypes.TemporalTypeAstNode{BaseType: 't', Width: 64, ScalarModifier: 0}
var Z32h = canonicaltypes.TemporalTypeAstNode{BaseType: 'z', Width: 32, ScalarModifier: 'h'}
var D32h = canonicaltypes.TemporalTypeAstNode{BaseType: 'd', Width: 32, ScalarModifier: 'h'}
var T32h = canonicaltypes.TemporalTypeAstNode{BaseType: 't', Width: 32, ScalarModifier: 'h'}
var Z64h = canonicaltypes.TemporalTypeAstNode{BaseType: 'z', Width: 64, ScalarModifier: 'h'}
var D64h = canonicaltypes.TemporalTypeAstNode{BaseType: 'd', Width: 64, ScalarModifier: 'h'}
var T64h = canonicaltypes.TemporalTypeAstNode{BaseType: 't', Width: 64, ScalarModifier: 'h'}
var Z32m = canonicaltypes.TemporalTypeAstNode{BaseType: 'z', Width: 32, ScalarModifier: 'm'}
var D32m = canonicaltypes.TemporalTypeAstNode{BaseType: 'd', Width: 32, ScalarModifier: 'm'}
var T32m = canonicaltypes.TemporalTypeAstNode{BaseType: 't', Width: 32, ScalarModifier: 'm'}
var Z64m = canonicaltypes.TemporalTypeAstNode{BaseType: 'z', Width: 64, ScalarModifier: 'm'}
var D64m = canonicaltypes.TemporalTypeAstNode{BaseType: 'd', Width: 64, ScalarModifier: 'm'}
var T64m = canonicaltypes.TemporalTypeAstNode{BaseType: 't', Width: 64, ScalarModifier: 'm'}
