// Code generated by boxer/public/semistructured/leeway/marshall/go/marshallgen — DO NOT EDIT.

package keelsonqueryreply

import (
	"iter"
	"time"

	"github.com/apache/arrow-go/v18/arrow/array"

	"github.com/stergiotis/boxer/public/observability/eh"
	"github.com/stergiotis/boxer/public/observability/eh/eb"
	dmlruntime "github.com/stergiotis/boxer/public/semistructured/leeway/dml/runtime"
	raruntime "github.com/stergiotis/boxer/public/semistructured/leeway/readaccess/runtime"

	"bytes"
	"io"
	"strings"
	"sync"

	"github.com/apache/arrow-go/v18/arrow"
	"github.com/apache/arrow-go/v18/arrow/ipc"
	"github.com/apache/arrow-go/v18/arrow/memory"

	"github.com/stergiotis/boxer/public/keelson/runtime/buscodec"
	"github.com/stergiotis/boxer/public/keelson/runtime/factsschema/arrowrowcbor"
	"github.com/stergiotis/boxer/public/keelson/runtime/factsschema/cborarrow"
	cbdml "github.com/stergiotis/boxer/public/keelson/runtime/factsschema/dml_cbor"
	"github.com/stergiotis/boxer/public/keelson/runtime/factsschema/ra"
	"github.com/stergiotis/boxer/public/keelson/vdd"
)

// --- Resolved membership ids from vdd. ---

var (
	kindKqReplyOk          uint64
	kindReason             uint64
	kindKqReplyContentType uint64
	kindKqReplyBody        uint64
)

func init() {
	kindKqReplyOk = vdd.MembKqReplyOk.GetId().Value()
	kindReason = vdd.MembReason.GetId().Value()
	kindKqReplyContentType = vdd.MembKqReplyContentType.GetId().Value()
	kindKqReplyBody = vdd.MembKqReplyBody.GetId().Value()
	buscodec.Register[KeelsonQueryReply](keelsonQueryReplyBusCodec)
}

// --- ADR-0042 active-section / active-field hints. ---

// KeelsonQueryReplyActiveSections is the dml_cbor section-index subset this kind
// populates. Passed to InEntityFacts.SetActiveSections so the
// builder skips beginSection list-slot work for inactive sections.
var KeelsonQueryReplyActiveSections = []int{0, 1, 9, 12}

// KeelsonQueryReplyActiveFields is the column-index subset this kind populates
// in the boxer.facts Arrow schema. Lazily computed once via
// sync.OnceValue: scans cbdml.CreateSchemaFacts()'s tv:<section>:...
// field names against this kind's active sections plus the three
// plain prefixes (id:, ts:, lc:). Driven through RecordBuilder.
// SetActiveFields to skip per-row emit walks for unused columns.
var KeelsonQueryReplyActiveFields = sync.OnceValue(func() []int {
	active := map[string]bool{"blobArray": true, "bool": true, "stringArray": true, "textArray": true}
	schema := cbdml.CreateSchemaFacts()
	out := make([]int, 0, 4+len(active)*8)
	for i, f := range schema.Fields() {
		name := f.Name
		switch {
		case strings.HasPrefix(name, "id:"),
			strings.HasPrefix(name, "ts:"),
			strings.HasPrefix(name, "lc:"):
			out = append(out, i)
		case strings.HasPrefix(name, "tv:"):
			rest := name[3:]
			colon := strings.IndexByte(rest, ':')
			if colon < 0 {
				continue
			}
			if active[rest[:colon]] {
				out = append(out, i)
			}
		}
	}
	return out
})

// --- Per-kind InEntityFacts pool. ---

// keelsonQueryReplyPool reuses dml_cbor.InEntityFacts instances across Marshal
// calls. Each carries all ~300 column builders and ~21 section
// orchestrators; un-pooled construction dominates the single-row
// cost. After TransferRecords the state is back to Initial with
// buffers reset to len=0, so reuse within this kind is safe.
var keelsonQueryReplyPool = sync.Pool{
	New: func() any {
		return cbdml.NewInEntityFacts(memory.NewGoAllocator(), 64)
	},
}

// --- SoA columns + AoS Append adapter. ---

// KeelsonQueryReplyColumns is the SoA storage for batches of KeelsonQueryReply rows.
// All slices grow in lockstep — Len returns the row count.
type KeelsonQueryReplyColumns struct {
	FactId     []uint64
	NaturalKey [][]byte
	At         []time.Time

	Ok          []bool
	Reason      []string
	ContentType []string
	Body        [][]byte
}

// Len returns the number of rows currently in the batch.
func (c *KeelsonQueryReplyColumns) Len() int { return len(c.FactId) }

// Append pushes one AoS record into the SoA buffers.
//
// Aliasing: slice and pointer fields (`[]T`, `*roaring.Bitmap`) are
// stored by reference, not copied. Callers must not mutate
// row.<F> after Append unless they want Marshal to read the
// mutation. Scalar fields (T, Option[T]) are copied by value.
func (c *KeelsonQueryReplyColumns) Append(row KeelsonQueryReply) {
	c.FactId = append(c.FactId, row.FactId)
	c.NaturalKey = append(c.NaturalKey, row.NaturalKey)
	c.At = append(c.At, row.At)
	c.Ok = append(c.Ok, row.Ok)
	c.Reason = append(c.Reason, row.Reason)
	c.ContentType = append(c.ContentType, row.ContentType)
	c.Body = append(c.Body, row.Body)
}

// Row reconstructs entity i as an AoS KeelsonQueryReply record. Inverse of
// Append: slice / pointer fields are shared by reference (no
// defensive copy); scalar fields and Option[T] are copied.
func (c *KeelsonQueryReplyColumns) Row(i int) (row KeelsonQueryReply) {
	row.FactId = c.FactId[i]
	row.NaturalKey = c.NaturalKey[i]
	row.At = c.At[i]
	row.Ok = c.Ok[i]
	row.Reason = c.Reason[i]
	row.ContentType = c.ContentType[i]
	row.Body = c.Body[i]
	return
}

// --- Composed-interface BuildEntities helper (schema-agnostic). ---
//
// KeelsonQueryReplyBuildEntities walks the SoA columns and emits one entity per
// row through dml.BeginEntity / per-section BeginAttribute* /
// AddMembershipLowCardRefP / AddToContainerP / EndAttributeP /
// EndSection / CommitEntity. dml is generic — any leeway-DML class
// whose method shapes satisfy the derived interfaces qualifies;
// Go's type inference binds the type parameters at the call site.
//
// Callers drain via dml.TransferRecords (or schema-specific
// equivalents) — left outside the helper because the record type
// varies by target.

// KeelsonQueryReplyBoolAttrI is the InAttr-side view of the bool section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type KeelsonQueryReplyBoolAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// KeelsonQueryReplyBoolSecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type KeelsonQueryReplyBoolSecI[Attr any, Ent any] interface {
	BeginAttribute(value bool) Attr
	EndSection() Ent
}

// KeelsonQueryReplyTextArrayAttrI is the InAttr-side view of the textArray section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type KeelsonQueryReplyTextArrayAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// KeelsonQueryReplyTextArraySecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type KeelsonQueryReplyTextArraySecI[Attr any, Ent any] interface {
	BeginAttributeSingle(value string) Attr
	EndSection() Ent
}

// KeelsonQueryReplyStringArrayAttrI is the InAttr-side view of the stringArray section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type KeelsonQueryReplyStringArrayAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// KeelsonQueryReplyStringArraySecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type KeelsonQueryReplyStringArraySecI[Attr any, Ent any] interface {
	BeginAttributeSingle(value string) Attr
	EndSection() Ent
}

// KeelsonQueryReplyBlobArrayAttrI is the InAttr-side view of the blobArray section. P-variants only —
// every method returns void so no F-bounded `[Self]` parameter is
// needed.
type KeelsonQueryReplyBlobArrayAttrI interface {
	dmlruntime.InAttributeMembershipLowCardRefPI
	EndAttributeP()
}

// KeelsonQueryReplyBlobArraySecI is the Section-side view: opens an attribute and closes
// the section. Attr and Ent are bound at the call site by inference.
type KeelsonQueryReplyBlobArraySecI[Attr any, Ent any] interface {
	BeginAttributeSingle(value []byte) Attr
	EndSection() Ent
}

// KeelsonQueryReplyEntityI is the entity-builder surface KeelsonQueryReplyAddSections drives.
// It always lists the per-section getters; the entity-frame methods
// (BeginEntity / plain setters / CommitEntity) are added only for the
// full codec's BuildEntities. AddSections stacks sections onto a frame
// the caller already owns, so it needs none of them — which lets a
// store drive it with a builder whose frame control is unexported
// (ADR-0100 SD6). Ent is the builder pointer.
type KeelsonQueryReplyEntityI[
	BoolAttr KeelsonQueryReplyBoolAttrI,
	BoolSec KeelsonQueryReplyBoolSecI[BoolAttr, Ent],
	TextArrayAttr KeelsonQueryReplyTextArrayAttrI,
	TextArraySec KeelsonQueryReplyTextArraySecI[TextArrayAttr, Ent],
	StringArrayAttr KeelsonQueryReplyStringArrayAttrI,
	StringArraySec KeelsonQueryReplyStringArraySecI[StringArrayAttr, Ent],
	BlobArrayAttr KeelsonQueryReplyBlobArrayAttrI,
	BlobArraySec KeelsonQueryReplyBlobArraySecI[BlobArrayAttr, Ent],
	Ent any,
] interface {
	BeginEntity() Ent
	SetId(id uint64, naturalKey []byte) Ent
	SetTimestamp(ts time.Time) Ent
	GetSectionBool() BoolSec
	GetSectionTextArray() TextArraySec
	GetSectionStringArray() StringArraySec
	GetSectionBlobArray() BlobArraySec
	CommitEntity() (err error)
}

// KeelsonQueryReplyBuildEntities walks c row-by-row, drives dml's entity / section
// chain, and returns once every row has been committed. The dml
// argument's concrete type binds every type parameter via Go's
// type inference at the call site.
func KeelsonQueryReplyBuildEntities[
	BoolAttr KeelsonQueryReplyBoolAttrI,
	BoolSec KeelsonQueryReplyBoolSecI[BoolAttr, Ent],
	TextArrayAttr KeelsonQueryReplyTextArrayAttrI,
	TextArraySec KeelsonQueryReplyTextArraySecI[TextArrayAttr, Ent],
	StringArrayAttr KeelsonQueryReplyStringArrayAttrI,
	StringArraySec KeelsonQueryReplyStringArraySecI[StringArrayAttr, Ent],
	BlobArrayAttr KeelsonQueryReplyBlobArrayAttrI,
	BlobArraySec KeelsonQueryReplyBlobArraySecI[BlobArrayAttr, Ent],
	Ent any,
	DML KeelsonQueryReplyEntityI[
		BoolAttr, BoolSec,
		TextArrayAttr, TextArraySec,
		StringArrayAttr, StringArraySec,
		BlobArrayAttr, BlobArraySec,
		Ent,
	],
](dml DML, c *KeelsonQueryReplyColumns) (err error) {
	n := c.Len()
	for i := 0; i < n; i++ {
		dml.BeginEntity()
		dml.SetId(c.FactId[i], c.NaturalKey[i])
		dml.SetTimestamp(c.At[i])
		// --- bool. ---
		boolSec := dml.GetSectionBool()
		boolSecAttr_Ok := boolSec.BeginAttribute(c.Ok[i])
		boolSecAttr_Ok.AddMembershipLowCardRefP(kindKqReplyOk)
		boolSecAttr_Ok.EndAttributeP()
		boolSec.EndSection()
		// --- textArray. ---
		textArraySec := dml.GetSectionTextArray()
		textArraySecAttr_Reason := textArraySec.BeginAttributeSingle(c.Reason[i])
		textArraySecAttr_Reason.AddMembershipLowCardRefP(kindReason)
		textArraySecAttr_Reason.EndAttributeP()
		textArraySec.EndSection()
		// --- stringArray. ---
		stringArraySec := dml.GetSectionStringArray()
		stringArraySecAttr_ContentType := stringArraySec.BeginAttributeSingle(c.ContentType[i])
		stringArraySecAttr_ContentType.AddMembershipLowCardRefP(kindKqReplyContentType)
		stringArraySecAttr_ContentType.EndAttributeP()
		stringArraySec.EndSection()
		// --- blobArray. ---
		blobArraySec := dml.GetSectionBlobArray()
		blobArraySecAttr_Body := blobArraySec.BeginAttributeSingle(c.Body[i])
		blobArraySecAttr_Body.AddMembershipLowCardRefP(kindKqReplyBody)
		blobArraySecAttr_Body.EndAttributeP()
		blobArraySec.EndSection()
		err = dml.CommitEntity()
		if err != nil {
			err = eh.Errorf("commit row %d: %w", i, err)
			return
		}
	}
	return
}

// KeelsonQueryReplyEmitSectionBool writes this kind's bool attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func KeelsonQueryReplyEmitSectionBool[
	BoolAttr KeelsonQueryReplyBoolAttrI,
	BoolSec KeelsonQueryReplyBoolSecI[BoolAttr, Ent],
	Ent any,
](boolSec BoolSec, row KeelsonQueryReply) (err error) {
	boolSecAttr_Ok := boolSec.BeginAttribute(row.Ok)
	boolSecAttr_Ok.AddMembershipLowCardRefP(kindKqReplyOk)
	boolSecAttr_Ok.EndAttributeP()
	return
}

// KeelsonQueryReplyEmitSectionTextArray writes this kind's textArray attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func KeelsonQueryReplyEmitSectionTextArray[
	TextArrayAttr KeelsonQueryReplyTextArrayAttrI,
	TextArraySec KeelsonQueryReplyTextArraySecI[TextArrayAttr, Ent],
	Ent any,
](textArraySec TextArraySec, row KeelsonQueryReply) (err error) {
	textArraySecAttr_Reason := textArraySec.BeginAttributeSingle(row.Reason)
	textArraySecAttr_Reason.AddMembershipLowCardRefP(kindReason)
	textArraySecAttr_Reason.EndAttributeP()
	return
}

// KeelsonQueryReplyEmitSectionStringArray writes this kind's stringArray attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func KeelsonQueryReplyEmitSectionStringArray[
	StringArrayAttr KeelsonQueryReplyStringArrayAttrI,
	StringArraySec KeelsonQueryReplyStringArraySecI[StringArrayAttr, Ent],
	Ent any,
](stringArraySec StringArraySec, row KeelsonQueryReply) (err error) {
	stringArraySecAttr_ContentType := stringArraySec.BeginAttributeSingle(row.ContentType)
	stringArraySecAttr_ContentType.AddMembershipLowCardRefP(kindKqReplyContentType)
	stringArraySecAttr_ContentType.EndAttributeP()
	return
}

// KeelsonQueryReplyEmitSectionBlobArray writes this kind's blobArray attributes into an
// ALREADY-OPEN section frame, and does not close it. The caller owns
// the frame: one kind's AddSections, or a builder deferring the close
// until every component that shares the section has written.
func KeelsonQueryReplyEmitSectionBlobArray[
	BlobArrayAttr KeelsonQueryReplyBlobArrayAttrI,
	BlobArraySec KeelsonQueryReplyBlobArraySecI[BlobArrayAttr, Ent],
	Ent any,
](blobArraySec BlobArraySec, row KeelsonQueryReply) (err error) {
	blobArraySecAttr_Body := blobArraySec.BeginAttributeSingle(row.Body)
	blobArraySecAttr_Body.AddMembershipLowCardRefP(kindKqReplyBody)
	blobArraySecAttr_Body.EndAttributeP()
	return
}

// KeelsonQueryReplyAddSections contributes this kind's tagged sections to the OPEN
// entity on dml — the BuildEntities body without the entity frame.
// The caller owns BeginEntity / plain setters / CommitEntity.
func KeelsonQueryReplyAddSections[
	BoolAttr KeelsonQueryReplyBoolAttrI,
	BoolSec KeelsonQueryReplyBoolSecI[BoolAttr, Ent],
	TextArrayAttr KeelsonQueryReplyTextArrayAttrI,
	TextArraySec KeelsonQueryReplyTextArraySecI[TextArrayAttr, Ent],
	StringArrayAttr KeelsonQueryReplyStringArrayAttrI,
	StringArraySec KeelsonQueryReplyStringArraySecI[StringArrayAttr, Ent],
	BlobArrayAttr KeelsonQueryReplyBlobArrayAttrI,
	BlobArraySec KeelsonQueryReplyBlobArraySecI[BlobArrayAttr, Ent],
	Ent any,
	DML KeelsonQueryReplyEntityI[
		BoolAttr, BoolSec,
		TextArrayAttr, TextArraySec,
		StringArrayAttr, StringArraySec,
		BlobArrayAttr, BlobArraySec,
		Ent,
	],
](dml DML, row KeelsonQueryReply) (err error) {
	// --- bool. ---
	boolSec := dml.GetSectionBool()
	err = KeelsonQueryReplyEmitSectionBool(boolSec, row)
	if err != nil {
		return
	}
	boolSec.EndSection()
	// --- textArray. ---
	textArraySec := dml.GetSectionTextArray()
	err = KeelsonQueryReplyEmitSectionTextArray(textArraySec, row)
	if err != nil {
		return
	}
	textArraySec.EndSection()
	// --- stringArray. ---
	stringArraySec := dml.GetSectionStringArray()
	err = KeelsonQueryReplyEmitSectionStringArray(stringArraySec, row)
	if err != nil {
		return
	}
	stringArraySec.EndSection()
	// --- blobArray. ---
	blobArraySec := dml.GetSectionBlobArray()
	err = KeelsonQueryReplyEmitSectionBlobArray(blobArraySec, row)
	if err != nil {
		return
	}
	blobArraySec.EndSection()
	return
}

// --- Composed-interface FillFromArrow helper (schema-agnostic). ---
//
// KeelsonQueryReplyFillFromArrow walks the Arrow record row-by-row and appends
// each entity's plain + tagged-section values into c. Plain columns
// enter as concrete Arrow accessors (uniform across schemas);
// per-section Attrs + Membs bind through type-parameter interfaces.

// KeelsonQueryReplyBoolAttrsReadI is the Attributes-side view of the bool section.
type KeelsonQueryReplyBoolAttrsReadI interface {
	GetAttrValueValue(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) bool
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// KeelsonQueryReplyBoolMembsReadI is the Memberships-side view of the bool section.
type KeelsonQueryReplyBoolMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// KeelsonQueryReplyTextArrayAttrsReadI is the Attributes-side view of the textArray section.
type KeelsonQueryReplyTextArrayAttrsReadI interface {
	GetAttrValueSingle(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) (string, error)
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// KeelsonQueryReplyTextArrayMembsReadI is the Memberships-side view of the textArray section.
type KeelsonQueryReplyTextArrayMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// KeelsonQueryReplyStringArrayAttrsReadI is the Attributes-side view of the stringArray section.
type KeelsonQueryReplyStringArrayAttrsReadI interface {
	GetAttrValueSingle(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) (string, error)
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// KeelsonQueryReplyStringArrayMembsReadI is the Memberships-side view of the stringArray section.
type KeelsonQueryReplyStringArrayMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// KeelsonQueryReplyBlobArrayAttrsReadI is the Attributes-side view of the blobArray section.
type KeelsonQueryReplyBlobArrayAttrsReadI interface {
	GetAttrValueSingle(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) ([]byte, error)
	GetNumberOfAttributes(entityIdx raruntime.EntityIdx) int64
}

// KeelsonQueryReplyBlobArrayMembsReadI is the Memberships-side view of the blobArray section.
type KeelsonQueryReplyBlobArrayMembsReadI interface {
	GetMembValueLowCardRef(entityIdx raruntime.EntityIdx, attrIdx raruntime.AttributeIdx) iter.Seq[uint64]
}

// KeelsonQueryReplyFillFromArrow walks rec row-by-row and appends each entity's
// plain + tagged-section values into c. Plain columns enter as
// concrete Arrow accessors; per-section Attrs + Membs bind through
// type-parameter interfaces.
func KeelsonQueryReplyFillFromArrow[
	BoolAttrs KeelsonQueryReplyBoolAttrsReadI,
	BoolMembs KeelsonQueryReplyBoolMembsReadI,
	TextArrayAttrs KeelsonQueryReplyTextArrayAttrsReadI,
	TextArrayMembs KeelsonQueryReplyTextArrayMembsReadI,
	StringArrayAttrs KeelsonQueryReplyStringArrayAttrsReadI,
	StringArrayMembs KeelsonQueryReplyStringArrayMembsReadI,
	BlobArrayAttrs KeelsonQueryReplyBlobArrayAttrsReadI,
	BlobArrayMembs KeelsonQueryReplyBlobArrayMembsReadI,
](
	c *KeelsonQueryReplyColumns,
	n int,
	idCol *array.Uint64,
	nkCol *array.Binary,
	tsCol *array.Timestamp,
	boolAttrs BoolAttrs,
	boolMembs BoolMembs,
	textArrayAttrs TextArrayAttrs,
	textArrayMembs TextArrayMembs,
	stringArrayAttrs StringArrayAttrs,
	stringArrayMembs StringArrayMembs,
	blobArrayAttrs BlobArrayAttrs,
	blobArrayMembs BlobArrayMembs,
) (err error) {
	for i := 0; i < n; i++ {
		c.FactId = append(c.FactId, idCol.Value(i))
		{
			src := nkCol.Value(i)
			cp := make([]byte, len(src))
			copy(cp, src)
			c.NaturalKey = append(c.NaturalKey, cp)
		}
		c.At = append(c.At, time.Unix(0, int64(tsCol.Value(i))).UTC())
		// --- bool. ---
		var boolOkVal bool
		var boolOkCount int
		var boolOkLastAttr int64
		nbool := boolAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
		for attrJ := int64(0); attrJ < nbool; attrJ++ {
			for membID := range boolMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
				switch membID {
				case kindKqReplyOk:
					if boolOkLastAttr != attrJ+1 {
						boolOkLastAttr = attrJ + 1
						boolOkCount++
					}
					val := boolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
					boolOkVal = val
				}
			}
		}
		if boolOkCount != 1 {
			err = eb.Build().Int("row", i).Str("section", "bool").Str("membership", "kqReplyOk").Int("got", boolOkCount).Errorf("slot bool@kqReplyOk (field Ok) carries %d attributes but the DTO admits exactly 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", boolOkCount)
			return
		}
		c.Ok = append(c.Ok, boolOkVal)
		// --- textArray. ---
		var textArrayReasonVal string
		var textArrayReasonCount int
		var textArrayReasonLastAttr int64
		ntextArray := textArrayAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
		for attrJ := int64(0); attrJ < ntextArray; attrJ++ {
			for membID := range textArrayMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
				switch membID {
				case kindReason:
					if textArrayReasonLastAttr != attrJ+1 {
						textArrayReasonLastAttr = attrJ + 1
						textArrayReasonCount++
					}
					val, valErr := textArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
					if valErr != nil {
						err = eb.Build().Int("row", i).Str("section", "textArray").Str("membership", "reason").Str("field", "Reason").Errorf("slot textArray@reason (field Reason) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
						return
					}
					textArrayReasonVal = val
				}
			}
		}
		if textArrayReasonCount != 1 {
			err = eb.Build().Int("row", i).Str("section", "textArray").Str("membership", "reason").Int("got", textArrayReasonCount).Errorf("slot textArray@reason (field Reason) carries %d attributes but the DTO admits exactly 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", textArrayReasonCount)
			return
		}
		c.Reason = append(c.Reason, textArrayReasonVal)
		// --- stringArray. ---
		var stringArrayContentTypeVal string
		var stringArrayContentTypeCount int
		var stringArrayContentTypeLastAttr int64
		nstringArray := stringArrayAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
		for attrJ := int64(0); attrJ < nstringArray; attrJ++ {
			for membID := range stringArrayMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
				switch membID {
				case kindKqReplyContentType:
					if stringArrayContentTypeLastAttr != attrJ+1 {
						stringArrayContentTypeLastAttr = attrJ + 1
						stringArrayContentTypeCount++
					}
					val, valErr := stringArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
					if valErr != nil {
						err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "kqReplyContentType").Str("field", "ContentType").Errorf("slot stringArray@kqReplyContentType (field ContentType) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
						return
					}
					stringArrayContentTypeVal = val
				}
			}
		}
		if stringArrayContentTypeCount != 1 {
			err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "kqReplyContentType").Int("got", stringArrayContentTypeCount).Errorf("slot stringArray@kqReplyContentType (field ContentType) carries %d attributes but the DTO admits exactly 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", stringArrayContentTypeCount)
			return
		}
		c.ContentType = append(c.ContentType, stringArrayContentTypeVal)
		// --- blobArray. ---
		var blobArrayBodyVal []byte
		var blobArrayBodyCount int
		var blobArrayBodyLastAttr int64
		nblobArray := blobArrayAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
		for attrJ := int64(0); attrJ < nblobArray; attrJ++ {
			for membID := range blobArrayMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
				switch membID {
				case kindKqReplyBody:
					if blobArrayBodyLastAttr != attrJ+1 {
						blobArrayBodyLastAttr = attrJ + 1
						blobArrayBodyCount++
					}
					val, valErr := blobArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
					if valErr != nil {
						err = eb.Build().Int("row", i).Str("section", "blobArray").Str("membership", "kqReplyBody").Str("field", "Body").Errorf("slot blobArray@kqReplyBody (field Body) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
						return
					}
					cp := make([]byte, len(val))
					copy(cp, val)
					blobArrayBodyVal = cp
				}
			}
		}
		if blobArrayBodyCount != 1 {
			err = eb.Build().Int("row", i).Str("section", "blobArray").Str("membership", "kqReplyBody").Int("got", blobArrayBodyCount).Errorf("slot blobArray@kqReplyBody (field Body) carries %d attributes but the DTO admits exactly 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", blobArrayBodyCount)
			return
		}
		c.Body = append(c.Body, blobArrayBodyVal)
	}
	return
}

// KeelsonQueryReplyReadRow reads row i as one optional KeelsonQueryReply component: presence-
// gated (a row carrying none of the kind's memberships yields
// present=false), membership-matched. A slot carrying more
// attributes than this kind's shape admits is an error, for every
// shape including containers. Plain-
// bound fields stay zero — the caller owns the envelope. The
// Attrs/Membs readers bind by type inference at the call site, as
// with FillFromArrow.
func KeelsonQueryReplyReadRow[
	BoolAttrs KeelsonQueryReplyBoolAttrsReadI,
	BoolMembs KeelsonQueryReplyBoolMembsReadI,
	TextArrayAttrs KeelsonQueryReplyTextArrayAttrsReadI,
	TextArrayMembs KeelsonQueryReplyTextArrayMembsReadI,
	StringArrayAttrs KeelsonQueryReplyStringArrayAttrsReadI,
	StringArrayMembs KeelsonQueryReplyStringArrayMembsReadI,
	BlobArrayAttrs KeelsonQueryReplyBlobArrayAttrsReadI,
	BlobArrayMembs KeelsonQueryReplyBlobArrayMembsReadI,
](
	i int,
	boolAttrs BoolAttrs,
	boolMembs BoolMembs,
	textArrayAttrs TextArrayAttrs,
	textArrayMembs TextArrayMembs,
	stringArrayAttrs StringArrayAttrs,
	stringArrayMembs StringArrayMembs,
	blobArrayAttrs BlobArrayAttrs,
	blobArrayMembs BlobArrayMembs,
) (row KeelsonQueryReply, present bool, err error) {
	// --- bool. ---
	var boolOkVal bool
	var boolOkCount int
	var boolOkLastAttr int64
	nbool := boolAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nbool; attrJ++ {
		for membID := range boolMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindKqReplyOk:
				if boolOkLastAttr != attrJ+1 {
					boolOkLastAttr = attrJ + 1
					boolOkCount++
				}
				val := boolAttrs.GetAttrValueValue(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				boolOkVal = val
			}
		}
	}
	if boolOkCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "bool").Str("membership", "kqReplyOk").Int("got", boolOkCount).Errorf("slot bool@kqReplyOk (field Ok) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", boolOkCount)
		return
	}
	if boolOkCount == 1 {
		row.Ok = boolOkVal
		present = true
	}
	// --- textArray. ---
	var textArrayReasonVal string
	var textArrayReasonCount int
	var textArrayReasonLastAttr int64
	ntextArray := textArrayAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < ntextArray; attrJ++ {
		for membID := range textArrayMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindReason:
				if textArrayReasonLastAttr != attrJ+1 {
					textArrayReasonLastAttr = attrJ + 1
					textArrayReasonCount++
				}
				val, valErr := textArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "textArray").Str("membership", "reason").Str("field", "Reason").Errorf("slot textArray@reason (field Reason) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				textArrayReasonVal = val
			}
		}
	}
	if textArrayReasonCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "textArray").Str("membership", "reason").Int("got", textArrayReasonCount).Errorf("slot textArray@reason (field Reason) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", textArrayReasonCount)
		return
	}
	if textArrayReasonCount == 1 {
		row.Reason = textArrayReasonVal
		present = true
	}
	// --- stringArray. ---
	var stringArrayContentTypeVal string
	var stringArrayContentTypeCount int
	var stringArrayContentTypeLastAttr int64
	nstringArray := stringArrayAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nstringArray; attrJ++ {
		for membID := range stringArrayMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindKqReplyContentType:
				if stringArrayContentTypeLastAttr != attrJ+1 {
					stringArrayContentTypeLastAttr = attrJ + 1
					stringArrayContentTypeCount++
				}
				val, valErr := stringArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "kqReplyContentType").Str("field", "ContentType").Errorf("slot stringArray@kqReplyContentType (field ContentType) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				stringArrayContentTypeVal = val
			}
		}
	}
	if stringArrayContentTypeCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "stringArray").Str("membership", "kqReplyContentType").Int("got", stringArrayContentTypeCount).Errorf("slot stringArray@kqReplyContentType (field ContentType) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", stringArrayContentTypeCount)
		return
	}
	if stringArrayContentTypeCount == 1 {
		row.ContentType = stringArrayContentTypeVal
		present = true
	}
	// --- blobArray. ---
	var blobArrayBodyVal []byte
	var blobArrayBodyCount int
	var blobArrayBodyLastAttr int64
	nblobArray := blobArrayAttrs.GetNumberOfAttributes(raruntime.EntityIdx(i))
	for attrJ := int64(0); attrJ < nblobArray; attrJ++ {
		for membID := range blobArrayMembs.GetMembValueLowCardRef(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ)) {
			switch membID {
			case kindKqReplyBody:
				if blobArrayBodyLastAttr != attrJ+1 {
					blobArrayBodyLastAttr = attrJ + 1
					blobArrayBodyCount++
				}
				val, valErr := blobArrayAttrs.GetAttrValueSingle(raruntime.EntityIdx(i), raruntime.AttributeIdx(attrJ))
				if valErr != nil {
					err = eb.Build().Int("row", i).Str("section", "blobArray").Str("membership", "kqReplyBody").Str("field", "Body").Errorf("slot blobArray@kqReplyBody (field Body) has an attribute carrying other than one value, but the field's `,unit` shape admits exactly one: %w", valErr)
					return
				}
				cp := make([]byte, len(val))
				copy(cp, val)
				blobArrayBodyVal = cp
			}
		}
	}
	if blobArrayBodyCount > 1 {
		err = eb.Build().Int("row", i).Str("section", "blobArray").Str("membership", "kqReplyBody").Int("got", blobArrayBodyCount).Errorf("slot blobArray@kqReplyBody (field Body) carries %d attributes but the DTO admits at most 1 — several producers claim this slot, so the reader cannot tell which attribute is this kind's", blobArrayBodyCount)
		return
	}
	if blobArrayBodyCount == 1 {
		row.Body = blobArrayBodyVal
		present = true
	}
	return
}

// --- Sparse-CBOR write (ADR-0042 driver path). ---

// Marshal writes the SoA buffer to w as the sparse-CBOR wire
// format produced through factsschema/dml_cbor. Thin wrapper
// around KeelsonQueryReplyBuildEntities — the per-row chain lives there and
// works against any leeway-DML class that structurally satisfies
// KeelsonQueryReplyEntityI.
func (c *KeelsonQueryReplyColumns) Marshal(w io.Writer) (err error) {
	ent := keelsonQueryReplyPool.Get().(*cbdml.InEntityFacts)
	defer keelsonQueryReplyPool.Put(ent)
	ent.SetActiveSections(KeelsonQueryReplyActiveSections)
	ent.Builder().SetActiveFields(KeelsonQueryReplyActiveFields())
	err = KeelsonQueryReplyBuildEntities(ent, c)
	if err != nil {
		return
	}
	var recs []*arrowrowcbor.Record
	recs, err = ent.TransferRecords(nil)
	if err != nil {
		err = eh.Errorf("keelsonqueryreply: transfer records: %w", err)
		return
	}
	rb := arrowrowcbor.JoinRecords(recs)
	_, err = w.Write(rb)
	if err != nil {
		err = eh.Errorf("keelsonqueryreply: marshal write: %w", err)
	}
	return
}

// --- Read path (ra-based). ---

// keelsonQueryReplyReader composes the readaccess helpers this kind needs.
// Constructed per Unmarshal call; released via defer.
type keelsonQueryReplyReader struct {
	EntityId        *ra.ReadAccessFactsPlainEntityIdAttributes
	EntityTimestamp *ra.ReadAccessFactsPlainEntityTimestampAttributes
	Bool            *ra.ReadAccessFactsTaggedBool
	TextArray       *ra.ReadAccessFactsTaggedTextArray
	StringArray     *ra.ReadAccessFactsTaggedStringArray
	BlobArray       *ra.ReadAccessFactsTaggedBlobArray
}

func newKeelsonQueryReplyReader() *keelsonQueryReplyReader {
	return &keelsonQueryReplyReader{
		EntityId:        ra.NewReadAccessFactsPlainEntityIdAttributes(),
		EntityTimestamp: ra.NewReadAccessFactsPlainEntityTimestampAttributes(),
		Bool:            ra.NewReadAccessFactsTaggedBool(),
		TextArray:       ra.NewReadAccessFactsTaggedTextArray(),
		StringArray:     ra.NewReadAccessFactsTaggedStringArray(),
		BlobArray:       ra.NewReadAccessFactsTaggedBlobArray(),
	}
}

func (r *keelsonQueryReplyReader) loadFromRecord(rec arrow.Record) (err error) {
	err = r.EntityId.LoadFromRecord(rec)
	if err != nil {
		err = eh.Errorf("keelsonqueryreply: load EntityId: %w", err)
		return
	}
	err = r.EntityTimestamp.LoadFromRecord(rec)
	if err != nil {
		err = eh.Errorf("keelsonqueryreply: load EntityTimestamp: %w", err)
		return
	}
	err = r.Bool.LoadFromRecord(rec)
	if err != nil {
		err = eh.Errorf("keelsonqueryreply: load Bool: %w", err)
		return
	}
	err = r.TextArray.LoadFromRecord(rec)
	if err != nil {
		err = eh.Errorf("keelsonqueryreply: load TextArray: %w", err)
		return
	}
	err = r.StringArray.LoadFromRecord(rec)
	if err != nil {
		err = eh.Errorf("keelsonqueryreply: load StringArray: %w", err)
		return
	}
	err = r.BlobArray.LoadFromRecord(rec)
	if err != nil {
		err = eh.Errorf("keelsonqueryreply: load BlobArray: %w", err)
		return
	}
	return
}

func (r *keelsonQueryReplyReader) release() {
	if r == nil {
		return
	}
	if r.EntityId != nil {
		r.EntityId.Release()
	}
	if r.EntityTimestamp != nil {
		r.EntityTimestamp.Release()
	}
	if r.Bool != nil {
		r.Bool.Release()
	}
	if r.TextArray != nil {
		r.TextArray.Release()
	}
	if r.StringArray != nil {
		r.StringArray.Release()
	}
	if r.BlobArray != nil {
		r.BlobArray.Release()
	}
}

// Unmarshal appends one row to c per entity in rec, projecting
// the boxer.facts columns through factsschema/ra. Thin wrapper
// around KeelsonQueryReplyFillFromArrow — the per-row decode lives there.
func (c *KeelsonQueryReplyColumns) Unmarshal(rec arrow.Record) (err error) {
	r := newKeelsonQueryReplyReader()
	defer r.release()
	err = r.loadFromRecord(rec)
	if err != nil {
		return
	}
	n := r.EntityId.Len()
	err = KeelsonQueryReplyFillFromArrow(
		c,
		n,
		r.EntityId.ValueId,
		r.EntityId.ValueNaturalKey,
		r.EntityTimestamp.ValueTs,
		r.Bool.Attributes, r.Bool.Memberships,
		r.TextArray.Attributes, r.TextArray.Memberships,
		r.StringArray.Attributes, r.StringArray.Memberships,
		r.BlobArray.Attributes, r.BlobArray.Memberships,
	)
	return
}

// --- buscodec.CodecI bridge. ---

// KeelsonQueryReplyCodec is the buscodec.CodecI bridge for KeelsonQueryReply. Encodes one row
// through dml_cbor; decodes via cborarrow.Convert + ra-Unmarshal +
// Row(0). Auto-registered in init() so callers using buscodec.Encode
// / Decode route through here instead of the CBOR fallback.
type KeelsonQueryReplyCodec struct{}

var _ buscodec.CodecI = (*KeelsonQueryReplyCodec)(nil)

// keelsonQueryReplyBusCodec is the package-local singleton wired into buscodec.
var keelsonQueryReplyBusCodec = &KeelsonQueryReplyCodec{}

func (inst *KeelsonQueryReplyCodec) Name() (n string) {
	n = "keelsonQueryReply-sparse-cbor"
	return
}

func (inst *KeelsonQueryReplyCodec) ContentType() (ct string) {
	ct = "application/x-runtime-facts+rb;kind=keelsonQueryReply"
	return
}

func (inst *KeelsonQueryReplyCodec) Encode(v any) (b []byte, err error) {
	var row KeelsonQueryReply
	switch x := v.(type) {
	case KeelsonQueryReply:
		row = x
	case *KeelsonQueryReply:
		if x == nil {
			err = eh.Errorf("keelsonqueryreply: Encode nil *KeelsonQueryReply")
			return
		}
		row = *x
	default:
		err = eh.Errorf("keelsonqueryreply: Encode requires KeelsonQueryReply or *KeelsonQueryReply, got %T", v)
		return
	}
	cols := &KeelsonQueryReplyColumns{}
	cols.Append(row)
	var buf bytes.Buffer
	err = cols.Marshal(&buf)
	if err != nil {
		err = eh.Errorf("keelsonqueryreply: Encode marshal: %w", err)
		return
	}
	b = buf.Bytes()
	return
}

func (inst *KeelsonQueryReplyCodec) Decode(b []byte, v any) (err error) {
	target, ok := v.(*KeelsonQueryReply)
	if !ok {
		err = eh.Errorf("keelsonqueryreply: Decode requires *KeelsonQueryReply, got %T", v)
		return
	}
	var arrowBuf bytes.Buffer
	err = cborarrow.Convert(bytes.NewReader(b), &arrowBuf)
	if err != nil {
		err = eh.Errorf("keelsonqueryreply: Decode cborarrow: %w", err)
		return
	}
	rd, err := ipc.NewReader(&arrowBuf)
	if err != nil {
		err = eh.Errorf("keelsonqueryreply: Decode ipc reader: %w", err)
		return
	}
	defer rd.Release()
	if !rd.Next() {
		err = eh.Errorf("keelsonqueryreply: Decode expected one Arrow record, got none")
		return
	}
	rec := rd.RecordBatch()
	defer rec.Release()
	cols := &KeelsonQueryReplyColumns{}
	err = cols.Unmarshal(rec)
	if err != nil {
		err = eh.Errorf("keelsonqueryreply: Decode unmarshal: %w", err)
		return
	}
	if cols.Len() != 1 {
		err = eb.Build().Int("got", cols.Len()).Errorf("keelsonqueryreply: Decode expected 1 row")
		return
	}
	*target = cols.Row(0)
	return
}
