name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  codestat:
    name: codestat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust setup
        run: rustup toolchain install stable --profile minimal
      - name: Install tokei
        run: cargo install --git https://github.com/XAMPPRocky/tokei.git tokei
      - name: Code statistics
        run: tokei . --exclude "*.gen.*" --exclude "*.out.*" --exclude "golay24" --files --sort=code --columns 200
