name: Run all tests

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  gotest:
    name: gotest
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Setup
        run: ./scripts/ci/install.sh
      - name: Check go.mod/go.sum are tidy
        run: go mod tidy --diff
      - name: Verify module checksums
        run: go mod verify
      - name: Run Tests
        run: ./scripts/ci/gotest.sh

  gotest-binary-log:
    name: gotest (binary_log)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Setup
        run: ./scripts/ci/install.sh
      - name: Run binary_log Tests
        run: ./scripts/ci/gotest_binary_log.sh
