name: Run all tests

on: [push]

jobs:
  gotestsum:
    name: gotestsum
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Setup gotestsum
        uses: autero1/action-gotestsum@v2.0.0
        with:
          gotestsum_version: 1.11.0
      - name: Sync go dependencies
        run: go mod tidy
      - name: Download go dependencies
        run: go mod download
      - name: Interact with gotestsum
        run: gotestsum --format short-verbose -- --short ./...
  gotest:
    name: gotest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Setup
        run: ./scripts/install.sh
      - name: Run Tests
        run: ./scripts/gotest.sh
